DROP TABLE IF EXISTS `ads_txn_tif_bas_50c`;
CREATE TABLE `ads_txn_tif_bas_5000c`
(
    UNN_TRNO                             decimal(22, 0) NOT NULL COMMENT '统一交易号',
    TXN_DT                               date           NOT NULL COMMENT '交易日期',
    BOCGP_INST_NO                        varchar(3)                                       DEFAULT NULL COMMENT '中银集团银行号',
    TXN_ACCNO                            varchar(18)                                      NOT NULL COMMENT '交易账号',
    RCRD_NO                              varchar(9)                                       DEFAULT NULL COMMENT '记录号',
    MSAC_ACCNO                           varchar(18)                                      DEFAULT NULL COMMENT '主账户账号',
    CDNO                                 varchar(19)                                      DEFAULT NULL COMMENT '卡号',
    TXN_ACCNO_SBACC_TYPE_NO              varchar(4)                                       DEFAULT NULL COMMENT '交易账号子账户类别号',
    TXN_CURR_ENG_CD                      varchar(3)                                       DEFAULT NULL COMMENT '交易货币英文码',
    DBTCR_IDR                            varchar(1)                                       DEFAULT NULL COMMENT '借贷标识',
    RVRS_IDR                             varchar(1)                                       DEFAULT NULL COMMENT '冲正标识',
    ORI_RCRD_NO                          varchar(9)                                       DEFAULT NULL COMMENT '原记录号',
    TXN_CHNL                             varchar(6)                                       DEFAULT NULL COMMENT '交易渠道',
    CTRYW_CLRG_ORG_CODE                  varchar(5)                                       DEFAULT NULL COMMENT '全国清算机构代码',
    ACC_PRONO                            varchar(5)                                       DEFAULT NULL COMMENT '账户省行机构编号',
    TXN_ACCNO_VLMNO                      varchar(3)                                       DEFAULT NULL COMMENT '交易账号册号',
    TXN_ACCNO_SN                         varchar(4)                                       DEFAULT NULL COMMENT '交易账号序号',
    TXN_SN                               varchar(18)                                      DEFAULT NULL COMMENT '交易流水号',
    UUID                                 varchar(32)                                      DEFAULT NULL COMMENT '外国系统UUID',
    PD_LGCLS                             varchar(4)                                       DEFAULT NULL COMMENT '产品大类',
    PD_AS                                varchar(4)                                       DEFAULT NULL COMMENT '产品子类',
    PD_DES                               varchar(100)                                     DEFAULT NULL COMMENT '产品描述',
    DOC_CTR_NO                           varchar(50)                                      DEFAULT NULL COMMENT '文书合同号',
    ACC_ATR                              varchar(1)                                       DEFAULT NULL COMMENT '账户属性',
    CUS_TP                               varchar(2)                                       DEFAULT NULL COMMENT '客户类型',
    ACC_TP                               varchar(3)                                       DEFAULT NULL COMMENT '账户类型',
    TRNSC                                varchar(2)                                       DEFAULT NULL COMMENT '交易性质',
    TXN_ATR                              varchar(1)                                       DEFAULT NULL COMMENT '交易属性',
    CTIQ_TRTY                            varchar(4)                                       DEFAULT NULL COMMENT 'CTIQ交易类型',
    TRTY_DES                             varchar(50)                                      DEFAULT NULL COMMENT '交易类型描述',
    TXN_TIME                             time                                             DEFAULT NULL COMMENT '交易时间',
    TXN_TLR_REFNO                        varchar(7)                                       DEFAULT NULL COMMENT '交易柜员编号',
    TXN_ORG_REFNO                        varchar(5)                                       DEFAULT NULL COMMENT '交易机构编号',
    TXN_ORG_NAME                         varchar(120)                                     DEFAULT NULL COMMENT '交易机构名称',
    VALUE_DT                             date                                             DEFAULT NULL COMMENT '起息日期',
    BCHPO_SPCL_IDR                       varchar(1)                                       DEFAULT NULL COMMENT '批量处理特殊标记：0—联机交易，1—批量交易拆分时折出的前笔交易，2—批量交易拆分时折出的非首笔交易，3—批屋不涉及',
    ATOMT_CD                             varchar(10)                                      DEFAULT NULL COMMENT '原子交易码',
    ORGNT_CD                             varchar(10)                                      DEFAULT NULL COMMENT '原始交易码',
    PROMP                                varchar(2)                                       DEFAULT NULL COMMENT '提示码',
    PROMP_DES                            varchar(6)                                       DEFAULT NULL COMMENT '提示码描述',
    ORI_TXN_DT                           date                                             DEFAULT NULL COMMENT '原交易日期',
    ORGNT_SN                             varchar(16)                                      DEFAULT NULL COMMENT '原始交易流水号',
    TXN_CURR_TP                          varchar(3)                                       DEFAULT NULL COMMENT '交易货币类型',
    TXN_EXRT                             decimal(14, 6)                                   DEFAULT NULL COMMENT '交易汇率',
    TXN_AMT                              decimal(21, 3)                                   DEFAULT NULL COMMENT '交易金额',
    TXN_AF_BAL                           decimal(21, 3)                                   DEFAULT NULL COMMENT '交易后余额',
    TXN_AF_AVL_BAL                       decimal(21, 3)                                   DEFAULT NULL COMMENT '交易后可用余额',
    FRZ_AMT                              decimal(21, 3)                                   DEFAULT NULL COMMENT '冻结金额',
    OD_QOT                               decimal(21, 3)                                   DEFAULT NULL COMMENT '透支限额',
    AVL_OD_QOT                           decimal(21, 3)                                   DEFAULT NULL COMMENT '可用透支限额',
    PRIMARY KEY (TXN_ACCNO, TXN_DT, UNN_TRNO) CLUSTERED
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_bin COMMENT ='基础交易信息表_50c';
