DROP TABLE IF EXISTS `ads_txn_tif_detail`;
CREATE TABLE `ads_txn_tif_detail`
(
    TRAN_KEY            varchar(100) NOT NULL,
    SRC_SYS             varchar(4)     DEFAULT NULL,
    SRC_MOD             varchar(4)     DEFAULT NULL,
    CUS_NO              varchar(17)    DEFAULT NULL COMMENT '客户号',
    TRAN_CUSM_NO        varchar(18)    DEFAULT NULL,
    ACT_NO              varchar(18)    DEFAULT NULL,
    TRAN_DATE           varchar(8)     DEFAULT NULL,
    TRAN_TIME           datetime       DEFAULT NULL COMMENT '交易时间',
    POST_DATE           varchar(8)     DEFAULT NULL,
    ACTUAL_DATE         varchar(8)     DEFAULT NULL,
    ACTUAL_TIME         varchar(8)     DEFAULT NULL,
    CLASSIFY_ID         varchar(4)     DEFAULT NULL,
    TRAN_CAT            varchar(1)     DEFAULT NULL,
    IS_SHOW             varchar(1)     DEFAULT NULL,
    TRAN_TYPE           varchar(4)     DEFAULT NULL COMMENT '交易类型',
    TRAN_MSG            varchar(50)    DEFAULT NULL COMMENT '交易类型描述',
    TRAN_TELLER         varchar(7)     DEFAULT NULL COMMENT '交易柜员编号',
    INCT_TRN_CODE       varchar(6)     DEFAULT NULL,
    INCT_BATCH_NO       varchar(2)     DEFAULT NULL,
    NWK_TYP             varchar(4)     DEFAULT NULL,
    CR_DR_IND           varchar(1)     DEFAULT NULL,
    REVERSAL_CODE       varchar(1)     DEFAULT NULL,
    TRAN_ID             varchar(20)    DEFAULT NULL,
    UUID                varchar(32)    DEFAULT NULL COMMENT '外国系统UUID',
    PROSUP_TYPE         varchar(4)     DEFAULT NULL,
    ACT_TYPE            varchar(3)     DEFAULT NULL,
    CARD_NO             varchar(28)    DEFAULT NULL COMMENT '卡号',
    VIR_CARD            varchar(28)    DEFAULT NULL,
    TRAN_AMOUNT         decimal(21, 3) DEFAULT NULL COMMENT '交易金额',
    TRAN_CURE_EN        varchar(3)     DEFAULT NULL COMMENT '交易货币英文码',
    ACT_AVAIL_BALANCE   decimal(21, 3) DEFAULT NULL COMMENT '交易后余额',
    ACT_NAME            varchar(140)   DEFAULT NULL,
    REMIT_TYPE          varchar(1)     DEFAULT NULL COMMENT '钞汇性质',
    REMIT_TYPE_NAME     varchar(6)     DEFAULT NULL COMMENT '钞汇性质描述',
    OPP_CUSM_NO         varchar(17)    DEFAULT NULL,
    OPP_ACT_NO          varchar(35)    DEFAULT NULL,
    OPP_CARD_NO         varchar(19)    DEFAULT NULL,
    OPP_CARD_NO_TYPE    varchar(1)     DEFAULT NULL,
    OPP_ACT_NAME        varchar(140)   DEFAULT NULL,
    OPP_BR_NAME         varchar(80)    DEFAULT NULL,
    OPP_BR_NO           varchar(14)    DEFAULT NULL,
    OPP_TRAN_AMOUNT     decimal(21, 3) DEFAULT NULL,
    OPP_TRAN_CURE_EN    varchar(3)     DEFAULT NULL,
    OPP_REMIT_TYPE      varchar(1)     DEFAULT NULL,
    OPP_REMIT_TYPE_DESC varchar(6)     DEFAULT NULL,
    TRAN_AMOUNT_CNY     decimal(21, 3) DEFAULT NULL,
    MER_NO              varchar(15)    DEFAULT NULL,
    MER_NAME            varchar(30)    DEFAULT NULL,
    MCC                 varchar(4)     DEFAULT NULL,
    REMBAK              varchar(160)   DEFAULT NULL COMMENT '备注',
    USAGE_NAME          varchar(80)    DEFAULT NULL COMMENT '用途',
    TRAN_PS             varchar(225)   DEFAULT NULL COMMENT '附言',
    SUMMARY             varchar(140)   DEFAULT NULL COMMENT '摘要',
    CUS_SEQ             varchar(40)    DEFAULT NULL COMMENT '业务编号',
    TRAN_JRNL_NO        varchar(12)    DEFAULT NULL,
    STATUS              varchar(1)     DEFAULT NULL,
    ERR_MSG             varchar(100)   DEFAULT NULL,
    REMARK              varchar(160)   DEFAULT NULL,
    CUST_EDIT_STAT      varchar(1)     DEFAULT NULL,
    SUM_FLAG            varchar(1)     DEFAULT NULL,
    EDIT_FLAG           varchar(1)     DEFAULT NULL,
    SYS_CODE            varchar(2)     DEFAULT NULL,
    OL_TIME             datetime       DEFAULT NULL,
    BAT_TIME            datetime       DEFAULT NULL,
    FINAL_TIME          datetime       DEFAULT NULL,
    FINAL_SIGN          varchar(20)    DEFAULT NULL,
    HIT_TYPE            varchar(140)   DEFAULT NULL,
    HIT_REASON          varchar(140)   DEFAULT NULL,
    HIE_PATH            varchar(100)   DEFAULT NULL,
    BOOK_ID             varchar(100)   DEFAULT NULL,
    USE_OBJ             varchar(2)     DEFAULT NULL,
    DAY                 bigint(20)   not null,
    RES_FIELD           varchar(10)    DEFAULT NULL,
    ID                  bigint(20)   PRIMARY KEY AUTO_RANDOM
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_bin COMMENT ='基础交易信息表_detail';
