DROP TABLE IF EXISTS `ads_txn_tif_bas_100c`;
CREATE TABLE `ads_txn_tif_bas_100c`
(
    UNN_TRNO                             decimal(22, 0) NOT NULL COMMENT '统一交易号',
    TXN_DT                               date           NOT NULL COMMENT '交易日期',
    BOCGP_INST_NO                        varchar(3)                                       DEFAULT NULL COMMENT '中银集团银行号',
    TXN_ACCNO                            varchar(18)                                      DEFAULT NULL COMMENT '交易账号',
    RCRD_NO                              varchar(9)                                       DEFAULT NULL COMMENT '记录号',
    MSAC_ACCNO                           varchar(18)                                      DEFAULT NULL COMMENT '主账户账号',
    CDNO                                 varchar(19)                                      DEFAULT NULL COMMENT '卡号',
    TXN_ACCNO_SBACC_TYPE_NO              varchar(4)                                       DEFAULT NULL COMMENT '交易账号子账户类别号',
    TXN_CURR_ENG_CD                      varchar(3)                                       DEFAULT NULL COMMENT '交易货币英文码',
    DBTCR_IDR                            varchar(1)                                       DEFAULT NULL COMMENT '借贷标识',
    RVRS_IDR                             varchar(1)                                       DEFAULT NULL COMMENT '冲正标识',
    ORI_RCRD_NO                          varchar(9)                                       DEFAULT NULL COMMENT '原记录号',
    TXN_CHNL                             varchar(6)                                       DEFAULT NULL COMMENT '交易渠道',
    CTRYW_CLRG_ORG_CODE                  varchar(5)                                       DEFAULT NULL COMMENT '全国清算机构代码',
    ACC_PRONO                            varchar(5)                                       DEFAULT NULL COMMENT '账户省行机构编号',
    TXN_ACCNO_VLMNO                      varchar(3)                                       DEFAULT NULL COMMENT '交易账号册号',
    TXN_ACCNO_SN                         varchar(4)                                       DEFAULT NULL COMMENT '交易账号序号',
    TXN_SN                               varchar(18)                                      DEFAULT NULL COMMENT '交易流水号',
    UUID                                 varchar(32)                                      DEFAULT NULL COMMENT '外国系统UUID',
    PD_LGCLS                             varchar(4)                                       DEFAULT NULL COMMENT '产品大类',
    PD_AS                                varchar(4)                                       DEFAULT NULL COMMENT '产品子类',
    PD_DES                               varchar(100)                                     DEFAULT NULL COMMENT '产品描述',
    DOC_CTR_NO                           varchar(50)                                      DEFAULT NULL COMMENT '文书合同号',
    ACC_ATR                              varchar(1)                                       DEFAULT NULL COMMENT '账户属性',
    CUS_TP                               varchar(2)                                       DEFAULT NULL COMMENT '客户类型',
    ACC_TP                               varchar(3)                                       DEFAULT NULL COMMENT '账户类型',
    TRNSC                                varchar(2)                                       DEFAULT NULL COMMENT '交易性质',
    TXN_ATR                              varchar(1)                                       DEFAULT NULL COMMENT '交易属性',
    CTIQ_TRTY                            varchar(4)                                       DEFAULT NULL COMMENT 'CTIQ交易类型',
    TRTY_DES                             varchar(50)                                      DEFAULT NULL COMMENT '交易类型描述',
    TXN_TIME                             time                                             DEFAULT NULL COMMENT '交易时间',
    TXN_TLR_REFNO                        varchar(7)                                       DEFAULT NULL COMMENT '交易柜员编号',
    TXN_ORG_REFNO                        varchar(5)                                       DEFAULT NULL COMMENT '交易机构编号',
    TXN_ORG_NAME                         varchar(120)                                     DEFAULT NULL COMMENT '交易机构名称',
    VALUE_DT                             date                                             DEFAULT NULL COMMENT '起息日期',
    BCHPO_SPCL_IDR                       varchar(1)                                       DEFAULT NULL COMMENT '批量处理特殊标记：0—联机交易，1—批量交易拆分时折出的前笔交易，2—批量交易拆分时折出的非首笔交易，3—批屋不涉及',
    ATOMT_CD                             varchar(10)                                      DEFAULT NULL COMMENT '原子交易码',
    ORGNT_CD                             varchar(10)                                      DEFAULT NULL COMMENT '原始交易码',
    PROMP                                varchar(2)                                       DEFAULT NULL COMMENT '提示码',
    PROMP_DES                            varchar(6)                                       DEFAULT NULL COMMENT '提示码描述',
    ORI_TXN_DT                           date                                             DEFAULT NULL COMMENT '原交易日期',
    ORGNT_SN                             varchar(16)                                      DEFAULT NULL COMMENT '原始交易流水号',
    TXN_CURR_TP                          varchar(3)                                       DEFAULT NULL COMMENT '交易货币类型',
    TXN_EXRT                             decimal(14, 6)                                   DEFAULT NULL COMMENT '交易汇率',
    TXN_AMT                              decimal(21, 3)                                   DEFAULT NULL COMMENT '交易金额',
    TXN_AF_BAL                           decimal(21, 3)                                   DEFAULT NULL COMMENT '交易后余额',
    TXN_AF_AVL_BAL                       decimal(21, 3)                                   DEFAULT NULL COMMENT '交易后可用余额',
    FRZ_AMT                              decimal(21, 3)                                   DEFAULT NULL COMMENT '冻结金额',
    OD_QOT                               decimal(21, 3)                                   DEFAULT NULL COMMENT '透支限额',
    AVL_OD_QOT                           decimal(21, 3)                                   DEFAULT NULL COMMENT '可用透支限额',
    DSCT_SSONI_AMT                       decimal(21, 3)                                   DEFAULT NULL COMMENT '贴现息金额',
    RGLR_PNP_BAL                         decimal(21, 3)                                   DEFAULT NULL COMMENT '正常本金余额',
    ODUE_PNP_BAL                         decimal(21, 3)                                   DEFAULT NULL COMMENT '逾期本金余额',
    DRINT_BAL                            decimal(21, 3)                                   DEFAULT NULL COMMENT '欠息余额',
    ODUE_PNP_AMT                         decimal(21, 3)                                   DEFAULT NULL COMMENT '逾期本金金额',
    ODUE_INT_AMT                         decimal(21, 3)                                   DEFAULT NULL COMMENT '逾期利息金额',
    PNP_PNINT_AMT                        decimal(21, 3)                                   DEFAULT NULL COMMENT '本金罚息金额',
    INT_PNINT_AMT                        decimal(21, 3)                                   DEFAULT NULL COMMENT '利息罚息金额',
    PNINT_OF_PNINT_AMT                   decimal(21, 3)                                   DEFAULT NULL COMMENT '罚息的罚息金额',
    RMRK                                 varchar(1000)                                    DEFAULT NULL COMMENT '备注',
    PURP                                 varchar(200)                                     DEFAULT NULL COMMENT '用途',
    MEMO                                 varchar(225)                                     DEFAULT NULL COMMENT '附言',
    SUMM                                 varchar(140)                                     DEFAULT NULL COMMENT '摘要',
    CSHEX_CHAR                           varchar(1)                                       DEFAULT NULL COMMENT '钞汇性质',
    CSHEX_CHAR_DES                       varchar(6)                                       DEFAULT NULL COMMENT '钞汇性质描述',
    NOMPR_ACNM                           varchar(200)                                     DEFAULT NULL COMMENT '名义付款人账户名称',
    NOMPR_CRDNO                          varchar(19)                                      DEFAULT NULL COMMENT '名义付款人卡号',
    NOMPR_ACCNO                          varchar(35)                                      DEFAULT NULL COMMENT '名义付款人账号',
    NOMPR_SBACC_TYPE_NO                  varchar(4)                                       DEFAULT NULL COMMENT '名义付款人子账户类别号',
    NOMPR_VLMNO                          varchar(3)                                       DEFAULT NULL COMMENT '名义付款人册号',
    NOMPR_SN                             varchar(2)                                       DEFAULT NULL COMMENT '名义付款人序号',
    NOMPR_ACC_BLNG_ORGNM                 varchar(210)                                     DEFAULT NULL COMMENT '名义付款人账户所属机构名称',
    NOMPR_ACC_BLNG_ORGNO                 varchar(14)                                      DEFAULT NULL COMMENT '名义付款人账户所属机构号',
    NOMPR_ACC_CTRYW_CLRG_ORG_CODE        varchar(5)                                       DEFAULT NULL COMMENT '名义付款人账户全国清算机构代码',
    ACPAYR_ACNM                          varchar(200)                                     DEFAULT NULL COMMENT '真实付款人账户名称',
    ACPAYR_CRDNO                         varchar(19)                                      DEFAULT NULL COMMENT '真实付款人卡号',
    ACPAYR_ACCNO                         varchar(35)                                      DEFAULT NULL COMMENT '真实付款人账号',
    ACPR_SBACC_TYPE_NO                   varchar(4)                                       DEFAULT NULL COMMENT '赢实付款人子账户类别号',
    ACPR_VLMNO                           varchar(3)                                       DEFAULT NULL COMMENT '真实付款人册号',
    ACPR_SN                              varchar(2)                                       DEFAULT NULL COMMENT '真实付款人障号',
    ACPR_ACC_BLNG_ORGNM                  varchar(210)                                     DEFAULT NULL COMMENT '真实付款人账户所属机构名称',
    ACPR_ACC_BLNG_ORGNO                  varchar(14)                                      DEFAULT NULL COMMENT '真实付歌人账户所用机构号',
    ACPAYR_ACC_CTRYW_CLRG_ORG_CODE       varchar(5)                                       DEFAULT NULL COMMENT '真实付款人账户全国清算机构代码',
    NOMPE_ACNM                           varchar(200)                                     DEFAULT NULL COMMENT '名义收款人账户名称',
    NOMPE_CRDNO                          varchar(19)                                      DEFAULT NULL COMMENT '名义收款人卡号',
    NOMPE_ACCNO                          varchar(35)                                      DEFAULT NULL COMMENT '名义收款人账号',
    NOMPE_SBACC_TYPE_NO                  varchar(4)                                       DEFAULT NULL COMMENT '名义收款人子账户类别号',
    NOMPE_VLMNO                          varchar(3)                                       DEFAULT NULL COMMENT '名义收款人册号',
    NOMPE_SN                             varchar(2)                                       DEFAULT NULL COMMENT '名义收款人序号',
    NOMPE_ACC_BLNG_ORGNM                 varchar(210)                                     DEFAULT NULL COMMENT '名义收款人账户所属机构名称',
    NOMPE_ACC_BLNG_ORGNO                 varchar(14)                                      DEFAULT NULL COMMENT '名义收款人账户所属机构号',
    NOMPE_ACC_CTRYW_CLRG_ORG_CODE        varchar(5)                                       DEFAULT NULL COMMENT '名义收款人账户全国清算机构代码',
    ACPAYE_ACNM                          varchar(200)                                     DEFAULT NULL COMMENT '真实收款人账户名称',
    ACPAYE_CRDNO                         varchar(19)                                      DEFAULT NULL COMMENT '真实收款人卡号',
    ACPAYE_ACCNO                         varchar(35)                                      DEFAULT NULL COMMENT '真实收款人账号',
    ACPE_SBACC_TYPE_NO                   varchar(4)                                       DEFAULT NULL COMMENT '赢实收款人子账户类别号',
    ACPE_VLMNO                           varchar(3)                                       DEFAULT NULL COMMENT '真实收款人册号',
    ACPE_SN                              varchar(2)                                       DEFAULT NULL COMMENT '真实收款人障号',
    ACPE_ACC_BLNG_ORGNM                  varchar(210)                                     DEFAULT NULL COMMENT '真实收款人账户所属机构名称',
    ACPE_ACC_BLNG_ORGNO                  varchar(14)                                      DEFAULT NULL COMMENT '真实收歌人账户所用机构号',
    PRIMARY KEY (UNN_TRNO, TXN_DT) CLUSTERED
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_bin COMMENT ='基础交易信息表_100c';
