DROP TABLE IF EXISTS `TEST_HTAP2_INSERT_002`;
CREATE TABLE `TEST_HTAP2_INSERT_002`
(
    ZDY_ZJ  varchar(50)    DEFAULT NULL COMMENT '自定义_主键',
    DTE     varchar(20)    DEFAULT NULL COMMENT '录入数据日期',
    JYXLH   varchar(100)   DEFAULT NULL COMMENT '交易序列号',
    JRXKZH  varchar(30)    DEFAULT NULL COMMENT '金融许可证号',
    NBJGH   varchar(30)    DEFAULT NULL COMMENT '内部机构号',
    YWBLJGH varchar(30)    DEFAULT NULL COMMENT '业务办理机构号',
    YHJGMC  varchar(450)   DEFAULT NULL COMMENT '银行机构名称',
    MXKMBH  varchar(60)    DEFAULT NULL COMMENT '明细科目编号',
    MXKMMC  varchar(300)   DEFAULT NULL COMMENT '明细科目名称',
    KHTYBH  varchar(60)    DEFAULT NULL COMMENT '客户统一编号',
    ZHMC    varchar(450)   DEFAULT NULL COMMENT '账户名称',
    ZJLB    varchar(60)    DEFAULT NULL COMMENT '证件类别',
    ZJHM    varchar(70)    DEFAULT NULL COMMENT '证件号码',
    GRCKZH  varchar(60)    DEFAULT NULL COMMENT '个人存款账号',
    WBZH    varchar(60)    DEFAULT NULL COMMENT '外部账号',
    JYLX    varchar(60)    DEFAULT NULL COMMENT '交易类型',
    JYJDBZ  varchar(3)     DEFAULT NULL COMMENT '交易借贷标志',
    HXJYRQ  varchar(8)     DEFAULT NULL COMMENT '核心交易日期',
    HXJYSJ  varchar(10)    DEFAULT NULL COMMENT '核心交易时间',
    BZ      varchar(3)     DEFAULT NULL COMMENT '币种',
    JYJE    decimal(20, 2) DEFAULT NULL COMMENT '交易金额',
    ZHYE    decimal(20, 2) DEFAULT NULL COMMENT '账户余额',
    DFZH    varchar(60)    DEFAULT NULL COMMENT '对方账号',
    DFHM    varchar(450)   DEFAULT NULL COMMENT '对方户名',
    DFXH    varchar(30)    DEFAULT NULL COMMENT '对方行号',
    DFXM    varchar(450)   DEFAULT NULL COMMENT '对方行名',
    ZY      varchar(600)   DEFAULT NULL COMMENT '摘要',
    FY      varchar(600)   DEFAULT NULL COMMENT '附言',
    CBMBZ   varchar(9)     DEFAULT NULL COMMENT '冲补抹标志',
    XZBZ    varchar(3)     DEFAULT NULL COMMENT '现转标志',
    JYQD    varchar(60)    DEFAULT NULL COMMENT '交易渠道',
    IPDZ    varchar(40)    DEFAULT NULL COMMENT 'IP地址',
    MACDZ   varchar(60)    DEFAULT NULL COMMENT 'MAC地址',
    DBRXM   varchar(150)   DEFAULT NULL COMMENT '代办人姓名',
    DBRZJLB varchar(60)    DEFAULT NULL COMMENT '代办人证件类别',
    DBRZJHM varchar(70)    DEFAULT NULL COMMENT '代办人证件号码',
    JYGYH   varchar(30)    DEFAULT NULL COMMENT '交易柜员号',
    SQGYH   varchar(30)    DEFAULT NULL COMMENT '授权柜员号',
    BBZ     varchar(600)   DEFAULT NULL COMMENT '备注',
    CJRQ    varchar(8)     DEFAULT NULL COMMENT '采集日期',
    GSFZJG  varchar(200)   DEFAULT NULL COMMENT '归属分支机构'
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_bin COMMENT ='个人存款分户账明细记录' SHARD_ROW_ID_BITS=4 PRE_SPLIT_REGIONS=3;
