DROP TABLE IF EXISTS `TEST_HTAP2_SORDATA_002`;
CREATE TABLE `TEST_HTAP2_SORDATA_002`
(
    ZDY_ZJ      varchar(50)    DEFAULT NULL COMMENT '自定义_主键',
    DTE         varchar(8)     DEFAULT NULL COMMENT '数据日期',
    JRXKZH      varchar(450)   DEFAULT NULL COMMENT '金融许可证号',
    NBJGH       varchar(30)    DEFAULT NULL COMMENT '内部机构号',
    YHJGMC      varchar(450)   DEFAULT NULL COMMENT '银行机构名称',
    KHTYBH      varchar(60)    DEFAULT NULL COMMENT '客户统一编号',
    KHMC        varchar(450)   DEFAULT NULL COMMENT '客户名称',
    KHLX        varchar(60)    DEFAULT NULL COMMENT '客户类型',
    ZJLB        varchar(60)    DEFAULT NULL COMMENT '证件类别',
    ZJHM        varchar(70)    DEFAULT NULL COMMENT '证件号码',
    FRDB        varchar(150)   DEFAULT NULL COMMENT '法人代表',
    FRDBZJLB    varchar(60)    DEFAULT NULL COMMENT '法人代表证件类别',
    FRDBZJHM    varchar(70)    DEFAULT NULL COMMENT '法人代表证件号码',
    CWFZR       varchar(150)   DEFAULT NULL COMMENT '财务负责人',
    CWFZRZJLB   varchar(60)    DEFAULT NULL COMMENT '财务负责人证件类别',
    CWFZRZJHM   varchar(70)    DEFAULT NULL COMMENT '财务负责人证件号码',
    JBCKZH      varchar(60)    DEFAULT NULL COMMENT '基本存款账号',
    JBCKZHKHHH  varchar(30)    DEFAULT NULL COMMENT '基本存款账户开户行号',
    JBCKZHKHHMC varchar(450)   DEFAULT NULL COMMENT '基本存款账户开户行名称',
    ZCZB        decimal(20, 2) DEFAULT NULL COMMENT '注册资本',
    ZCZBBZ      varchar(3)     DEFAULT NULL COMMENT '注册资本币种',
    SSZB        decimal(20, 2) DEFAULT NULL COMMENT '实收资本',
    SSZBBZ      varchar(3)     DEFAULT NULL COMMENT '实收资本币种',
    ZCDZ        varchar(600)   DEFAULT NULL COMMENT '注册地址',
    LXDH        varchar(30)    DEFAULT NULL COMMENT '联系电话',
    JYFW        varchar(1500)  DEFAULT NULL COMMENT '经营范围',
    CLRQ        varchar(8)     DEFAULT NULL COMMENT '成立日期',
    SSHY        varchar(90)    DEFAULT NULL COMMENT '所属行业',
    QYFL        varchar(30)    DEFAULT NULL COMMENT '企业分类',
    XDKHBZ      varchar(3)     DEFAULT NULL COMMENT '信贷客户标志',
    SCJLXDGXNY  varchar(6)     DEFAULT NULL COMMENT '首次建立信贷关系年月',
    SSGSBZ      varchar(3)     DEFAULT NULL COMMENT '上市公司标志',
    XYPJ        varchar(30)    DEFAULT NULL COMMENT '信用评级',
    YGRS        int(11)        DEFAULT NULL COMMENT '员工人数',
    XZQHDM      varchar(6)     DEFAULT NULL COMMENT '行政区划代码',
    FXYJXH      varchar(500)   DEFAULT NULL COMMENT '风险预警信号',
    GZSJDM      varchar(500)   DEFAULT NULL COMMENT '关注事件代码',
    BBZ         varchar(600)   DEFAULT NULL COMMENT '备注',
    CJRQ        varchar(8)     DEFAULT NULL COMMENT '采集日期',
    GSFZJG      varchar(200)   DEFAULT NULL COMMENT '归属分支机构'
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_bin COMMENT ='对公客户信息表_报送历史表';