package com.heiheipp.common.mbg.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Time;
import java.util.Date;

public class AdsTxnTifBas50c extends BaseModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.UNN_TRNO
     *
     * @mbg.generated
     */
    private BigDecimal unnTrno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.TXN_DT
     *
     * @mbg.generated
     */
    private Date txnDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.BOCGP_INST_NO
     *
     * @mbg.generated
     */
    private String bocgpInstNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.TXN_ACCNO
     *
     * @mbg.generated
     */
    private String txnAccno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.RCRD_NO
     *
     * @mbg.generated
     */
    private String rcrdNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.MSAC_ACCNO
     *
     * @mbg.generated
     */
    private String msacAccno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.CDNO
     *
     * @mbg.generated
     */
    private String cdno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.TXN_ACCNO_SBACC_TYPE_NO
     *
     * @mbg.generated
     */
    private String txnAccnoSbaccTypeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.TXN_CURR_ENG_CD
     *
     * @mbg.generated
     */
    private String txnCurrEngCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.DBTCR_IDR
     *
     * @mbg.generated
     */
    private String dbtcrIdr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.RVRS_IDR
     *
     * @mbg.generated
     */
    private String rvrsIdr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.ORI_RCRD_NO
     *
     * @mbg.generated
     */
    private String oriRcrdNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.TXN_CHNL
     *
     * @mbg.generated
     */
    private String txnChnl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.CTRYW_CLRG_ORG_CODE
     *
     * @mbg.generated
     */
    private String ctrywClrgOrgCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.ACC_PRONO
     *
     * @mbg.generated
     */
    private String accProno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.TXN_ACCNO_VLMNO
     *
     * @mbg.generated
     */
    private String txnAccnoVlmno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.TXN_ACCNO_SN
     *
     * @mbg.generated
     */
    private String txnAccnoSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.TXN_SN
     *
     * @mbg.generated
     */
    private String txnSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.UUID
     *
     * @mbg.generated
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.PD_LGCLS
     *
     * @mbg.generated
     */
    private String pdLgcls;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.PD_AS
     *
     * @mbg.generated
     */
    private String pdAs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.PD_DES
     *
     * @mbg.generated
     */
    private String pdDes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.DOC_CTR_NO
     *
     * @mbg.generated
     */
    private String docCtrNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.ACC_ATR
     *
     * @mbg.generated
     */
    private String accAtr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.CUS_TP
     *
     * @mbg.generated
     */
    private String cusTp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.ACC_TP
     *
     * @mbg.generated
     */
    private String accTp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.TRNSC
     *
     * @mbg.generated
     */
    private String trnsc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.TXN_ATR
     *
     * @mbg.generated
     */
    private String txnAtr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.CTIQ_TRTY
     *
     * @mbg.generated
     */
    private String ctiqTrty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.TRTY_DES
     *
     * @mbg.generated
     */
    private String trtyDes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.TXN_TIME
     *
     * @mbg.generated
     */
    private Time txnTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.TXN_TLR_REFNO
     *
     * @mbg.generated
     */
    private String txnTlrRefno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.TXN_ORG_REFNO
     *
     * @mbg.generated
     */
    private String txnOrgRefno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.TXN_ORG_NAME
     *
     * @mbg.generated
     */
    private String txnOrgName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.VALUE_DT
     *
     * @mbg.generated
     */
    private Date valueDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.BCHPO_SPCL_IDR
     *
     * @mbg.generated
     */
    private String bchpoSpclIdr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.ATOMT_CD
     *
     * @mbg.generated
     */
    private String atomtCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.ORGNT_CD
     *
     * @mbg.generated
     */
    private String orgntCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.PROMP
     *
     * @mbg.generated
     */
    private String promp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.PROMP_DES
     *
     * @mbg.generated
     */
    private String prompDes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.ORI_TXN_DT
     *
     * @mbg.generated
     */
    private Date oriTxnDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.ORGNT_SN
     *
     * @mbg.generated
     */
    private String orgntSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.TXN_CURR_TP
     *
     * @mbg.generated
     */
    private String txnCurrTp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.TXN_EXRT
     *
     * @mbg.generated
     */
    private BigDecimal txnExrt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.TXN_AMT
     *
     * @mbg.generated
     */
    private BigDecimal txnAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.TXN_AF_BAL
     *
     * @mbg.generated
     */
    private BigDecimal txnAfBal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.TXN_AF_AVL_BAL
     *
     * @mbg.generated
     */
    private BigDecimal txnAfAvlBal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.FRZ_AMT
     *
     * @mbg.generated
     */
    private BigDecimal frzAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.OD_QOT
     *
     * @mbg.generated
     */
    private BigDecimal odQot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ads_txn_tif_bas_50c.AVL_OD_QOT
     *
     * @mbg.generated
     */
    private BigDecimal avlOdQot;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ads_txn_tif_bas_50c
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.UNN_TRNO
     *
     * @return the value of ads_txn_tif_bas_50c.UNN_TRNO
     *
     * @mbg.generated
     */
    public BigDecimal getUnnTrno() {
        return unnTrno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.UNN_TRNO
     *
     * @param unnTrno the value for ads_txn_tif_bas_50c.UNN_TRNO
     *
     * @mbg.generated
     */
    public void setUnnTrno(BigDecimal unnTrno) {
        this.unnTrno = unnTrno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.TXN_DT
     *
     * @return the value of ads_txn_tif_bas_50c.TXN_DT
     *
     * @mbg.generated
     */
    public Date getTxnDt() {
        return txnDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.TXN_DT
     *
     * @param txnDt the value for ads_txn_tif_bas_50c.TXN_DT
     *
     * @mbg.generated
     */
    public void setTxnDt(Date txnDt) {
        this.txnDt = txnDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.BOCGP_INST_NO
     *
     * @return the value of ads_txn_tif_bas_50c.BOCGP_INST_NO
     *
     * @mbg.generated
     */
    public String getBocgpInstNo() {
        return bocgpInstNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.BOCGP_INST_NO
     *
     * @param bocgpInstNo the value for ads_txn_tif_bas_50c.BOCGP_INST_NO
     *
     * @mbg.generated
     */
    public void setBocgpInstNo(String bocgpInstNo) {
        this.bocgpInstNo = bocgpInstNo == null ? null : bocgpInstNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.TXN_ACCNO
     *
     * @return the value of ads_txn_tif_bas_50c.TXN_ACCNO
     *
     * @mbg.generated
     */
    public String getTxnAccno() {
        return txnAccno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.TXN_ACCNO
     *
     * @param txnAccno the value for ads_txn_tif_bas_50c.TXN_ACCNO
     *
     * @mbg.generated
     */
    public void setTxnAccno(String txnAccno) {
        this.txnAccno = txnAccno == null ? null : txnAccno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.RCRD_NO
     *
     * @return the value of ads_txn_tif_bas_50c.RCRD_NO
     *
     * @mbg.generated
     */
    public String getRcrdNo() {
        return rcrdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.RCRD_NO
     *
     * @param rcrdNo the value for ads_txn_tif_bas_50c.RCRD_NO
     *
     * @mbg.generated
     */
    public void setRcrdNo(String rcrdNo) {
        this.rcrdNo = rcrdNo == null ? null : rcrdNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.MSAC_ACCNO
     *
     * @return the value of ads_txn_tif_bas_50c.MSAC_ACCNO
     *
     * @mbg.generated
     */
    public String getMsacAccno() {
        return msacAccno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.MSAC_ACCNO
     *
     * @param msacAccno the value for ads_txn_tif_bas_50c.MSAC_ACCNO
     *
     * @mbg.generated
     */
    public void setMsacAccno(String msacAccno) {
        this.msacAccno = msacAccno == null ? null : msacAccno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.CDNO
     *
     * @return the value of ads_txn_tif_bas_50c.CDNO
     *
     * @mbg.generated
     */
    public String getCdno() {
        return cdno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.CDNO
     *
     * @param cdno the value for ads_txn_tif_bas_50c.CDNO
     *
     * @mbg.generated
     */
    public void setCdno(String cdno) {
        this.cdno = cdno == null ? null : cdno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.TXN_ACCNO_SBACC_TYPE_NO
     *
     * @return the value of ads_txn_tif_bas_50c.TXN_ACCNO_SBACC_TYPE_NO
     *
     * @mbg.generated
     */
    public String getTxnAccnoSbaccTypeNo() {
        return txnAccnoSbaccTypeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.TXN_ACCNO_SBACC_TYPE_NO
     *
     * @param txnAccnoSbaccTypeNo the value for ads_txn_tif_bas_50c.TXN_ACCNO_SBACC_TYPE_NO
     *
     * @mbg.generated
     */
    public void setTxnAccnoSbaccTypeNo(String txnAccnoSbaccTypeNo) {
        this.txnAccnoSbaccTypeNo = txnAccnoSbaccTypeNo == null ? null : txnAccnoSbaccTypeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.TXN_CURR_ENG_CD
     *
     * @return the value of ads_txn_tif_bas_50c.TXN_CURR_ENG_CD
     *
     * @mbg.generated
     */
    public String getTxnCurrEngCd() {
        return txnCurrEngCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.TXN_CURR_ENG_CD
     *
     * @param txnCurrEngCd the value for ads_txn_tif_bas_50c.TXN_CURR_ENG_CD
     *
     * @mbg.generated
     */
    public void setTxnCurrEngCd(String txnCurrEngCd) {
        this.txnCurrEngCd = txnCurrEngCd == null ? null : txnCurrEngCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.DBTCR_IDR
     *
     * @return the value of ads_txn_tif_bas_50c.DBTCR_IDR
     *
     * @mbg.generated
     */
    public String getDbtcrIdr() {
        return dbtcrIdr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.DBTCR_IDR
     *
     * @param dbtcrIdr the value for ads_txn_tif_bas_50c.DBTCR_IDR
     *
     * @mbg.generated
     */
    public void setDbtcrIdr(String dbtcrIdr) {
        this.dbtcrIdr = dbtcrIdr == null ? null : dbtcrIdr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.RVRS_IDR
     *
     * @return the value of ads_txn_tif_bas_50c.RVRS_IDR
     *
     * @mbg.generated
     */
    public String getRvrsIdr() {
        return rvrsIdr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.RVRS_IDR
     *
     * @param rvrsIdr the value for ads_txn_tif_bas_50c.RVRS_IDR
     *
     * @mbg.generated
     */
    public void setRvrsIdr(String rvrsIdr) {
        this.rvrsIdr = rvrsIdr == null ? null : rvrsIdr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.ORI_RCRD_NO
     *
     * @return the value of ads_txn_tif_bas_50c.ORI_RCRD_NO
     *
     * @mbg.generated
     */
    public String getOriRcrdNo() {
        return oriRcrdNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.ORI_RCRD_NO
     *
     * @param oriRcrdNo the value for ads_txn_tif_bas_50c.ORI_RCRD_NO
     *
     * @mbg.generated
     */
    public void setOriRcrdNo(String oriRcrdNo) {
        this.oriRcrdNo = oriRcrdNo == null ? null : oriRcrdNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.TXN_CHNL
     *
     * @return the value of ads_txn_tif_bas_50c.TXN_CHNL
     *
     * @mbg.generated
     */
    public String getTxnChnl() {
        return txnChnl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.TXN_CHNL
     *
     * @param txnChnl the value for ads_txn_tif_bas_50c.TXN_CHNL
     *
     * @mbg.generated
     */
    public void setTxnChnl(String txnChnl) {
        this.txnChnl = txnChnl == null ? null : txnChnl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.CTRYW_CLRG_ORG_CODE
     *
     * @return the value of ads_txn_tif_bas_50c.CTRYW_CLRG_ORG_CODE
     *
     * @mbg.generated
     */
    public String getCtrywClrgOrgCode() {
        return ctrywClrgOrgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.CTRYW_CLRG_ORG_CODE
     *
     * @param ctrywClrgOrgCode the value for ads_txn_tif_bas_50c.CTRYW_CLRG_ORG_CODE
     *
     * @mbg.generated
     */
    public void setCtrywClrgOrgCode(String ctrywClrgOrgCode) {
        this.ctrywClrgOrgCode = ctrywClrgOrgCode == null ? null : ctrywClrgOrgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.ACC_PRONO
     *
     * @return the value of ads_txn_tif_bas_50c.ACC_PRONO
     *
     * @mbg.generated
     */
    public String getAccProno() {
        return accProno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.ACC_PRONO
     *
     * @param accProno the value for ads_txn_tif_bas_50c.ACC_PRONO
     *
     * @mbg.generated
     */
    public void setAccProno(String accProno) {
        this.accProno = accProno == null ? null : accProno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.TXN_ACCNO_VLMNO
     *
     * @return the value of ads_txn_tif_bas_50c.TXN_ACCNO_VLMNO
     *
     * @mbg.generated
     */
    public String getTxnAccnoVlmno() {
        return txnAccnoVlmno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.TXN_ACCNO_VLMNO
     *
     * @param txnAccnoVlmno the value for ads_txn_tif_bas_50c.TXN_ACCNO_VLMNO
     *
     * @mbg.generated
     */
    public void setTxnAccnoVlmno(String txnAccnoVlmno) {
        this.txnAccnoVlmno = txnAccnoVlmno == null ? null : txnAccnoVlmno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.TXN_ACCNO_SN
     *
     * @return the value of ads_txn_tif_bas_50c.TXN_ACCNO_SN
     *
     * @mbg.generated
     */
    public String getTxnAccnoSn() {
        return txnAccnoSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.TXN_ACCNO_SN
     *
     * @param txnAccnoSn the value for ads_txn_tif_bas_50c.TXN_ACCNO_SN
     *
     * @mbg.generated
     */
    public void setTxnAccnoSn(String txnAccnoSn) {
        this.txnAccnoSn = txnAccnoSn == null ? null : txnAccnoSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.TXN_SN
     *
     * @return the value of ads_txn_tif_bas_50c.TXN_SN
     *
     * @mbg.generated
     */
    public String getTxnSn() {
        return txnSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.TXN_SN
     *
     * @param txnSn the value for ads_txn_tif_bas_50c.TXN_SN
     *
     * @mbg.generated
     */
    public void setTxnSn(String txnSn) {
        this.txnSn = txnSn == null ? null : txnSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.UUID
     *
     * @return the value of ads_txn_tif_bas_50c.UUID
     *
     * @mbg.generated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.UUID
     *
     * @param uuid the value for ads_txn_tif_bas_50c.UUID
     *
     * @mbg.generated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.PD_LGCLS
     *
     * @return the value of ads_txn_tif_bas_50c.PD_LGCLS
     *
     * @mbg.generated
     */
    public String getPdLgcls() {
        return pdLgcls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.PD_LGCLS
     *
     * @param pdLgcls the value for ads_txn_tif_bas_50c.PD_LGCLS
     *
     * @mbg.generated
     */
    public void setPdLgcls(String pdLgcls) {
        this.pdLgcls = pdLgcls == null ? null : pdLgcls.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.PD_AS
     *
     * @return the value of ads_txn_tif_bas_50c.PD_AS
     *
     * @mbg.generated
     */
    public String getPdAs() {
        return pdAs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.PD_AS
     *
     * @param pdAs the value for ads_txn_tif_bas_50c.PD_AS
     *
     * @mbg.generated
     */
    public void setPdAs(String pdAs) {
        this.pdAs = pdAs == null ? null : pdAs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.PD_DES
     *
     * @return the value of ads_txn_tif_bas_50c.PD_DES
     *
     * @mbg.generated
     */
    public String getPdDes() {
        return pdDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.PD_DES
     *
     * @param pdDes the value for ads_txn_tif_bas_50c.PD_DES
     *
     * @mbg.generated
     */
    public void setPdDes(String pdDes) {
        this.pdDes = pdDes == null ? null : pdDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.DOC_CTR_NO
     *
     * @return the value of ads_txn_tif_bas_50c.DOC_CTR_NO
     *
     * @mbg.generated
     */
    public String getDocCtrNo() {
        return docCtrNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.DOC_CTR_NO
     *
     * @param docCtrNo the value for ads_txn_tif_bas_50c.DOC_CTR_NO
     *
     * @mbg.generated
     */
    public void setDocCtrNo(String docCtrNo) {
        this.docCtrNo = docCtrNo == null ? null : docCtrNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.ACC_ATR
     *
     * @return the value of ads_txn_tif_bas_50c.ACC_ATR
     *
     * @mbg.generated
     */
    public String getAccAtr() {
        return accAtr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.ACC_ATR
     *
     * @param accAtr the value for ads_txn_tif_bas_50c.ACC_ATR
     *
     * @mbg.generated
     */
    public void setAccAtr(String accAtr) {
        this.accAtr = accAtr == null ? null : accAtr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.CUS_TP
     *
     * @return the value of ads_txn_tif_bas_50c.CUS_TP
     *
     * @mbg.generated
     */
    public String getCusTp() {
        return cusTp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.CUS_TP
     *
     * @param cusTp the value for ads_txn_tif_bas_50c.CUS_TP
     *
     * @mbg.generated
     */
    public void setCusTp(String cusTp) {
        this.cusTp = cusTp == null ? null : cusTp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.ACC_TP
     *
     * @return the value of ads_txn_tif_bas_50c.ACC_TP
     *
     * @mbg.generated
     */
    public String getAccTp() {
        return accTp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.ACC_TP
     *
     * @param accTp the value for ads_txn_tif_bas_50c.ACC_TP
     *
     * @mbg.generated
     */
    public void setAccTp(String accTp) {
        this.accTp = accTp == null ? null : accTp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.TRNSC
     *
     * @return the value of ads_txn_tif_bas_50c.TRNSC
     *
     * @mbg.generated
     */
    public String getTrnsc() {
        return trnsc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.TRNSC
     *
     * @param trnsc the value for ads_txn_tif_bas_50c.TRNSC
     *
     * @mbg.generated
     */
    public void setTrnsc(String trnsc) {
        this.trnsc = trnsc == null ? null : trnsc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.TXN_ATR
     *
     * @return the value of ads_txn_tif_bas_50c.TXN_ATR
     *
     * @mbg.generated
     */
    public String getTxnAtr() {
        return txnAtr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.TXN_ATR
     *
     * @param txnAtr the value for ads_txn_tif_bas_50c.TXN_ATR
     *
     * @mbg.generated
     */
    public void setTxnAtr(String txnAtr) {
        this.txnAtr = txnAtr == null ? null : txnAtr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.CTIQ_TRTY
     *
     * @return the value of ads_txn_tif_bas_50c.CTIQ_TRTY
     *
     * @mbg.generated
     */
    public String getCtiqTrty() {
        return ctiqTrty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.CTIQ_TRTY
     *
     * @param ctiqTrty the value for ads_txn_tif_bas_50c.CTIQ_TRTY
     *
     * @mbg.generated
     */
    public void setCtiqTrty(String ctiqTrty) {
        this.ctiqTrty = ctiqTrty == null ? null : ctiqTrty.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.TRTY_DES
     *
     * @return the value of ads_txn_tif_bas_50c.TRTY_DES
     *
     * @mbg.generated
     */
    public String getTrtyDes() {
        return trtyDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.TRTY_DES
     *
     * @param trtyDes the value for ads_txn_tif_bas_50c.TRTY_DES
     *
     * @mbg.generated
     */
    public void setTrtyDes(String trtyDes) {
        this.trtyDes = trtyDes == null ? null : trtyDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.TXN_TIME
     *
     * @return the value of ads_txn_tif_bas_50c.TXN_TIME
     *
     * @mbg.generated
     */
    public Date getTxnTime() {
        return txnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.TXN_TIME
     *
     * @param txnTime the value for ads_txn_tif_bas_50c.TXN_TIME
     *
     * @mbg.generated
     */
    public void setTxnTime(Time txnTime) {
        this.txnTime = txnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.TXN_TLR_REFNO
     *
     * @return the value of ads_txn_tif_bas_50c.TXN_TLR_REFNO
     *
     * @mbg.generated
     */
    public String getTxnTlrRefno() {
        return txnTlrRefno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.TXN_TLR_REFNO
     *
     * @param txnTlrRefno the value for ads_txn_tif_bas_50c.TXN_TLR_REFNO
     *
     * @mbg.generated
     */
    public void setTxnTlrRefno(String txnTlrRefno) {
        this.txnTlrRefno = txnTlrRefno == null ? null : txnTlrRefno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.TXN_ORG_REFNO
     *
     * @return the value of ads_txn_tif_bas_50c.TXN_ORG_REFNO
     *
     * @mbg.generated
     */
    public String getTxnOrgRefno() {
        return txnOrgRefno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.TXN_ORG_REFNO
     *
     * @param txnOrgRefno the value for ads_txn_tif_bas_50c.TXN_ORG_REFNO
     *
     * @mbg.generated
     */
    public void setTxnOrgRefno(String txnOrgRefno) {
        this.txnOrgRefno = txnOrgRefno == null ? null : txnOrgRefno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.TXN_ORG_NAME
     *
     * @return the value of ads_txn_tif_bas_50c.TXN_ORG_NAME
     *
     * @mbg.generated
     */
    public String getTxnOrgName() {
        return txnOrgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.TXN_ORG_NAME
     *
     * @param txnOrgName the value for ads_txn_tif_bas_50c.TXN_ORG_NAME
     *
     * @mbg.generated
     */
    public void setTxnOrgName(String txnOrgName) {
        this.txnOrgName = txnOrgName == null ? null : txnOrgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.VALUE_DT
     *
     * @return the value of ads_txn_tif_bas_50c.VALUE_DT
     *
     * @mbg.generated
     */
    public Date getValueDt() {
        return valueDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.VALUE_DT
     *
     * @param valueDt the value for ads_txn_tif_bas_50c.VALUE_DT
     *
     * @mbg.generated
     */
    public void setValueDt(Date valueDt) {
        this.valueDt = valueDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.BCHPO_SPCL_IDR
     *
     * @return the value of ads_txn_tif_bas_50c.BCHPO_SPCL_IDR
     *
     * @mbg.generated
     */
    public String getBchpoSpclIdr() {
        return bchpoSpclIdr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.BCHPO_SPCL_IDR
     *
     * @param bchpoSpclIdr the value for ads_txn_tif_bas_50c.BCHPO_SPCL_IDR
     *
     * @mbg.generated
     */
    public void setBchpoSpclIdr(String bchpoSpclIdr) {
        this.bchpoSpclIdr = bchpoSpclIdr == null ? null : bchpoSpclIdr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.ATOMT_CD
     *
     * @return the value of ads_txn_tif_bas_50c.ATOMT_CD
     *
     * @mbg.generated
     */
    public String getAtomtCd() {
        return atomtCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.ATOMT_CD
     *
     * @param atomtCd the value for ads_txn_tif_bas_50c.ATOMT_CD
     *
     * @mbg.generated
     */
    public void setAtomtCd(String atomtCd) {
        this.atomtCd = atomtCd == null ? null : atomtCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.ORGNT_CD
     *
     * @return the value of ads_txn_tif_bas_50c.ORGNT_CD
     *
     * @mbg.generated
     */
    public String getOrgntCd() {
        return orgntCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.ORGNT_CD
     *
     * @param orgntCd the value for ads_txn_tif_bas_50c.ORGNT_CD
     *
     * @mbg.generated
     */
    public void setOrgntCd(String orgntCd) {
        this.orgntCd = orgntCd == null ? null : orgntCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.PROMP
     *
     * @return the value of ads_txn_tif_bas_50c.PROMP
     *
     * @mbg.generated
     */
    public String getPromp() {
        return promp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.PROMP
     *
     * @param promp the value for ads_txn_tif_bas_50c.PROMP
     *
     * @mbg.generated
     */
    public void setPromp(String promp) {
        this.promp = promp == null ? null : promp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.PROMP_DES
     *
     * @return the value of ads_txn_tif_bas_50c.PROMP_DES
     *
     * @mbg.generated
     */
    public String getPrompDes() {
        return prompDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.PROMP_DES
     *
     * @param prompDes the value for ads_txn_tif_bas_50c.PROMP_DES
     *
     * @mbg.generated
     */
    public void setPrompDes(String prompDes) {
        this.prompDes = prompDes == null ? null : prompDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.ORI_TXN_DT
     *
     * @return the value of ads_txn_tif_bas_50c.ORI_TXN_DT
     *
     * @mbg.generated
     */
    public Date getOriTxnDt() {
        return oriTxnDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.ORI_TXN_DT
     *
     * @param oriTxnDt the value for ads_txn_tif_bas_50c.ORI_TXN_DT
     *
     * @mbg.generated
     */
    public void setOriTxnDt(Date oriTxnDt) {
        this.oriTxnDt = oriTxnDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.ORGNT_SN
     *
     * @return the value of ads_txn_tif_bas_50c.ORGNT_SN
     *
     * @mbg.generated
     */
    public String getOrgntSn() {
        return orgntSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.ORGNT_SN
     *
     * @param orgntSn the value for ads_txn_tif_bas_50c.ORGNT_SN
     *
     * @mbg.generated
     */
    public void setOrgntSn(String orgntSn) {
        this.orgntSn = orgntSn == null ? null : orgntSn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.TXN_CURR_TP
     *
     * @return the value of ads_txn_tif_bas_50c.TXN_CURR_TP
     *
     * @mbg.generated
     */
    public String getTxnCurrTp() {
        return txnCurrTp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.TXN_CURR_TP
     *
     * @param txnCurrTp the value for ads_txn_tif_bas_50c.TXN_CURR_TP
     *
     * @mbg.generated
     */
    public void setTxnCurrTp(String txnCurrTp) {
        this.txnCurrTp = txnCurrTp == null ? null : txnCurrTp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.TXN_EXRT
     *
     * @return the value of ads_txn_tif_bas_50c.TXN_EXRT
     *
     * @mbg.generated
     */
    public BigDecimal getTxnExrt() {
        return txnExrt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.TXN_EXRT
     *
     * @param txnExrt the value for ads_txn_tif_bas_50c.TXN_EXRT
     *
     * @mbg.generated
     */
    public void setTxnExrt(BigDecimal txnExrt) {
        this.txnExrt = txnExrt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.TXN_AMT
     *
     * @return the value of ads_txn_tif_bas_50c.TXN_AMT
     *
     * @mbg.generated
     */
    public BigDecimal getTxnAmt() {
        return txnAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.TXN_AMT
     *
     * @param txnAmt the value for ads_txn_tif_bas_50c.TXN_AMT
     *
     * @mbg.generated
     */
    public void setTxnAmt(BigDecimal txnAmt) {
        this.txnAmt = txnAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.TXN_AF_BAL
     *
     * @return the value of ads_txn_tif_bas_50c.TXN_AF_BAL
     *
     * @mbg.generated
     */
    public BigDecimal getTxnAfBal() {
        return txnAfBal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.TXN_AF_BAL
     *
     * @param txnAfBal the value for ads_txn_tif_bas_50c.TXN_AF_BAL
     *
     * @mbg.generated
     */
    public void setTxnAfBal(BigDecimal txnAfBal) {
        this.txnAfBal = txnAfBal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.TXN_AF_AVL_BAL
     *
     * @return the value of ads_txn_tif_bas_50c.TXN_AF_AVL_BAL
     *
     * @mbg.generated
     */
    public BigDecimal getTxnAfAvlBal() {
        return txnAfAvlBal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.TXN_AF_AVL_BAL
     *
     * @param txnAfAvlBal the value for ads_txn_tif_bas_50c.TXN_AF_AVL_BAL
     *
     * @mbg.generated
     */
    public void setTxnAfAvlBal(BigDecimal txnAfAvlBal) {
        this.txnAfAvlBal = txnAfAvlBal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.FRZ_AMT
     *
     * @return the value of ads_txn_tif_bas_50c.FRZ_AMT
     *
     * @mbg.generated
     */
    public BigDecimal getFrzAmt() {
        return frzAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.FRZ_AMT
     *
     * @param frzAmt the value for ads_txn_tif_bas_50c.FRZ_AMT
     *
     * @mbg.generated
     */
    public void setFrzAmt(BigDecimal frzAmt) {
        this.frzAmt = frzAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.OD_QOT
     *
     * @return the value of ads_txn_tif_bas_50c.OD_QOT
     *
     * @mbg.generated
     */
    public BigDecimal getOdQot() {
        return odQot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.OD_QOT
     *
     * @param odQot the value for ads_txn_tif_bas_50c.OD_QOT
     *
     * @mbg.generated
     */
    public void setOdQot(BigDecimal odQot) {
        this.odQot = odQot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ads_txn_tif_bas_50c.AVL_OD_QOT
     *
     * @return the value of ads_txn_tif_bas_50c.AVL_OD_QOT
     *
     * @mbg.generated
     */
    public BigDecimal getAvlOdQot() {
        return avlOdQot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ads_txn_tif_bas_50c.AVL_OD_QOT
     *
     * @param avlOdQot the value for ads_txn_tif_bas_50c.AVL_OD_QOT
     *
     * @mbg.generated
     */
    public void setAvlOdQot(BigDecimal avlOdQot) {
        this.avlOdQot = avlOdQot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads_txn_tif_bas_50c
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", unnTrno=").append(unnTrno);
        sb.append(", txnDt=").append(txnDt);
        sb.append(", bocgpInstNo=").append(bocgpInstNo);
        sb.append(", txnAccno=").append(txnAccno);
        sb.append(", rcrdNo=").append(rcrdNo);
        sb.append(", msacAccno=").append(msacAccno);
        sb.append(", cdno=").append(cdno);
        sb.append(", txnAccnoSbaccTypeNo=").append(txnAccnoSbaccTypeNo);
        sb.append(", txnCurrEngCd=").append(txnCurrEngCd);
        sb.append(", dbtcrIdr=").append(dbtcrIdr);
        sb.append(", rvrsIdr=").append(rvrsIdr);
        sb.append(", oriRcrdNo=").append(oriRcrdNo);
        sb.append(", txnChnl=").append(txnChnl);
        sb.append(", ctrywClrgOrgCode=").append(ctrywClrgOrgCode);
        sb.append(", accProno=").append(accProno);
        sb.append(", txnAccnoVlmno=").append(txnAccnoVlmno);
        sb.append(", txnAccnoSn=").append(txnAccnoSn);
        sb.append(", txnSn=").append(txnSn);
        sb.append(", uuid=").append(uuid);
        sb.append(", pdLgcls=").append(pdLgcls);
        sb.append(", pdAs=").append(pdAs);
        sb.append(", pdDes=").append(pdDes);
        sb.append(", docCtrNo=").append(docCtrNo);
        sb.append(", accAtr=").append(accAtr);
        sb.append(", cusTp=").append(cusTp);
        sb.append(", accTp=").append(accTp);
        sb.append(", trnsc=").append(trnsc);
        sb.append(", txnAtr=").append(txnAtr);
        sb.append(", ctiqTrty=").append(ctiqTrty);
        sb.append(", trtyDes=").append(trtyDes);
        sb.append(", txnTime=").append(txnTime);
        sb.append(", txnTlrRefno=").append(txnTlrRefno);
        sb.append(", txnOrgRefno=").append(txnOrgRefno);
        sb.append(", txnOrgName=").append(txnOrgName);
        sb.append(", valueDt=").append(valueDt);
        sb.append(", bchpoSpclIdr=").append(bchpoSpclIdr);
        sb.append(", atomtCd=").append(atomtCd);
        sb.append(", orgntCd=").append(orgntCd);
        sb.append(", promp=").append(promp);
        sb.append(", prompDes=").append(prompDes);
        sb.append(", oriTxnDt=").append(oriTxnDt);
        sb.append(", orgntSn=").append(orgntSn);
        sb.append(", txnCurrTp=").append(txnCurrTp);
        sb.append(", txnExrt=").append(txnExrt);
        sb.append(", txnAmt=").append(txnAmt);
        sb.append(", txnAfBal=").append(txnAfBal);
        sb.append(", txnAfAvlBal=").append(txnAfAvlBal);
        sb.append(", frzAmt=").append(frzAmt);
        sb.append(", odQot=").append(odQot);
        sb.append(", avlOdQot=").append(avlOdQot);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}