package com.heiheipp.common.mbg.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Date;

public class CdmTransDetail implements Serializable, Cloneable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdm_trans_detail.tran_id
     *
     * @mbg.generated
     */
    private String tranId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdm_trans_detail.cust_id
     *
     * @mbg.generated
     */
    private String custId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdm_trans_detail.card_no
     *
     * @mbg.generated
     */
    private String cardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdm_trans_detail.date_time
     *
     * @mbg.generated
     */
    private Timestamp dateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdm_trans_detail.tran_type
     *
     * @mbg.generated
     */
    private String tranType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdm_trans_detail.tran_cat
     *
     * @mbg.generated
     */
    private String tranCat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdm_trans_detail.tran_msg
     *
     * @mbg.generated
     */
    private String tranMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdm_trans_detail.tran_amount
     *
     * @mbg.generated
     */
    private BigDecimal tranAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdm_trans_detail.tran_cureen
     *
     * @mbg.generated
     */
    private String tranCureen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdm_trans_detail.acct_avaibala
     *
     * @mbg.generated
     */
    private BigDecimal acctAvaibala;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdm_trans_detail.act_name
     *
     * @mbg.generated
     */
    private String actName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdm_trans_detail.remit_type
     *
     * @mbg.generated
     */
    private String remitType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdm_trans_detail.opp_actno
     *
     * @mbg.generated
     */
    private String oppActno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdm_trans_detail.opp_cardno
     *
     * @mbg.generated
     */
    private String oppCardno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdm_trans_detail.opp_actname
     *
     * @mbg.generated
     */
    private String oppActname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdm_trans_detail.opp_brname
     *
     * @mbg.generated
     */
    private String oppBrname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdm_trans_detail.opp_brno
     *
     * @mbg.generated
     */
    private String oppBrno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdm_trans_detail.tran_amountcny
     *
     * @mbg.generated
     */
    private BigDecimal tranAmountcny;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdm_trans_detail.mer_no
     *
     * @mbg.generated
     */
    private String merNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdm_trans_detail.mer_name
     *
     * @mbg.generated
     */
    private String merName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdm_trans_detail.rembak
     *
     * @mbg.generated
     */
    private String rembak;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdm_trans_detail.usage_name
     *
     * @mbg.generated
     */
    private String usageName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdm_trans_detail.tran_ps
     *
     * @mbg.generated
     */
    private String tranPs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdm_trans_detail.summary
     *
     * @mbg.generated
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdm_trans_detail.sum_flag
     *
     * @mbg.generated
     */
    private String sumFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdm_trans_detail.edit_flag
     *
     * @mbg.generated
     */
    private String editFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdm_trans_detail.sys_code
     *
     * @mbg.generated
     */
    private String sysCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cdm_trans_detail
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * clone方法
     * @return 浅拷贝对象
     * @throws CloneNotSupportedException
     */
    @Override
    public Object clone() throws CloneNotSupportedException {
        return super.clone();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdm_trans_detail.cust_id
     *
     * @return the value of cdm_trans_detail.cust_id
     *
     * @mbg.generated
     */
    public String getCustId() {
        return custId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdm_trans_detail.cust_id
     *
     * @param custId the value for cdm_trans_detail.cust_id
     *
     * @mbg.generated
     */
    public void setCustId(String custId) {
        this.custId = custId == null ? null : custId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdm_trans_detail.date_time
     *
     * @return the value of cdm_trans_detail.date_time
     *
     * @mbg.generated
     */
    public Date getDateTime() {
        return dateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdm_trans_detail.date_time
     *
     * @param dateTime the value for cdm_trans_detail.date_time
     *
     * @mbg.generated
     */
    public void setDateTime(Timestamp dateTime) {
        this.dateTime = dateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdm_trans_detail.tran_id
     *
     * @return the value of cdm_trans_detail.tran_id
     *
     * @mbg.generated
     */
    public String getTranId() {
        return tranId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdm_trans_detail.tran_id
     *
     * @param tranId the value for cdm_trans_detail.tran_id
     *
     * @mbg.generated
     */
    public void setTranId(String tranId) {
        this.tranId = tranId == null ? null : tranId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdm_trans_detail.card_no
     *
     * @return the value of cdm_trans_detail.card_no
     *
     * @mbg.generated
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdm_trans_detail.card_no
     *
     * @param cardNo the value for cdm_trans_detail.card_no
     *
     * @mbg.generated
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo == null ? null : cardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdm_trans_detail.tran_type
     *
     * @return the value of cdm_trans_detail.tran_type
     *
     * @mbg.generated
     */
    public String getTranType() {
        return tranType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdm_trans_detail.tran_type
     *
     * @param tranType the value for cdm_trans_detail.tran_type
     *
     * @mbg.generated
     */
    public void setTranType(String tranType) {
        this.tranType = tranType == null ? null : tranType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdm_trans_detail.tran_cat
     *
     * @return the value of cdm_trans_detail.tran_cat
     *
     * @mbg.generated
     */
    public String getTranCat() {
        return tranCat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdm_trans_detail.tran_cat
     *
     * @param tranCat the value for cdm_trans_detail.tran_cat
     *
     * @mbg.generated
     */
    public void setTranCat(String tranCat) {
        this.tranCat = tranCat == null ? null : tranCat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdm_trans_detail.tran_msg
     *
     * @return the value of cdm_trans_detail.tran_msg
     *
     * @mbg.generated
     */
    public String getTranMsg() {
        return tranMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdm_trans_detail.tran_msg
     *
     * @param tranMsg the value for cdm_trans_detail.tran_msg
     *
     * @mbg.generated
     */
    public void setTranMsg(String tranMsg) {
        this.tranMsg = tranMsg == null ? null : tranMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdm_trans_detail.tran_amount
     *
     * @return the value of cdm_trans_detail.tran_amount
     *
     * @mbg.generated
     */
    public BigDecimal getTranAmount() {
        return tranAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdm_trans_detail.tran_amount
     *
     * @param tranAmount the value for cdm_trans_detail.tran_amount
     *
     * @mbg.generated
     */
    public void setTranAmount(BigDecimal tranAmount) {
        this.tranAmount = tranAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdm_trans_detail.tran_cureen
     *
     * @return the value of cdm_trans_detail.tran_cureen
     *
     * @mbg.generated
     */
    public String getTranCureen() {
        return tranCureen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdm_trans_detail.tran_cureen
     *
     * @param tranCureen the value for cdm_trans_detail.tran_cureen
     *
     * @mbg.generated
     */
    public void setTranCureen(String tranCureen) {
        this.tranCureen = tranCureen == null ? null : tranCureen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdm_trans_detail.acct_avaibala
     *
     * @return the value of cdm_trans_detail.acct_avaibala
     *
     * @mbg.generated
     */
    public BigDecimal getAcctAvaibala() {
        return acctAvaibala;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdm_trans_detail.acct_avaibala
     *
     * @param acctAvaibala the value for cdm_trans_detail.acct_avaibala
     *
     * @mbg.generated
     */
    public void setAcctAvaibala(BigDecimal acctAvaibala) {
        this.acctAvaibala = acctAvaibala;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdm_trans_detail.act_name
     *
     * @return the value of cdm_trans_detail.act_name
     *
     * @mbg.generated
     */
    public String getActName() {
        return actName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdm_trans_detail.act_name
     *
     * @param actName the value for cdm_trans_detail.act_name
     *
     * @mbg.generated
     */
    public void setActName(String actName) {
        this.actName = actName == null ? null : actName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdm_trans_detail.remit_type
     *
     * @return the value of cdm_trans_detail.remit_type
     *
     * @mbg.generated
     */
    public String getRemitType() {
        return remitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdm_trans_detail.remit_type
     *
     * @param remitType the value for cdm_trans_detail.remit_type
     *
     * @mbg.generated
     */
    public void setRemitType(String remitType) {
        this.remitType = remitType == null ? null : remitType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdm_trans_detail.opp_actno
     *
     * @return the value of cdm_trans_detail.opp_actno
     *
     * @mbg.generated
     */
    public String getOppActno() {
        return oppActno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdm_trans_detail.opp_actno
     *
     * @param oppActno the value for cdm_trans_detail.opp_actno
     *
     * @mbg.generated
     */
    public void setOppActno(String oppActno) {
        this.oppActno = oppActno == null ? null : oppActno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdm_trans_detail.opp_cardno
     *
     * @return the value of cdm_trans_detail.opp_cardno
     *
     * @mbg.generated
     */
    public String getOppCardno() {
        return oppCardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdm_trans_detail.opp_cardno
     *
     * @param oppCardno the value for cdm_trans_detail.opp_cardno
     *
     * @mbg.generated
     */
    public void setOppCardno(String oppCardno) {
        this.oppCardno = oppCardno == null ? null : oppCardno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdm_trans_detail.opp_actname
     *
     * @return the value of cdm_trans_detail.opp_actname
     *
     * @mbg.generated
     */
    public String getOppActname() {
        return oppActname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdm_trans_detail.opp_actname
     *
     * @param oppActname the value for cdm_trans_detail.opp_actname
     *
     * @mbg.generated
     */
    public void setOppActname(String oppActname) {
        this.oppActname = oppActname == null ? null : oppActname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdm_trans_detail.opp_brname
     *
     * @return the value of cdm_trans_detail.opp_brname
     *
     * @mbg.generated
     */
    public String getOppBrname() {
        return oppBrname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdm_trans_detail.opp_brname
     *
     * @param oppBrname the value for cdm_trans_detail.opp_brname
     *
     * @mbg.generated
     */
    public void setOppBrname(String oppBrname) {
        this.oppBrname = oppBrname == null ? null : oppBrname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdm_trans_detail.opp_brno
     *
     * @return the value of cdm_trans_detail.opp_brno
     *
     * @mbg.generated
     */
    public String getOppBrno() {
        return oppBrno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdm_trans_detail.opp_brno
     *
     * @param oppBrno the value for cdm_trans_detail.opp_brno
     *
     * @mbg.generated
     */
    public void setOppBrno(String oppBrno) {
        this.oppBrno = oppBrno == null ? null : oppBrno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdm_trans_detail.tran_amountcny
     *
     * @return the value of cdm_trans_detail.tran_amountcny
     *
     * @mbg.generated
     */
    public BigDecimal getTranAmountcny() {
        return tranAmountcny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdm_trans_detail.tran_amountcny
     *
     * @param tranAmountcny the value for cdm_trans_detail.tran_amountcny
     *
     * @mbg.generated
     */
    public void setTranAmountcny(BigDecimal tranAmountcny) {
        this.tranAmountcny = tranAmountcny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdm_trans_detail.mer_no
     *
     * @return the value of cdm_trans_detail.mer_no
     *
     * @mbg.generated
     */
    public String getMerNo() {
        return merNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdm_trans_detail.mer_no
     *
     * @param merNo the value for cdm_trans_detail.mer_no
     *
     * @mbg.generated
     */
    public void setMerNo(String merNo) {
        this.merNo = merNo == null ? null : merNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdm_trans_detail.mer_name
     *
     * @return the value of cdm_trans_detail.mer_name
     *
     * @mbg.generated
     */
    public String getMerName() {
        return merName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdm_trans_detail.mer_name
     *
     * @param merName the value for cdm_trans_detail.mer_name
     *
     * @mbg.generated
     */
    public void setMerName(String merName) {
        this.merName = merName == null ? null : merName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdm_trans_detail.rembak
     *
     * @return the value of cdm_trans_detail.rembak
     *
     * @mbg.generated
     */
    public String getRembak() {
        return rembak;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdm_trans_detail.rembak
     *
     * @param rembak the value for cdm_trans_detail.rembak
     *
     * @mbg.generated
     */
    public void setRembak(String rembak) {
        this.rembak = rembak == null ? null : rembak.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdm_trans_detail.usage_name
     *
     * @return the value of cdm_trans_detail.usage_name
     *
     * @mbg.generated
     */
    public String getUsageName() {
        return usageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdm_trans_detail.usage_name
     *
     * @param usageName the value for cdm_trans_detail.usage_name
     *
     * @mbg.generated
     */
    public void setUsageName(String usageName) {
        this.usageName = usageName == null ? null : usageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdm_trans_detail.tran_ps
     *
     * @return the value of cdm_trans_detail.tran_ps
     *
     * @mbg.generated
     */
    public String getTranPs() {
        return tranPs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdm_trans_detail.tran_ps
     *
     * @param tranPs the value for cdm_trans_detail.tran_ps
     *
     * @mbg.generated
     */
    public void setTranPs(String tranPs) {
        this.tranPs = tranPs == null ? null : tranPs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdm_trans_detail.summary
     *
     * @return the value of cdm_trans_detail.summary
     *
     * @mbg.generated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdm_trans_detail.summary
     *
     * @param summary the value for cdm_trans_detail.summary
     *
     * @mbg.generated
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdm_trans_detail.sum_flag
     *
     * @return the value of cdm_trans_detail.sum_flag
     *
     * @mbg.generated
     */
    public String getSumFlag() {
        return sumFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdm_trans_detail.sum_flag
     *
     * @param sumFlag the value for cdm_trans_detail.sum_flag
     *
     * @mbg.generated
     */
    public void setSumFlag(String sumFlag) {
        this.sumFlag = sumFlag == null ? null : sumFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdm_trans_detail.edit_flag
     *
     * @return the value of cdm_trans_detail.edit_flag
     *
     * @mbg.generated
     */
    public String getEditFlag() {
        return editFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdm_trans_detail.edit_flag
     *
     * @param editFlag the value for cdm_trans_detail.edit_flag
     *
     * @mbg.generated
     */
    public void setEditFlag(String editFlag) {
        this.editFlag = editFlag == null ? null : editFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdm_trans_detail.sys_code
     *
     * @return the value of cdm_trans_detail.sys_code
     *
     * @mbg.generated
     */
    public String getSysCode() {
        return sysCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdm_trans_detail.sys_code
     *
     * @param sysCode the value for cdm_trans_detail.sys_code
     *
     * @mbg.generated
     */
    public void setSysCode(String sysCode) {
        this.sysCode = sysCode == null ? null : sysCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdm_trans_detail
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", custId=").append(custId);
        sb.append(", dateTime=").append(dateTime);
        sb.append(", tranId=").append(tranId);
        sb.append(", cardNo=").append(cardNo);
        sb.append(", tranType=").append(tranType);
        sb.append(", tranCat=").append(tranCat);
        sb.append(", tranMsg=").append(tranMsg);
        sb.append(", tranAmount=").append(tranAmount);
        sb.append(", tranCureen=").append(tranCureen);
        sb.append(", acctAvaibala=").append(acctAvaibala);
        sb.append(", actName=").append(actName);
        sb.append(", remitType=").append(remitType);
        sb.append(", oppActno=").append(oppActno);
        sb.append(", oppCardno=").append(oppCardno);
        sb.append(", oppActname=").append(oppActname);
        sb.append(", oppBrname=").append(oppBrname);
        sb.append(", oppBrno=").append(oppBrno);
        sb.append(", tranAmountcny=").append(tranAmountcny);
        sb.append(", merNo=").append(merNo);
        sb.append(", merName=").append(merName);
        sb.append(", rembak=").append(rembak);
        sb.append(", usageName=").append(usageName);
        sb.append(", tranPs=").append(tranPs);
        sb.append(", summary=").append(summary);
        sb.append(", sumFlag=").append(sumFlag);
        sb.append(", editFlag=").append(editFlag);
        sb.append(", sysCode=").append(sysCode);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * 生成文件头字符
     * @return
     */
    public static String generateFileHeader() {
        StringBuilder sb = new StringBuilder();
        sb.append("tran_id,");
        sb.append("cust_id,");
        sb.append("card_no,");
        sb.append("date_time,");
        sb.append("tran_type,");
        sb.append("tran_cat,");
        sb.append("tran_msg,");
        sb.append("tran_amount,");
        sb.append("tran_cureen,");
        sb.append("acct_avaibala,");
        sb.append("act_name,");
        sb.append("remit_type,");
        sb.append("opp_actno,");
        sb.append("opp_cardno,");
        sb.append("opp_actname,");
        sb.append("opp_brname,");
        sb.append("opp_brno,");
        sb.append("tran_amountcny,");
        sb.append("mer_no,");
        sb.append("mer_name,");
        sb.append("rembak,");
        sb.append("usage_name,");
        sb.append("tran_ps,");
        sb.append("summary,");
        sb.append("sum_flag,");
        sb.append("edit_flag,");
        sb.append("sys_code");

        return sb.toString();
    }
}