package com.heiheipp.common.mbg.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class DwdTransDetail implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_trans_detail.tran_id
     *
     * @mbg.generated
     */
    private String tranId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_trans_detail.custid
     *
     * @mbg.generated
     */
    private String custid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_trans_detail.trancid
     *
     * @mbg.generated
     */
    private String trancid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_trans_detail.trandate
     *
     * @mbg.generated
     */
    private String trandate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_trans_detail.trantime
     *
     * @mbg.generated
     */
    private String trantime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_trans_detail.classifyid
     *
     * @mbg.generated
     */
    private String classifyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_trans_detail.trancat
     *
     * @mbg.generated
     */
    private String trancat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_trans_detail.trantype
     *
     * @mbg.generated
     */
    private String trantype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_trans_detail.tranmsg
     *
     * @mbg.generated
     */
    private String tranmsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_trans_detail.crdrind
     *
     * @mbg.generated
     */
    private String crdrind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_trans_detail.cardno
     *
     * @mbg.generated
     */
    private String cardno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_trans_detail.tranamount
     *
     * @mbg.generated
     */
    private BigDecimal tranamount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_trans_detail.trancureen
     *
     * @mbg.generated
     */
    private String trancureen;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_trans_detail.acctavaibala
     *
     * @mbg.generated
     */
    private BigDecimal acctavaibala;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_trans_detail.actname
     *
     * @mbg.generated
     */
    private String actname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_trans_detail.remittype
     *
     * @mbg.generated
     */
    private String remittype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_trans_detail.oppactno
     *
     * @mbg.generated
     */
    private String oppactno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_trans_detail.oppcardno
     *
     * @mbg.generated
     */
    private String oppcardno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_trans_detail.oppactname
     *
     * @mbg.generated
     */
    private String oppactname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_trans_detail.oppbrname
     *
     * @mbg.generated
     */
    private String oppbrname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_trans_detail.oppbrno
     *
     * @mbg.generated
     */
    private String oppbrno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_trans_detail.tranamountcny
     *
     * @mbg.generated
     */
    private BigDecimal tranamountcny;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_trans_detail.merno
     *
     * @mbg.generated
     */
    private String merno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_trans_detail.mername
     *
     * @mbg.generated
     */
    private String mername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_trans_detail.rembak
     *
     * @mbg.generated
     */
    private String rembak;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_trans_detail.usagename
     *
     * @mbg.generated
     */
    private String usagename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_trans_detail.tranps
     *
     * @mbg.generated
     */
    private String tranps;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_trans_detail.summary
     *
     * @mbg.generated
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_trans_detail.sumflag
     *
     * @mbg.generated
     */
    private String sumflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_trans_detail.editflag
     *
     * @mbg.generated
     */
    private String editflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dwd_trans_detail.syscode
     *
     * @mbg.generated
     */
    private String syscode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dwd_trans_detail
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_trans_detail.tran_id
     *
     * @return the value of dwd_trans_detail.tran_id
     *
     * @mbg.generated
     */
    public String getTranId() {
        return tranId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_trans_detail.tran_id
     *
     * @param tranId the value for dwd_trans_detail.tran_id
     *
     * @mbg.generated
     */
    public void setTranId(String tranId) {
        this.tranId = tranId == null ? null : tranId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_trans_detail.custid
     *
     * @return the value of dwd_trans_detail.custid
     *
     * @mbg.generated
     */
    public String getCustid() {
        return custid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_trans_detail.custid
     *
     * @param custid the value for dwd_trans_detail.custid
     *
     * @mbg.generated
     */
    public void setCustid(String custid) {
        this.custid = custid == null ? null : custid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_trans_detail.trancid
     *
     * @return the value of dwd_trans_detail.trancid
     *
     * @mbg.generated
     */
    public String getTrancid() {
        return trancid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_trans_detail.trancid
     *
     * @param trancid the value for dwd_trans_detail.trancid
     *
     * @mbg.generated
     */
    public void setTrancid(String trancid) {
        this.trancid = trancid == null ? null : trancid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_trans_detail.trandate
     *
     * @return the value of dwd_trans_detail.trandate
     *
     * @mbg.generated
     */
    public String getTrandate() {
        return trandate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_trans_detail.trandate
     *
     * @param trandate the value for dwd_trans_detail.trandate
     *
     * @mbg.generated
     */
    public void setTrandate(String trandate) {
        this.trandate = trandate == null ? null : trandate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_trans_detail.trantime
     *
     * @return the value of dwd_trans_detail.trantime
     *
     * @mbg.generated
     */
    public String getTrantime() {
        return trantime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_trans_detail.trantime
     *
     * @param trantime the value for dwd_trans_detail.trantime
     *
     * @mbg.generated
     */
    public void setTrantime(String trantime) {
        this.trantime = trantime == null ? null : trantime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_trans_detail.classifyid
     *
     * @return the value of dwd_trans_detail.classifyid
     *
     * @mbg.generated
     */
    public String getClassifyid() {
        return classifyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_trans_detail.classifyid
     *
     * @param classifyid the value for dwd_trans_detail.classifyid
     *
     * @mbg.generated
     */
    public void setClassifyid(String classifyid) {
        this.classifyid = classifyid == null ? null : classifyid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_trans_detail.trancat
     *
     * @return the value of dwd_trans_detail.trancat
     *
     * @mbg.generated
     */
    public String getTrancat() {
        return trancat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_trans_detail.trancat
     *
     * @param trancat the value for dwd_trans_detail.trancat
     *
     * @mbg.generated
     */
    public void setTrancat(String trancat) {
        this.trancat = trancat == null ? null : trancat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_trans_detail.trantype
     *
     * @return the value of dwd_trans_detail.trantype
     *
     * @mbg.generated
     */
    public String getTrantype() {
        return trantype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_trans_detail.trantype
     *
     * @param trantype the value for dwd_trans_detail.trantype
     *
     * @mbg.generated
     */
    public void setTrantype(String trantype) {
        this.trantype = trantype == null ? null : trantype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_trans_detail.tranmsg
     *
     * @return the value of dwd_trans_detail.tranmsg
     *
     * @mbg.generated
     */
    public String getTranmsg() {
        return tranmsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_trans_detail.tranmsg
     *
     * @param tranmsg the value for dwd_trans_detail.tranmsg
     *
     * @mbg.generated
     */
    public void setTranmsg(String tranmsg) {
        this.tranmsg = tranmsg == null ? null : tranmsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_trans_detail.crdrind
     *
     * @return the value of dwd_trans_detail.crdrind
     *
     * @mbg.generated
     */
    public String getCrdrind() {
        return crdrind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_trans_detail.crdrind
     *
     * @param crdrind the value for dwd_trans_detail.crdrind
     *
     * @mbg.generated
     */
    public void setCrdrind(String crdrind) {
        this.crdrind = crdrind == null ? null : crdrind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_trans_detail.cardno
     *
     * @return the value of dwd_trans_detail.cardno
     *
     * @mbg.generated
     */
    public String getCardno() {
        return cardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_trans_detail.cardno
     *
     * @param cardno the value for dwd_trans_detail.cardno
     *
     * @mbg.generated
     */
    public void setCardno(String cardno) {
        this.cardno = cardno == null ? null : cardno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_trans_detail.tranamount
     *
     * @return the value of dwd_trans_detail.tranamount
     *
     * @mbg.generated
     */
    public BigDecimal getTranamount() {
        return tranamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_trans_detail.tranamount
     *
     * @param tranamount the value for dwd_trans_detail.tranamount
     *
     * @mbg.generated
     */
    public void setTranamount(BigDecimal tranamount) {
        this.tranamount = tranamount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_trans_detail.trancureen
     *
     * @return the value of dwd_trans_detail.trancureen
     *
     * @mbg.generated
     */
    public String getTrancureen() {
        return trancureen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_trans_detail.trancureen
     *
     * @param trancureen the value for dwd_trans_detail.trancureen
     *
     * @mbg.generated
     */
    public void setTrancureen(String trancureen) {
        this.trancureen = trancureen == null ? null : trancureen.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_trans_detail.acctavaibala
     *
     * @return the value of dwd_trans_detail.acctavaibala
     *
     * @mbg.generated
     */
    public BigDecimal getAcctavaibala() {
        return acctavaibala;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_trans_detail.acctavaibala
     *
     * @param acctavaibala the value for dwd_trans_detail.acctavaibala
     *
     * @mbg.generated
     */
    public void setAcctavaibala(BigDecimal acctavaibala) {
        this.acctavaibala = acctavaibala;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_trans_detail.actname
     *
     * @return the value of dwd_trans_detail.actname
     *
     * @mbg.generated
     */
    public String getActname() {
        return actname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_trans_detail.actname
     *
     * @param actname the value for dwd_trans_detail.actname
     *
     * @mbg.generated
     */
    public void setActname(String actname) {
        this.actname = actname == null ? null : actname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_trans_detail.remittype
     *
     * @return the value of dwd_trans_detail.remittype
     *
     * @mbg.generated
     */
    public String getRemittype() {
        return remittype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_trans_detail.remittype
     *
     * @param remittype the value for dwd_trans_detail.remittype
     *
     * @mbg.generated
     */
    public void setRemittype(String remittype) {
        this.remittype = remittype == null ? null : remittype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_trans_detail.oppactno
     *
     * @return the value of dwd_trans_detail.oppactno
     *
     * @mbg.generated
     */
    public String getOppactno() {
        return oppactno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_trans_detail.oppactno
     *
     * @param oppactno the value for dwd_trans_detail.oppactno
     *
     * @mbg.generated
     */
    public void setOppactno(String oppactno) {
        this.oppactno = oppactno == null ? null : oppactno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_trans_detail.oppcardno
     *
     * @return the value of dwd_trans_detail.oppcardno
     *
     * @mbg.generated
     */
    public String getOppcardno() {
        return oppcardno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_trans_detail.oppcardno
     *
     * @param oppcardno the value for dwd_trans_detail.oppcardno
     *
     * @mbg.generated
     */
    public void setOppcardno(String oppcardno) {
        this.oppcardno = oppcardno == null ? null : oppcardno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_trans_detail.oppactname
     *
     * @return the value of dwd_trans_detail.oppactname
     *
     * @mbg.generated
     */
    public String getOppactname() {
        return oppactname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_trans_detail.oppactname
     *
     * @param oppactname the value for dwd_trans_detail.oppactname
     *
     * @mbg.generated
     */
    public void setOppactname(String oppactname) {
        this.oppactname = oppactname == null ? null : oppactname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_trans_detail.oppbrname
     *
     * @return the value of dwd_trans_detail.oppbrname
     *
     * @mbg.generated
     */
    public String getOppbrname() {
        return oppbrname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_trans_detail.oppbrname
     *
     * @param oppbrname the value for dwd_trans_detail.oppbrname
     *
     * @mbg.generated
     */
    public void setOppbrname(String oppbrname) {
        this.oppbrname = oppbrname == null ? null : oppbrname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_trans_detail.oppbrno
     *
     * @return the value of dwd_trans_detail.oppbrno
     *
     * @mbg.generated
     */
    public String getOppbrno() {
        return oppbrno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_trans_detail.oppbrno
     *
     * @param oppbrno the value for dwd_trans_detail.oppbrno
     *
     * @mbg.generated
     */
    public void setOppbrno(String oppbrno) {
        this.oppbrno = oppbrno == null ? null : oppbrno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_trans_detail.tranamountcny
     *
     * @return the value of dwd_trans_detail.tranamountcny
     *
     * @mbg.generated
     */
    public BigDecimal getTranamountcny() {
        return tranamountcny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_trans_detail.tranamountcny
     *
     * @param tranamountcny the value for dwd_trans_detail.tranamountcny
     *
     * @mbg.generated
     */
    public void setTranamountcny(BigDecimal tranamountcny) {
        this.tranamountcny = tranamountcny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_trans_detail.merno
     *
     * @return the value of dwd_trans_detail.merno
     *
     * @mbg.generated
     */
    public String getMerno() {
        return merno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_trans_detail.merno
     *
     * @param merno the value for dwd_trans_detail.merno
     *
     * @mbg.generated
     */
    public void setMerno(String merno) {
        this.merno = merno == null ? null : merno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_trans_detail.mername
     *
     * @return the value of dwd_trans_detail.mername
     *
     * @mbg.generated
     */
    public String getMername() {
        return mername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_trans_detail.mername
     *
     * @param mername the value for dwd_trans_detail.mername
     *
     * @mbg.generated
     */
    public void setMername(String mername) {
        this.mername = mername == null ? null : mername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_trans_detail.rembak
     *
     * @return the value of dwd_trans_detail.rembak
     *
     * @mbg.generated
     */
    public String getRembak() {
        return rembak;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_trans_detail.rembak
     *
     * @param rembak the value for dwd_trans_detail.rembak
     *
     * @mbg.generated
     */
    public void setRembak(String rembak) {
        this.rembak = rembak == null ? null : rembak.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_trans_detail.usagename
     *
     * @return the value of dwd_trans_detail.usagename
     *
     * @mbg.generated
     */
    public String getUsagename() {
        return usagename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_trans_detail.usagename
     *
     * @param usagename the value for dwd_trans_detail.usagename
     *
     * @mbg.generated
     */
    public void setUsagename(String usagename) {
        this.usagename = usagename == null ? null : usagename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_trans_detail.tranps
     *
     * @return the value of dwd_trans_detail.tranps
     *
     * @mbg.generated
     */
    public String getTranps() {
        return tranps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_trans_detail.tranps
     *
     * @param tranps the value for dwd_trans_detail.tranps
     *
     * @mbg.generated
     */
    public void setTranps(String tranps) {
        this.tranps = tranps == null ? null : tranps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_trans_detail.summary
     *
     * @return the value of dwd_trans_detail.summary
     *
     * @mbg.generated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_trans_detail.summary
     *
     * @param summary the value for dwd_trans_detail.summary
     *
     * @mbg.generated
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_trans_detail.sumflag
     *
     * @return the value of dwd_trans_detail.sumflag
     *
     * @mbg.generated
     */
    public String getSumflag() {
        return sumflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_trans_detail.sumflag
     *
     * @param sumflag the value for dwd_trans_detail.sumflag
     *
     * @mbg.generated
     */
    public void setSumflag(String sumflag) {
        this.sumflag = sumflag == null ? null : sumflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_trans_detail.editflag
     *
     * @return the value of dwd_trans_detail.editflag
     *
     * @mbg.generated
     */
    public String getEditflag() {
        return editflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_trans_detail.editflag
     *
     * @param editflag the value for dwd_trans_detail.editflag
     *
     * @mbg.generated
     */
    public void setEditflag(String editflag) {
        this.editflag = editflag == null ? null : editflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dwd_trans_detail.syscode
     *
     * @return the value of dwd_trans_detail.syscode
     *
     * @mbg.generated
     */
    public String getSyscode() {
        return syscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dwd_trans_detail.syscode
     *
     * @param syscode the value for dwd_trans_detail.syscode
     *
     * @mbg.generated
     */
    public void setSyscode(String syscode) {
        this.syscode = syscode == null ? null : syscode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwd_trans_detail
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", tranId=").append(tranId);
        sb.append(", custid=").append(custid);
        sb.append(", trancid=").append(trancid);
        sb.append(", trandate=").append(trandate);
        sb.append(", trantime=").append(trantime);
        sb.append(", classifyid=").append(classifyid);
        sb.append(", trancat=").append(trancat);
        sb.append(", trantype=").append(trantype);
        sb.append(", tranmsg=").append(tranmsg);
        sb.append(", crdrind=").append(crdrind);
        sb.append(", cardno=").append(cardno);
        sb.append(", tranamount=").append(tranamount);
        sb.append(", trancureen=").append(trancureen);
        sb.append(", acctavaibala=").append(acctavaibala);
        sb.append(", actname=").append(actname);
        sb.append(", remittype=").append(remittype);
        sb.append(", oppactno=").append(oppactno);
        sb.append(", oppcardno=").append(oppcardno);
        sb.append(", oppactname=").append(oppactname);
        sb.append(", oppbrname=").append(oppbrname);
        sb.append(", oppbrno=").append(oppbrno);
        sb.append(", tranamountcny=").append(tranamountcny);
        sb.append(", merno=").append(merno);
        sb.append(", mername=").append(mername);
        sb.append(", rembak=").append(rembak);
        sb.append(", usagename=").append(usagename);
        sb.append(", tranps=").append(tranps);
        sb.append(", summary=").append(summary);
        sb.append(", sumflag=").append(sumflag);
        sb.append(", editflag=").append(editflag);
        sb.append(", syscode=").append(syscode);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}