package com.heiheipp.common.mbg.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class SzTable1 implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sz_table_1.BANK_NO
     *
     * @mbg.generated
     */
    private String bankNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sz_table_1.JIZHANG_DATE
     *
     * @mbg.generated
     */
    private String jizhangDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sz_table_1.TRAN_DATE
     *
     * @mbg.generated
     */
    private String tranDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sz_table_1.TRAN_TIME
     *
     * @mbg.generated
     */
    private String tranTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sz_table_1.TRAN_SEQ
     *
     * @mbg.generated
     */
    private String tranSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sz_table_1.FENLU_SEQ
     *
     * @mbg.generated
     */
    private String fenluSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sz_table_1.JIZHANG_BRANCH
     *
     * @mbg.generated
     */
    private String jizhangBranch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sz_table_1.JIZHANG_CURRENCY
     *
     * @mbg.generated
     */
    private String jizhangCurrency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sz_table_1.HESUAN_CODE
     *
     * @mbg.generated
     */
    private String hesuanCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sz_table_1.HESUAN_OBJ_CODE
     *
     * @mbg.generated
     */
    private String hesuanObjCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sz_table_1.SOURCE_CODE
     *
     * @mbg.generated
     */
    private String sourceCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sz_table_1.CUST_NO
     *
     * @mbg.generated
     */
    private String custNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sz_table_1.JIZHANG_AMOUNT
     *
     * @mbg.generated
     */
    private BigDecimal jizhangAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sz_table_1.ACCT_NO
     *
     * @mbg.generated
     */
    private String acctNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sz_table_1.TRAN_CODE
     *
     * @mbg.generated
     */
    private String tranCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sz_table_1.TELLER_NO
     *
     * @mbg.generated
     */
    private String tellerNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sz_table_1
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sz_table_1.BANK_NO
     *
     * @return the value of sz_table_1.BANK_NO
     *
     * @mbg.generated
     */
    public String getBankNo() {
        return bankNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sz_table_1.BANK_NO
     *
     * @param bankNo the value for sz_table_1.BANK_NO
     *
     * @mbg.generated
     */
    public void setBankNo(String bankNo) {
        this.bankNo = bankNo == null ? null : bankNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sz_table_1.JIZHANG_DATE
     *
     * @return the value of sz_table_1.JIZHANG_DATE
     *
     * @mbg.generated
     */
    public String getJizhangDate() {
        return jizhangDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sz_table_1.JIZHANG_DATE
     *
     * @param jizhangDate the value for sz_table_1.JIZHANG_DATE
     *
     * @mbg.generated
     */
    public void setJizhangDate(String jizhangDate) {
        this.jizhangDate = jizhangDate == null ? null : jizhangDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sz_table_1.TRAN_DATE
     *
     * @return the value of sz_table_1.TRAN_DATE
     *
     * @mbg.generated
     */
    public String getTranDate() {
        return tranDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sz_table_1.TRAN_DATE
     *
     * @param tranDate the value for sz_table_1.TRAN_DATE
     *
     * @mbg.generated
     */
    public void setTranDate(String tranDate) {
        this.tranDate = tranDate == null ? null : tranDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sz_table_1.TRAN_TIME
     *
     * @return the value of sz_table_1.TRAN_TIME
     *
     * @mbg.generated
     */
    public String getTranTime() {
        return tranTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sz_table_1.TRAN_TIME
     *
     * @param tranTime the value for sz_table_1.TRAN_TIME
     *
     * @mbg.generated
     */
    public void setTranTime(String tranTime) {
        this.tranTime = tranTime == null ? null : tranTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sz_table_1.TRAN_SEQ
     *
     * @return the value of sz_table_1.TRAN_SEQ
     *
     * @mbg.generated
     */
    public String getTranSeq() {
        return tranSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sz_table_1.TRAN_SEQ
     *
     * @param tranSeq the value for sz_table_1.TRAN_SEQ
     *
     * @mbg.generated
     */
    public void setTranSeq(String tranSeq) {
        this.tranSeq = tranSeq == null ? null : tranSeq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sz_table_1.FENLU_SEQ
     *
     * @return the value of sz_table_1.FENLU_SEQ
     *
     * @mbg.generated
     */
    public String getFenluSeq() {
        return fenluSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sz_table_1.FENLU_SEQ
     *
     * @param fenluSeq the value for sz_table_1.FENLU_SEQ
     *
     * @mbg.generated
     */
    public void setFenluSeq(String fenluSeq) {
        this.fenluSeq = fenluSeq == null ? null : fenluSeq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sz_table_1.JIZHANG_BRANCH
     *
     * @return the value of sz_table_1.JIZHANG_BRANCH
     *
     * @mbg.generated
     */
    public String getJizhangBranch() {
        return jizhangBranch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sz_table_1.JIZHANG_BRANCH
     *
     * @param jizhangBranch the value for sz_table_1.JIZHANG_BRANCH
     *
     * @mbg.generated
     */
    public void setJizhangBranch(String jizhangBranch) {
        this.jizhangBranch = jizhangBranch == null ? null : jizhangBranch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sz_table_1.JIZHANG_CURRENCY
     *
     * @return the value of sz_table_1.JIZHANG_CURRENCY
     *
     * @mbg.generated
     */
    public String getJizhangCurrency() {
        return jizhangCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sz_table_1.JIZHANG_CURRENCY
     *
     * @param jizhangCurrency the value for sz_table_1.JIZHANG_CURRENCY
     *
     * @mbg.generated
     */
    public void setJizhangCurrency(String jizhangCurrency) {
        this.jizhangCurrency = jizhangCurrency == null ? null : jizhangCurrency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sz_table_1.HESUAN_CODE
     *
     * @return the value of sz_table_1.HESUAN_CODE
     *
     * @mbg.generated
     */
    public String getHesuanCode() {
        return hesuanCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sz_table_1.HESUAN_CODE
     *
     * @param hesuanCode the value for sz_table_1.HESUAN_CODE
     *
     * @mbg.generated
     */
    public void setHesuanCode(String hesuanCode) {
        this.hesuanCode = hesuanCode == null ? null : hesuanCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sz_table_1.HESUAN_OBJ_CODE
     *
     * @return the value of sz_table_1.HESUAN_OBJ_CODE
     *
     * @mbg.generated
     */
    public String getHesuanObjCode() {
        return hesuanObjCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sz_table_1.HESUAN_OBJ_CODE
     *
     * @param hesuanObjCode the value for sz_table_1.HESUAN_OBJ_CODE
     *
     * @mbg.generated
     */
    public void setHesuanObjCode(String hesuanObjCode) {
        this.hesuanObjCode = hesuanObjCode == null ? null : hesuanObjCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sz_table_1.SOURCE_CODE
     *
     * @return the value of sz_table_1.SOURCE_CODE
     *
     * @mbg.generated
     */
    public String getSourceCode() {
        return sourceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sz_table_1.SOURCE_CODE
     *
     * @param sourceCode the value for sz_table_1.SOURCE_CODE
     *
     * @mbg.generated
     */
    public void setSourceCode(String sourceCode) {
        this.sourceCode = sourceCode == null ? null : sourceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sz_table_1.CUST_NO
     *
     * @return the value of sz_table_1.CUST_NO
     *
     * @mbg.generated
     */
    public String getCustNo() {
        return custNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sz_table_1.CUST_NO
     *
     * @param custNo the value for sz_table_1.CUST_NO
     *
     * @mbg.generated
     */
    public void setCustNo(String custNo) {
        this.custNo = custNo == null ? null : custNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sz_table_1.JIZHANG_AMOUNT
     *
     * @return the value of sz_table_1.JIZHANG_AMOUNT
     *
     * @mbg.generated
     */
    public BigDecimal getJizhangAmount() {
        return jizhangAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sz_table_1.JIZHANG_AMOUNT
     *
     * @param jizhangAmount the value for sz_table_1.JIZHANG_AMOUNT
     *
     * @mbg.generated
     */
    public void setJizhangAmount(BigDecimal jizhangAmount) {
        this.jizhangAmount = jizhangAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sz_table_1.ACCT_NO
     *
     * @return the value of sz_table_1.ACCT_NO
     *
     * @mbg.generated
     */
    public String getAcctNo() {
        return acctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sz_table_1.ACCT_NO
     *
     * @param acctNo the value for sz_table_1.ACCT_NO
     *
     * @mbg.generated
     */
    public void setAcctNo(String acctNo) {
        this.acctNo = acctNo == null ? null : acctNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sz_table_1.TRAN_CODE
     *
     * @return the value of sz_table_1.TRAN_CODE
     *
     * @mbg.generated
     */
    public String getTranCode() {
        return tranCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sz_table_1.TRAN_CODE
     *
     * @param tranCode the value for sz_table_1.TRAN_CODE
     *
     * @mbg.generated
     */
    public void setTranCode(String tranCode) {
        this.tranCode = tranCode == null ? null : tranCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sz_table_1.TELLER_NO
     *
     * @return the value of sz_table_1.TELLER_NO
     *
     * @mbg.generated
     */
    public String getTellerNo() {
        return tellerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sz_table_1.TELLER_NO
     *
     * @param tellerNo the value for sz_table_1.TELLER_NO
     *
     * @mbg.generated
     */
    public void setTellerNo(String tellerNo) {
        this.tellerNo = tellerNo == null ? null : tellerNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sz_table_1
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", bankNo=").append(bankNo);
        sb.append(", jizhangDate=").append(jizhangDate);
        sb.append(", tranDate=").append(tranDate);
        sb.append(", tranTime=").append(tranTime);
        sb.append(", tranSeq=").append(tranSeq);
        sb.append(", fenluSeq=").append(fenluSeq);
        sb.append(", jizhangBranch=").append(jizhangBranch);
        sb.append(", jizhangCurrency=").append(jizhangCurrency);
        sb.append(", hesuanCode=").append(hesuanCode);
        sb.append(", hesuanObjCode=").append(hesuanObjCode);
        sb.append(", sourceCode=").append(sourceCode);
        sb.append(", custNo=").append(custNo);
        sb.append(", jizhangAmount=").append(jizhangAmount);
        sb.append(", acctNo=").append(acctNo);
        sb.append(", tranCode=").append(tranCode);
        sb.append(", tellerNo=").append(tellerNo);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * 生成文件头字符
     * @return
     */
    public static String generateFileHeader() {
        StringBuilder sb = new StringBuilder();
        sb.append("bankNo");
        sb.append(",jizhangDate");
        sb.append(",tranDate");
        sb.append(",tranTime");
        sb.append(",tranSeq");
        sb.append(",fenluSeq");
        sb.append(",jizhangBranch");
        sb.append(",jizhangCurrency");
        sb.append(",hesuanCode");
        sb.append(",hesuanObjCode");
        sb.append(",sourceCode");
        sb.append(",custNo");
        sb.append(",jizhangAmount");
        sb.append(",acctNo");
        sb.append(",tranCode");
        sb.append(",tellerNo");

        return sb.toString();
    }
}