package com.heiheipp.common.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class TaskLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_log.parent_id
     *
     * @mbg.generated
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_log.sub_id
     *
     * @mbg.generated
     */
    private String subId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_log.task_type
     *
     * @mbg.generated
     */
    private String taskType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_log.task_content
     *
     * @mbg.generated
     */
    private String taskContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_log.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_log.total_nums
     *
     * @mbg.generated
     */
    private Long totalNums;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_log.processed_nums
     *
     * @mbg.generated
     */
    private Long processedNums;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_log.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_log.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table task_log
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_log.parent_id
     *
     * @return the value of task_log.parent_id
     *
     * @mbg.generated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_log.parent_id
     *
     * @param parentId the value for task_log.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_log.sub_id
     *
     * @return the value of task_log.sub_id
     *
     * @mbg.generated
     */
    public String getSubId() {
        return subId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_log.sub_id
     *
     * @param subId the value for task_log.sub_id
     *
     * @mbg.generated
     */
    public void setSubId(String subId) {
        this.subId = subId == null ? null : subId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_log.task_type
     *
     * @return the value of task_log.task_type
     *
     * @mbg.generated
     */
    public String getTaskType() {
        return taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_log.task_type
     *
     * @param taskType the value for task_log.task_type
     *
     * @mbg.generated
     */
    public void setTaskType(String taskType) {
        this.taskType = taskType == null ? null : taskType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_log.task_content
     *
     * @return the value of task_log.task_content
     *
     * @mbg.generated
     */
    public String getTaskContent() {
        return taskContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_log.task_content
     *
     * @param taskContent the value for task_log.task_content
     *
     * @mbg.generated
     */
    public void setTaskContent(String taskContent) {
        this.taskContent = taskContent == null ? null : taskContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_log.status
     *
     * @return the value of task_log.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_log.status
     *
     * @param status the value for task_log.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_log.total_nums
     *
     * @return the value of task_log.total_nums
     *
     * @mbg.generated
     */
    public Long getTotalNums() {
        return totalNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_log.total_nums
     *
     * @param totalNums the value for task_log.total_nums
     *
     * @mbg.generated
     */
    public void setTotalNums(Long totalNums) {
        this.totalNums = totalNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_log.processed_nums
     *
     * @return the value of task_log.processed_nums
     *
     * @mbg.generated
     */
    public Long getProcessedNums() {
        return processedNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_log.processed_nums
     *
     * @param processedNums the value for task_log.processed_nums
     *
     * @mbg.generated
     */
    public void setProcessedNums(Long processedNums) {
        this.processedNums = processedNums;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_log.create_time
     *
     * @return the value of task_log.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_log.create_time
     *
     * @param createTime the value for task_log.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_log.update_time
     *
     * @return the value of task_log.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_log.update_time
     *
     * @param updateTime the value for task_log.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_log
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", parentId=").append(parentId);
        sb.append(", subId=").append(subId);
        sb.append(", taskType=").append(taskType);
        sb.append(", taskContent=").append(taskContent);
        sb.append(", status=").append(status);
        sb.append(", totalNums=").append(totalNums);
        sb.append(", processedNums=").append(processedNums);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}