package com.heiheipp.common.mbg.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class TestHtap2Sordata001 extends BaseModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_001.ZDY_ZJ
     *
     * @mbg.generated
     */
    private String zdyZj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_001.DTE
     *
     * @mbg.generated
     */
    private String dte;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_001.JRXKZH
     *
     * @mbg.generated
     */
    private String jrxkzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_001.NBJGH
     *
     * @mbg.generated
     */
    private String nbjgh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_001.YHJGMC
     *
     * @mbg.generated
     */
    private String yhjgmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_001.KHTYBH
     *
     * @mbg.generated
     */
    private String khtybh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_001.KHXM
     *
     * @mbg.generated
     */
    private String khxm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_001.ZJLB
     *
     * @mbg.generated
     */
    private String zjlb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_001.ZJHM
     *
     * @mbg.generated
     */
    private String zjhm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_001.KHLX
     *
     * @mbg.generated
     */
    private String khlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_001.GJ
     *
     * @mbg.generated
     */
    private String gj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_001.MZ
     *
     * @mbg.generated
     */
    private String mz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_001.XB
     *
     * @mbg.generated
     */
    private String xb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_001.XL
     *
     * @mbg.generated
     */
    private String xl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_001.CSNY
     *
     * @mbg.generated
     */
    private String csny;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_001.SFYH
     *
     * @mbg.generated
     */
    private String sfyh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_001.GZDWMC
     *
     * @mbg.generated
     */
    private String gzdwmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_001.GZDWDZ
     *
     * @mbg.generated
     */
    private String gzdwdz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_001.GZDWDH
     *
     * @mbg.generated
     */
    private String gzdwdh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_001.DWXZ
     *
     * @mbg.generated
     */
    private String dwxz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_001.ZY
     *
     * @mbg.generated
     */
    private String zy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_001.ZW
     *
     * @mbg.generated
     */
    private String zw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_001.GRNSR
     *
     * @mbg.generated
     */
    private BigDecimal grnsr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_001.TXDZ
     *
     * @mbg.generated
     */
    private String txdz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_001.LXDH
     *
     * @mbg.generated
     */
    private String lxdh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_001.XDKHBZ
     *
     * @mbg.generated
     */
    private String xdkhbz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_001.SCJLXDGXNY
     *
     * @mbg.generated
     */
    private String scjlxdgxny;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_001.SFNH
     *
     * @mbg.generated
     */
    private String sfnh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_001.BHYGBZ
     *
     * @mbg.generated
     */
    private String bhygbz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_001.SHMDBZ
     *
     * @mbg.generated
     */
    private String shmdbz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_001.SHMDRQ
     *
     * @mbg.generated
     */
    private String shmdrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_001.BBZ
     *
     * @mbg.generated
     */
    private String bbz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_001.CJRQ
     *
     * @mbg.generated
     */
    private String cjrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_001.GSFZJG
     *
     * @mbg.generated
     */
    private String gsfzjg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TEST_HTAP2_SORDATA_001
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_001.ZDY_ZJ
     *
     * @return the value of TEST_HTAP2_SORDATA_001.ZDY_ZJ
     *
     * @mbg.generated
     */
    public String getZdyZj() {
        return zdyZj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_001.ZDY_ZJ
     *
     * @param zdyZj the value for TEST_HTAP2_SORDATA_001.ZDY_ZJ
     *
     * @mbg.generated
     */
    public void setZdyZj(String zdyZj) {
        this.zdyZj = zdyZj == null ? null : zdyZj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_001.DTE
     *
     * @return the value of TEST_HTAP2_SORDATA_001.DTE
     *
     * @mbg.generated
     */
    public String getDte() {
        return dte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_001.DTE
     *
     * @param dte the value for TEST_HTAP2_SORDATA_001.DTE
     *
     * @mbg.generated
     */
    public void setDte(String dte) {
        this.dte = dte == null ? null : dte.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_001.JRXKZH
     *
     * @return the value of TEST_HTAP2_SORDATA_001.JRXKZH
     *
     * @mbg.generated
     */
    public String getJrxkzh() {
        return jrxkzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_001.JRXKZH
     *
     * @param jrxkzh the value for TEST_HTAP2_SORDATA_001.JRXKZH
     *
     * @mbg.generated
     */
    public void setJrxkzh(String jrxkzh) {
        this.jrxkzh = jrxkzh == null ? null : jrxkzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_001.NBJGH
     *
     * @return the value of TEST_HTAP2_SORDATA_001.NBJGH
     *
     * @mbg.generated
     */
    public String getNbjgh() {
        return nbjgh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_001.NBJGH
     *
     * @param nbjgh the value for TEST_HTAP2_SORDATA_001.NBJGH
     *
     * @mbg.generated
     */
    public void setNbjgh(String nbjgh) {
        this.nbjgh = nbjgh == null ? null : nbjgh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_001.YHJGMC
     *
     * @return the value of TEST_HTAP2_SORDATA_001.YHJGMC
     *
     * @mbg.generated
     */
    public String getYhjgmc() {
        return yhjgmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_001.YHJGMC
     *
     * @param yhjgmc the value for TEST_HTAP2_SORDATA_001.YHJGMC
     *
     * @mbg.generated
     */
    public void setYhjgmc(String yhjgmc) {
        this.yhjgmc = yhjgmc == null ? null : yhjgmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_001.KHTYBH
     *
     * @return the value of TEST_HTAP2_SORDATA_001.KHTYBH
     *
     * @mbg.generated
     */
    public String getKhtybh() {
        return khtybh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_001.KHTYBH
     *
     * @param khtybh the value for TEST_HTAP2_SORDATA_001.KHTYBH
     *
     * @mbg.generated
     */
    public void setKhtybh(String khtybh) {
        this.khtybh = khtybh == null ? null : khtybh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_001.KHXM
     *
     * @return the value of TEST_HTAP2_SORDATA_001.KHXM
     *
     * @mbg.generated
     */
    public String getKhxm() {
        return khxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_001.KHXM
     *
     * @param khxm the value for TEST_HTAP2_SORDATA_001.KHXM
     *
     * @mbg.generated
     */
    public void setKhxm(String khxm) {
        this.khxm = khxm == null ? null : khxm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_001.ZJLB
     *
     * @return the value of TEST_HTAP2_SORDATA_001.ZJLB
     *
     * @mbg.generated
     */
    public String getZjlb() {
        return zjlb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_001.ZJLB
     *
     * @param zjlb the value for TEST_HTAP2_SORDATA_001.ZJLB
     *
     * @mbg.generated
     */
    public void setZjlb(String zjlb) {
        this.zjlb = zjlb == null ? null : zjlb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_001.ZJHM
     *
     * @return the value of TEST_HTAP2_SORDATA_001.ZJHM
     *
     * @mbg.generated
     */
    public String getZjhm() {
        return zjhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_001.ZJHM
     *
     * @param zjhm the value for TEST_HTAP2_SORDATA_001.ZJHM
     *
     * @mbg.generated
     */
    public void setZjhm(String zjhm) {
        this.zjhm = zjhm == null ? null : zjhm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_001.KHLX
     *
     * @return the value of TEST_HTAP2_SORDATA_001.KHLX
     *
     * @mbg.generated
     */
    public String getKhlx() {
        return khlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_001.KHLX
     *
     * @param khlx the value for TEST_HTAP2_SORDATA_001.KHLX
     *
     * @mbg.generated
     */
    public void setKhlx(String khlx) {
        this.khlx = khlx == null ? null : khlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_001.GJ
     *
     * @return the value of TEST_HTAP2_SORDATA_001.GJ
     *
     * @mbg.generated
     */
    public String getGj() {
        return gj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_001.GJ
     *
     * @param gj the value for TEST_HTAP2_SORDATA_001.GJ
     *
     * @mbg.generated
     */
    public void setGj(String gj) {
        this.gj = gj == null ? null : gj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_001.MZ
     *
     * @return the value of TEST_HTAP2_SORDATA_001.MZ
     *
     * @mbg.generated
     */
    public String getMz() {
        return mz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_001.MZ
     *
     * @param mz the value for TEST_HTAP2_SORDATA_001.MZ
     *
     * @mbg.generated
     */
    public void setMz(String mz) {
        this.mz = mz == null ? null : mz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_001.XB
     *
     * @return the value of TEST_HTAP2_SORDATA_001.XB
     *
     * @mbg.generated
     */
    public String getXb() {
        return xb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_001.XB
     *
     * @param xb the value for TEST_HTAP2_SORDATA_001.XB
     *
     * @mbg.generated
     */
    public void setXb(String xb) {
        this.xb = xb == null ? null : xb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_001.XL
     *
     * @return the value of TEST_HTAP2_SORDATA_001.XL
     *
     * @mbg.generated
     */
    public String getXl() {
        return xl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_001.XL
     *
     * @param xl the value for TEST_HTAP2_SORDATA_001.XL
     *
     * @mbg.generated
     */
    public void setXl(String xl) {
        this.xl = xl == null ? null : xl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_001.CSNY
     *
     * @return the value of TEST_HTAP2_SORDATA_001.CSNY
     *
     * @mbg.generated
     */
    public String getCsny() {
        return csny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_001.CSNY
     *
     * @param csny the value for TEST_HTAP2_SORDATA_001.CSNY
     *
     * @mbg.generated
     */
    public void setCsny(String csny) {
        this.csny = csny == null ? null : csny.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_001.SFYH
     *
     * @return the value of TEST_HTAP2_SORDATA_001.SFYH
     *
     * @mbg.generated
     */
    public String getSfyh() {
        return sfyh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_001.SFYH
     *
     * @param sfyh the value for TEST_HTAP2_SORDATA_001.SFYH
     *
     * @mbg.generated
     */
    public void setSfyh(String sfyh) {
        this.sfyh = sfyh == null ? null : sfyh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_001.GZDWMC
     *
     * @return the value of TEST_HTAP2_SORDATA_001.GZDWMC
     *
     * @mbg.generated
     */
    public String getGzdwmc() {
        return gzdwmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_001.GZDWMC
     *
     * @param gzdwmc the value for TEST_HTAP2_SORDATA_001.GZDWMC
     *
     * @mbg.generated
     */
    public void setGzdwmc(String gzdwmc) {
        this.gzdwmc = gzdwmc == null ? null : gzdwmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_001.GZDWDZ
     *
     * @return the value of TEST_HTAP2_SORDATA_001.GZDWDZ
     *
     * @mbg.generated
     */
    public String getGzdwdz() {
        return gzdwdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_001.GZDWDZ
     *
     * @param gzdwdz the value for TEST_HTAP2_SORDATA_001.GZDWDZ
     *
     * @mbg.generated
     */
    public void setGzdwdz(String gzdwdz) {
        this.gzdwdz = gzdwdz == null ? null : gzdwdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_001.GZDWDH
     *
     * @return the value of TEST_HTAP2_SORDATA_001.GZDWDH
     *
     * @mbg.generated
     */
    public String getGzdwdh() {
        return gzdwdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_001.GZDWDH
     *
     * @param gzdwdh the value for TEST_HTAP2_SORDATA_001.GZDWDH
     *
     * @mbg.generated
     */
    public void setGzdwdh(String gzdwdh) {
        this.gzdwdh = gzdwdh == null ? null : gzdwdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_001.DWXZ
     *
     * @return the value of TEST_HTAP2_SORDATA_001.DWXZ
     *
     * @mbg.generated
     */
    public String getDwxz() {
        return dwxz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_001.DWXZ
     *
     * @param dwxz the value for TEST_HTAP2_SORDATA_001.DWXZ
     *
     * @mbg.generated
     */
    public void setDwxz(String dwxz) {
        this.dwxz = dwxz == null ? null : dwxz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_001.ZY
     *
     * @return the value of TEST_HTAP2_SORDATA_001.ZY
     *
     * @mbg.generated
     */
    public String getZy() {
        return zy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_001.ZY
     *
     * @param zy the value for TEST_HTAP2_SORDATA_001.ZY
     *
     * @mbg.generated
     */
    public void setZy(String zy) {
        this.zy = zy == null ? null : zy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_001.ZW
     *
     * @return the value of TEST_HTAP2_SORDATA_001.ZW
     *
     * @mbg.generated
     */
    public String getZw() {
        return zw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_001.ZW
     *
     * @param zw the value for TEST_HTAP2_SORDATA_001.ZW
     *
     * @mbg.generated
     */
    public void setZw(String zw) {
        this.zw = zw == null ? null : zw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_001.GRNSR
     *
     * @return the value of TEST_HTAP2_SORDATA_001.GRNSR
     *
     * @mbg.generated
     */
    public BigDecimal getGrnsr() {
        return grnsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_001.GRNSR
     *
     * @param grnsr the value for TEST_HTAP2_SORDATA_001.GRNSR
     *
     * @mbg.generated
     */
    public void setGrnsr(BigDecimal grnsr) {
        this.grnsr = grnsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_001.TXDZ
     *
     * @return the value of TEST_HTAP2_SORDATA_001.TXDZ
     *
     * @mbg.generated
     */
    public String getTxdz() {
        return txdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_001.TXDZ
     *
     * @param txdz the value for TEST_HTAP2_SORDATA_001.TXDZ
     *
     * @mbg.generated
     */
    public void setTxdz(String txdz) {
        this.txdz = txdz == null ? null : txdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_001.LXDH
     *
     * @return the value of TEST_HTAP2_SORDATA_001.LXDH
     *
     * @mbg.generated
     */
    public String getLxdh() {
        return lxdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_001.LXDH
     *
     * @param lxdh the value for TEST_HTAP2_SORDATA_001.LXDH
     *
     * @mbg.generated
     */
    public void setLxdh(String lxdh) {
        this.lxdh = lxdh == null ? null : lxdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_001.XDKHBZ
     *
     * @return the value of TEST_HTAP2_SORDATA_001.XDKHBZ
     *
     * @mbg.generated
     */
    public String getXdkhbz() {
        return xdkhbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_001.XDKHBZ
     *
     * @param xdkhbz the value for TEST_HTAP2_SORDATA_001.XDKHBZ
     *
     * @mbg.generated
     */
    public void setXdkhbz(String xdkhbz) {
        this.xdkhbz = xdkhbz == null ? null : xdkhbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_001.SCJLXDGXNY
     *
     * @return the value of TEST_HTAP2_SORDATA_001.SCJLXDGXNY
     *
     * @mbg.generated
     */
    public String getScjlxdgxny() {
        return scjlxdgxny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_001.SCJLXDGXNY
     *
     * @param scjlxdgxny the value for TEST_HTAP2_SORDATA_001.SCJLXDGXNY
     *
     * @mbg.generated
     */
    public void setScjlxdgxny(String scjlxdgxny) {
        this.scjlxdgxny = scjlxdgxny == null ? null : scjlxdgxny.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_001.SFNH
     *
     * @return the value of TEST_HTAP2_SORDATA_001.SFNH
     *
     * @mbg.generated
     */
    public String getSfnh() {
        return sfnh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_001.SFNH
     *
     * @param sfnh the value for TEST_HTAP2_SORDATA_001.SFNH
     *
     * @mbg.generated
     */
    public void setSfnh(String sfnh) {
        this.sfnh = sfnh == null ? null : sfnh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_001.BHYGBZ
     *
     * @return the value of TEST_HTAP2_SORDATA_001.BHYGBZ
     *
     * @mbg.generated
     */
    public String getBhygbz() {
        return bhygbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_001.BHYGBZ
     *
     * @param bhygbz the value for TEST_HTAP2_SORDATA_001.BHYGBZ
     *
     * @mbg.generated
     */
    public void setBhygbz(String bhygbz) {
        this.bhygbz = bhygbz == null ? null : bhygbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_001.SHMDBZ
     *
     * @return the value of TEST_HTAP2_SORDATA_001.SHMDBZ
     *
     * @mbg.generated
     */
    public String getShmdbz() {
        return shmdbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_001.SHMDBZ
     *
     * @param shmdbz the value for TEST_HTAP2_SORDATA_001.SHMDBZ
     *
     * @mbg.generated
     */
    public void setShmdbz(String shmdbz) {
        this.shmdbz = shmdbz == null ? null : shmdbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_001.SHMDRQ
     *
     * @return the value of TEST_HTAP2_SORDATA_001.SHMDRQ
     *
     * @mbg.generated
     */
    public String getShmdrq() {
        return shmdrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_001.SHMDRQ
     *
     * @param shmdrq the value for TEST_HTAP2_SORDATA_001.SHMDRQ
     *
     * @mbg.generated
     */
    public void setShmdrq(String shmdrq) {
        this.shmdrq = shmdrq == null ? null : shmdrq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_001.BBZ
     *
     * @return the value of TEST_HTAP2_SORDATA_001.BBZ
     *
     * @mbg.generated
     */
    public String getBbz() {
        return bbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_001.BBZ
     *
     * @param bbz the value for TEST_HTAP2_SORDATA_001.BBZ
     *
     * @mbg.generated
     */
    public void setBbz(String bbz) {
        this.bbz = bbz == null ? null : bbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_001.CJRQ
     *
     * @return the value of TEST_HTAP2_SORDATA_001.CJRQ
     *
     * @mbg.generated
     */
    public String getCjrq() {
        return cjrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_001.CJRQ
     *
     * @param cjrq the value for TEST_HTAP2_SORDATA_001.CJRQ
     *
     * @mbg.generated
     */
    public void setCjrq(String cjrq) {
        this.cjrq = cjrq == null ? null : cjrq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_001.GSFZJG
     *
     * @return the value of TEST_HTAP2_SORDATA_001.GSFZJG
     *
     * @mbg.generated
     */
    public String getGsfzjg() {
        return gsfzjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_001.GSFZJG
     *
     * @param gsfzjg the value for TEST_HTAP2_SORDATA_001.GSFZJG
     *
     * @mbg.generated
     */
    public void setGsfzjg(String gsfzjg) {
        this.gsfzjg = gsfzjg == null ? null : gsfzjg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST_HTAP2_SORDATA_001
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", zdyZj=").append(zdyZj);
        sb.append(", dte=").append(dte);
        sb.append(", jrxkzh=").append(jrxkzh);
        sb.append(", nbjgh=").append(nbjgh);
        sb.append(", yhjgmc=").append(yhjgmc);
        sb.append(", khtybh=").append(khtybh);
        sb.append(", khxm=").append(khxm);
        sb.append(", zjlb=").append(zjlb);
        sb.append(", zjhm=").append(zjhm);
        sb.append(", khlx=").append(khlx);
        sb.append(", gj=").append(gj);
        sb.append(", mz=").append(mz);
        sb.append(", xb=").append(xb);
        sb.append(", xl=").append(xl);
        sb.append(", csny=").append(csny);
        sb.append(", sfyh=").append(sfyh);
        sb.append(", gzdwmc=").append(gzdwmc);
        sb.append(", gzdwdz=").append(gzdwdz);
        sb.append(", gzdwdh=").append(gzdwdh);
        sb.append(", dwxz=").append(dwxz);
        sb.append(", zy=").append(zy);
        sb.append(", zw=").append(zw);
        sb.append(", grnsr=").append(grnsr);
        sb.append(", txdz=").append(txdz);
        sb.append(", lxdh=").append(lxdh);
        sb.append(", xdkhbz=").append(xdkhbz);
        sb.append(", scjlxdgxny=").append(scjlxdgxny);
        sb.append(", sfnh=").append(sfnh);
        sb.append(", bhygbz=").append(bhygbz);
        sb.append(", shmdbz=").append(shmdbz);
        sb.append(", shmdrq=").append(shmdrq);
        sb.append(", bbz=").append(bbz);
        sb.append(", cjrq=").append(cjrq);
        sb.append(", gsfzjg=").append(gsfzjg);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}