package com.heiheipp.common.mbg.model;

import java.io.Serializable;

public class Test1 implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test1.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test1.msg
     *
     * @mbg.generated
     */
    private byte[] msg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test1
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test1.id
     *
     * @return the value of test1.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test1.id
     *
     * @param id the value for test1.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test1.msg
     *
     * @return the value of test1.msg
     *
     * @mbg.generated
     */
    public byte[] getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test1.msg
     *
     * @param msg the value for test1.msg
     *
     * @mbg.generated
     */
    public void setMsg(byte[] msg) {
        this.msg = msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test1
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", msg=").append(msg);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}