package com.heiheipp.common.mbg.model;

import java.io.Serializable;

public class TestTable4 extends BaseModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table_4.V_CARD_ID
     *
     * @mbg.generated
     */
    private String vCardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table_4.V_CARD_ISSUE_ID
     *
     * @mbg.generated
     */
    private String vCardIssueId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table_4.V_INST_CODE
     *
     * @mbg.generated
     */
    private String vInstCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table_4.V_CARD_MAILER_CONTACT_ID
     *
     * @mbg.generated
     */
    private String vCardMailerContactId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_table_4
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table_4.V_CARD_ID
     *
     * @return the value of test_table_4.V_CARD_ID
     *
     * @mbg.generated
     */
    public String getvCardId() {
        return vCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table_4.V_CARD_ID
     *
     * @param vCardId the value for test_table_4.V_CARD_ID
     *
     * @mbg.generated
     */
    public void setvCardId(String vCardId) {
        this.vCardId = vCardId == null ? null : vCardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table_4.V_CARD_ISSUE_ID
     *
     * @return the value of test_table_4.V_CARD_ISSUE_ID
     *
     * @mbg.generated
     */
    public String getvCardIssueId() {
        return vCardIssueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table_4.V_CARD_ISSUE_ID
     *
     * @param vCardIssueId the value for test_table_4.V_CARD_ISSUE_ID
     *
     * @mbg.generated
     */
    public void setvCardIssueId(String vCardIssueId) {
        this.vCardIssueId = vCardIssueId == null ? null : vCardIssueId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table_4.V_INST_CODE
     *
     * @return the value of test_table_4.V_INST_CODE
     *
     * @mbg.generated
     */
    public String getvInstCode() {
        return vInstCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table_4.V_INST_CODE
     *
     * @param vInstCode the value for test_table_4.V_INST_CODE
     *
     * @mbg.generated
     */
    public void setvInstCode(String vInstCode) {
        this.vInstCode = vInstCode == null ? null : vInstCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table_4.V_CARD_MAILER_CONTACT_ID
     *
     * @return the value of test_table_4.V_CARD_MAILER_CONTACT_ID
     *
     * @mbg.generated
     */
    public String getvCardMailerContactId() {
        return vCardMailerContactId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table_4.V_CARD_MAILER_CONTACT_ID
     *
     * @param vCardMailerContactId the value for test_table_4.V_CARD_MAILER_CONTACT_ID
     *
     * @mbg.generated
     */
    public void setvCardMailerContactId(String vCardMailerContactId) {
        this.vCardMailerContactId = vCardMailerContactId == null ? null : vCardMailerContactId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table_4
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", vCardId=").append(vCardId);
        sb.append(", vCardIssueId=").append(vCardIssueId);
        sb.append(", vInstCode=").append(vInstCode);
        sb.append(", vCardMailerContactId=").append(vCardMailerContactId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * 生成文件头字符
     * @return
     */
    public static String generateFileHeader() {
        StringBuilder sb = new StringBuilder();
        sb.append("V_CARD_ID,");
        sb.append("V_CARD_ISSUE_ID,");
        sb.append("V_INST_CODE,");
        sb.append("V_CARD_MAILER_CONTACT_ID");

        return sb.toString();
    }
}