package com.heiheipp.common.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class TestTable5 extends BaseModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table_5.V_RELATION_ID
     *
     * @mbg.generated
     */
    private String vRelationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table_5.N_RELATION_SEQ_NO
     *
     * @mbg.generated
     */
    private Integer nRelationSeqNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table_5.D_START_DATE
     *
     * @mbg.generated
     */
    private Date dStartDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table_5.D_END_DATE
     *
     * @mbg.generated
     */
    private Date dEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table_5.F_DEL_FLAG
     *
     * @mbg.generated
     */
    private String fDelFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table_5.N_NEXT_NO
     *
     * @mbg.generated
     */
    private Integer nNextNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table_5.V_INST_CODE
     *
     * @mbg.generated
     */
    private String vInstCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table_5.V_SRC_CUST_REF_CODE
     *
     * @mbg.generated
     */
    private String vSrcCustRefCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table_5.V_CUST_ADDRESS_ID
     *
     * @mbg.generated
     */
    private String vCustAddressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_table_5
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table_5.V_RELATION_ID
     *
     * @return the value of test_table_5.V_RELATION_ID
     *
     * @mbg.generated
     */
    public String getvRelationId() {
        return vRelationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table_5.V_RELATION_ID
     *
     * @param vRelationId the value for test_table_5.V_RELATION_ID
     *
     * @mbg.generated
     */
    public void setvRelationId(String vRelationId) {
        this.vRelationId = vRelationId == null ? null : vRelationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table_5.N_RELATION_SEQ_NO
     *
     * @return the value of test_table_5.N_RELATION_SEQ_NO
     *
     * @mbg.generated
     */
    public Integer getnRelationSeqNo() {
        return nRelationSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table_5.N_RELATION_SEQ_NO
     *
     * @param nRelationSeqNo the value for test_table_5.N_RELATION_SEQ_NO
     *
     * @mbg.generated
     */
    public void setnRelationSeqNo(Integer nRelationSeqNo) {
        this.nRelationSeqNo = nRelationSeqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table_5.D_START_DATE
     *
     * @return the value of test_table_5.D_START_DATE
     *
     * @mbg.generated
     */
    public Date getdStartDate() {
        return dStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table_5.D_START_DATE
     *
     * @param dStartDate the value for test_table_5.D_START_DATE
     *
     * @mbg.generated
     */
    public void setdStartDate(Date dStartDate) {
        this.dStartDate = dStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table_5.D_END_DATE
     *
     * @return the value of test_table_5.D_END_DATE
     *
     * @mbg.generated
     */
    public Date getdEndDate() {
        return dEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table_5.D_END_DATE
     *
     * @param dEndDate the value for test_table_5.D_END_DATE
     *
     * @mbg.generated
     */
    public void setdEndDate(Date dEndDate) {
        this.dEndDate = dEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table_5.F_DEL_FLAG
     *
     * @return the value of test_table_5.F_DEL_FLAG
     *
     * @mbg.generated
     */
    public String getfDelFlag() {
        return fDelFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table_5.F_DEL_FLAG
     *
     * @param fDelFlag the value for test_table_5.F_DEL_FLAG
     *
     * @mbg.generated
     */
    public void setfDelFlag(String fDelFlag) {
        this.fDelFlag = fDelFlag == null ? null : fDelFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table_5.N_NEXT_NO
     *
     * @return the value of test_table_5.N_NEXT_NO
     *
     * @mbg.generated
     */
    public Integer getnNextNo() {
        return nNextNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table_5.N_NEXT_NO
     *
     * @param nNextNo the value for test_table_5.N_NEXT_NO
     *
     * @mbg.generated
     */
    public void setnNextNo(Integer nNextNo) {
        this.nNextNo = nNextNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table_5.V_INST_CODE
     *
     * @return the value of test_table_5.V_INST_CODE
     *
     * @mbg.generated
     */
    public String getvInstCode() {
        return vInstCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table_5.V_INST_CODE
     *
     * @param vInstCode the value for test_table_5.V_INST_CODE
     *
     * @mbg.generated
     */
    public void setvInstCode(String vInstCode) {
        this.vInstCode = vInstCode == null ? null : vInstCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table_5.V_SRC_CUST_REF_CODE
     *
     * @return the value of test_table_5.V_SRC_CUST_REF_CODE
     *
     * @mbg.generated
     */
    public String getvSrcCustRefCode() {
        return vSrcCustRefCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table_5.V_SRC_CUST_REF_CODE
     *
     * @param vSrcCustRefCode the value for test_table_5.V_SRC_CUST_REF_CODE
     *
     * @mbg.generated
     */
    public void setvSrcCustRefCode(String vSrcCustRefCode) {
        this.vSrcCustRefCode = vSrcCustRefCode == null ? null : vSrcCustRefCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table_5.V_CUST_ADDRESS_ID
     *
     * @return the value of test_table_5.V_CUST_ADDRESS_ID
     *
     * @mbg.generated
     */
    public String getvCustAddressId() {
        return vCustAddressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table_5.V_CUST_ADDRESS_ID
     *
     * @param vCustAddressId the value for test_table_5.V_CUST_ADDRESS_ID
     *
     * @mbg.generated
     */
    public void setvCustAddressId(String vCustAddressId) {
        this.vCustAddressId = vCustAddressId == null ? null : vCustAddressId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table_5
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", vRelationId=").append(vRelationId);
        sb.append(", nRelationSeqNo=").append(nRelationSeqNo);
        sb.append(", dStartDate=").append(dStartDate);
        sb.append(", dEndDate=").append(dEndDate);
        sb.append(", fDelFlag=").append(fDelFlag);
        sb.append(", nNextNo=").append(nNextNo);
        sb.append(", vInstCode=").append(vInstCode);
        sb.append(", vSrcCustRefCode=").append(vSrcCustRefCode);
        sb.append(", vCustAddressId=").append(vCustAddressId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * 生成文件头字符
     * @return
     */
    public static String generateFileHeader() {
        StringBuilder sb = new StringBuilder();
        sb.append("V_RELATION_ID,");
        sb.append("N_RELATION_SEQ_NO,");
        sb.append("D_START_DATE,");
        sb.append("D_END_DATE,");
        sb.append("F_DEL_FLAG,");
        sb.append("N_NEXT_NO,");
        sb.append("V_INST_CODE,");
        sb.append("V_SRC_CUST_REF_CODE,");
        sb.append("V_CUST_ADDRESS_ID");

        return sb.toString();
    }
}