package com.heiheipp.common.mbg.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class TestHtap2Sordata002 extends BaseModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_002.ZDY_ZJ
     *
     * @mbg.generated
     */
    private String zdyZj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_002.DTE
     *
     * @mbg.generated
     */
    private String dte;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_002.JRXKZH
     *
     * @mbg.generated
     */
    private String jrxkzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_002.NBJGH
     *
     * @mbg.generated
     */
    private String nbjgh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_002.YHJGMC
     *
     * @mbg.generated
     */
    private String yhjgmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_002.KHTYBH
     *
     * @mbg.generated
     */
    private String khtybh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_002.KHMC
     *
     * @mbg.generated
     */
    private String khmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_002.KHLX
     *
     * @mbg.generated
     */
    private String khlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_002.ZJLB
     *
     * @mbg.generated
     */
    private String zjlb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_002.ZJHM
     *
     * @mbg.generated
     */
    private String zjhm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_002.FRDB
     *
     * @mbg.generated
     */
    private String frdb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_002.FRDBZJLB
     *
     * @mbg.generated
     */
    private String frdbzjlb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_002.FRDBZJHM
     *
     * @mbg.generated
     */
    private String frdbzjhm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_002.CWFZR
     *
     * @mbg.generated
     */
    private String cwfzr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_002.CWFZRZJLB
     *
     * @mbg.generated
     */
    private String cwfzrzjlb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_002.CWFZRZJHM
     *
     * @mbg.generated
     */
    private String cwfzrzjhm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_002.JBCKZH
     *
     * @mbg.generated
     */
    private String jbckzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_002.JBCKZHKHHH
     *
     * @mbg.generated
     */
    private String jbckzhkhhh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_002.JBCKZHKHHMC
     *
     * @mbg.generated
     */
    private String jbckzhkhhmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_002.ZCZB
     *
     * @mbg.generated
     */
    private BigDecimal zczb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_002.ZCZBBZ
     *
     * @mbg.generated
     */
    private String zczbbz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_002.SSZB
     *
     * @mbg.generated
     */
    private BigDecimal sszb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_002.SSZBBZ
     *
     * @mbg.generated
     */
    private String sszbbz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_002.ZCDZ
     *
     * @mbg.generated
     */
    private String zcdz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_002.LXDH
     *
     * @mbg.generated
     */
    private String lxdh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_002.JYFW
     *
     * @mbg.generated
     */
    private String jyfw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_002.CLRQ
     *
     * @mbg.generated
     */
    private String clrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_002.SSHY
     *
     * @mbg.generated
     */
    private String sshy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_002.QYFL
     *
     * @mbg.generated
     */
    private String qyfl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_002.XDKHBZ
     *
     * @mbg.generated
     */
    private String xdkhbz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_002.SCJLXDGXNY
     *
     * @mbg.generated
     */
    private String scjlxdgxny;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_002.SSGSBZ
     *
     * @mbg.generated
     */
    private String ssgsbz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_002.XYPJ
     *
     * @mbg.generated
     */
    private String xypj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_002.YGRS
     *
     * @mbg.generated
     */
    private Integer ygrs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_002.XZQHDM
     *
     * @mbg.generated
     */
    private String xzqhdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_002.FXYJXH
     *
     * @mbg.generated
     */
    private String fxyjxh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_002.GZSJDM
     *
     * @mbg.generated
     */
    private String gzsjdm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_002.BBZ
     *
     * @mbg.generated
     */
    private String bbz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_002.CJRQ
     *
     * @mbg.generated
     */
    private String cjrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_SORDATA_002.GSFZJG
     *
     * @mbg.generated
     */
    private String gsfzjg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TEST_HTAP2_SORDATA_002
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_002.ZDY_ZJ
     *
     * @return the value of TEST_HTAP2_SORDATA_002.ZDY_ZJ
     *
     * @mbg.generated
     */
    public String getZdyZj() {
        return zdyZj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_002.ZDY_ZJ
     *
     * @param zdyZj the value for TEST_HTAP2_SORDATA_002.ZDY_ZJ
     *
     * @mbg.generated
     */
    public void setZdyZj(String zdyZj) {
        this.zdyZj = zdyZj == null ? null : zdyZj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_002.DTE
     *
     * @return the value of TEST_HTAP2_SORDATA_002.DTE
     *
     * @mbg.generated
     */
    public String getDte() {
        return dte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_002.DTE
     *
     * @param dte the value for TEST_HTAP2_SORDATA_002.DTE
     *
     * @mbg.generated
     */
    public void setDte(String dte) {
        this.dte = dte == null ? null : dte.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_002.JRXKZH
     *
     * @return the value of TEST_HTAP2_SORDATA_002.JRXKZH
     *
     * @mbg.generated
     */
    public String getJrxkzh() {
        return jrxkzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_002.JRXKZH
     *
     * @param jrxkzh the value for TEST_HTAP2_SORDATA_002.JRXKZH
     *
     * @mbg.generated
     */
    public void setJrxkzh(String jrxkzh) {
        this.jrxkzh = jrxkzh == null ? null : jrxkzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_002.NBJGH
     *
     * @return the value of TEST_HTAP2_SORDATA_002.NBJGH
     *
     * @mbg.generated
     */
    public String getNbjgh() {
        return nbjgh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_002.NBJGH
     *
     * @param nbjgh the value for TEST_HTAP2_SORDATA_002.NBJGH
     *
     * @mbg.generated
     */
    public void setNbjgh(String nbjgh) {
        this.nbjgh = nbjgh == null ? null : nbjgh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_002.YHJGMC
     *
     * @return the value of TEST_HTAP2_SORDATA_002.YHJGMC
     *
     * @mbg.generated
     */
    public String getYhjgmc() {
        return yhjgmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_002.YHJGMC
     *
     * @param yhjgmc the value for TEST_HTAP2_SORDATA_002.YHJGMC
     *
     * @mbg.generated
     */
    public void setYhjgmc(String yhjgmc) {
        this.yhjgmc = yhjgmc == null ? null : yhjgmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_002.KHTYBH
     *
     * @return the value of TEST_HTAP2_SORDATA_002.KHTYBH
     *
     * @mbg.generated
     */
    public String getKhtybh() {
        return khtybh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_002.KHTYBH
     *
     * @param khtybh the value for TEST_HTAP2_SORDATA_002.KHTYBH
     *
     * @mbg.generated
     */
    public void setKhtybh(String khtybh) {
        this.khtybh = khtybh == null ? null : khtybh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_002.KHMC
     *
     * @return the value of TEST_HTAP2_SORDATA_002.KHMC
     *
     * @mbg.generated
     */
    public String getKhmc() {
        return khmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_002.KHMC
     *
     * @param khmc the value for TEST_HTAP2_SORDATA_002.KHMC
     *
     * @mbg.generated
     */
    public void setKhmc(String khmc) {
        this.khmc = khmc == null ? null : khmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_002.KHLX
     *
     * @return the value of TEST_HTAP2_SORDATA_002.KHLX
     *
     * @mbg.generated
     */
    public String getKhlx() {
        return khlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_002.KHLX
     *
     * @param khlx the value for TEST_HTAP2_SORDATA_002.KHLX
     *
     * @mbg.generated
     */
    public void setKhlx(String khlx) {
        this.khlx = khlx == null ? null : khlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_002.ZJLB
     *
     * @return the value of TEST_HTAP2_SORDATA_002.ZJLB
     *
     * @mbg.generated
     */
    public String getZjlb() {
        return zjlb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_002.ZJLB
     *
     * @param zjlb the value for TEST_HTAP2_SORDATA_002.ZJLB
     *
     * @mbg.generated
     */
    public void setZjlb(String zjlb) {
        this.zjlb = zjlb == null ? null : zjlb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_002.ZJHM
     *
     * @return the value of TEST_HTAP2_SORDATA_002.ZJHM
     *
     * @mbg.generated
     */
    public String getZjhm() {
        return zjhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_002.ZJHM
     *
     * @param zjhm the value for TEST_HTAP2_SORDATA_002.ZJHM
     *
     * @mbg.generated
     */
    public void setZjhm(String zjhm) {
        this.zjhm = zjhm == null ? null : zjhm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_002.FRDB
     *
     * @return the value of TEST_HTAP2_SORDATA_002.FRDB
     *
     * @mbg.generated
     */
    public String getFrdb() {
        return frdb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_002.FRDB
     *
     * @param frdb the value for TEST_HTAP2_SORDATA_002.FRDB
     *
     * @mbg.generated
     */
    public void setFrdb(String frdb) {
        this.frdb = frdb == null ? null : frdb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_002.FRDBZJLB
     *
     * @return the value of TEST_HTAP2_SORDATA_002.FRDBZJLB
     *
     * @mbg.generated
     */
    public String getFrdbzjlb() {
        return frdbzjlb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_002.FRDBZJLB
     *
     * @param frdbzjlb the value for TEST_HTAP2_SORDATA_002.FRDBZJLB
     *
     * @mbg.generated
     */
    public void setFrdbzjlb(String frdbzjlb) {
        this.frdbzjlb = frdbzjlb == null ? null : frdbzjlb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_002.FRDBZJHM
     *
     * @return the value of TEST_HTAP2_SORDATA_002.FRDBZJHM
     *
     * @mbg.generated
     */
    public String getFrdbzjhm() {
        return frdbzjhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_002.FRDBZJHM
     *
     * @param frdbzjhm the value for TEST_HTAP2_SORDATA_002.FRDBZJHM
     *
     * @mbg.generated
     */
    public void setFrdbzjhm(String frdbzjhm) {
        this.frdbzjhm = frdbzjhm == null ? null : frdbzjhm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_002.CWFZR
     *
     * @return the value of TEST_HTAP2_SORDATA_002.CWFZR
     *
     * @mbg.generated
     */
    public String getCwfzr() {
        return cwfzr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_002.CWFZR
     *
     * @param cwfzr the value for TEST_HTAP2_SORDATA_002.CWFZR
     *
     * @mbg.generated
     */
    public void setCwfzr(String cwfzr) {
        this.cwfzr = cwfzr == null ? null : cwfzr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_002.CWFZRZJLB
     *
     * @return the value of TEST_HTAP2_SORDATA_002.CWFZRZJLB
     *
     * @mbg.generated
     */
    public String getCwfzrzjlb() {
        return cwfzrzjlb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_002.CWFZRZJLB
     *
     * @param cwfzrzjlb the value for TEST_HTAP2_SORDATA_002.CWFZRZJLB
     *
     * @mbg.generated
     */
    public void setCwfzrzjlb(String cwfzrzjlb) {
        this.cwfzrzjlb = cwfzrzjlb == null ? null : cwfzrzjlb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_002.CWFZRZJHM
     *
     * @return the value of TEST_HTAP2_SORDATA_002.CWFZRZJHM
     *
     * @mbg.generated
     */
    public String getCwfzrzjhm() {
        return cwfzrzjhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_002.CWFZRZJHM
     *
     * @param cwfzrzjhm the value for TEST_HTAP2_SORDATA_002.CWFZRZJHM
     *
     * @mbg.generated
     */
    public void setCwfzrzjhm(String cwfzrzjhm) {
        this.cwfzrzjhm = cwfzrzjhm == null ? null : cwfzrzjhm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_002.JBCKZH
     *
     * @return the value of TEST_HTAP2_SORDATA_002.JBCKZH
     *
     * @mbg.generated
     */
    public String getJbckzh() {
        return jbckzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_002.JBCKZH
     *
     * @param jbckzh the value for TEST_HTAP2_SORDATA_002.JBCKZH
     *
     * @mbg.generated
     */
    public void setJbckzh(String jbckzh) {
        this.jbckzh = jbckzh == null ? null : jbckzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_002.JBCKZHKHHH
     *
     * @return the value of TEST_HTAP2_SORDATA_002.JBCKZHKHHH
     *
     * @mbg.generated
     */
    public String getJbckzhkhhh() {
        return jbckzhkhhh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_002.JBCKZHKHHH
     *
     * @param jbckzhkhhh the value for TEST_HTAP2_SORDATA_002.JBCKZHKHHH
     *
     * @mbg.generated
     */
    public void setJbckzhkhhh(String jbckzhkhhh) {
        this.jbckzhkhhh = jbckzhkhhh == null ? null : jbckzhkhhh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_002.JBCKZHKHHMC
     *
     * @return the value of TEST_HTAP2_SORDATA_002.JBCKZHKHHMC
     *
     * @mbg.generated
     */
    public String getJbckzhkhhmc() {
        return jbckzhkhhmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_002.JBCKZHKHHMC
     *
     * @param jbckzhkhhmc the value for TEST_HTAP2_SORDATA_002.JBCKZHKHHMC
     *
     * @mbg.generated
     */
    public void setJbckzhkhhmc(String jbckzhkhhmc) {
        this.jbckzhkhhmc = jbckzhkhhmc == null ? null : jbckzhkhhmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_002.ZCZB
     *
     * @return the value of TEST_HTAP2_SORDATA_002.ZCZB
     *
     * @mbg.generated
     */
    public BigDecimal getZczb() {
        return zczb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_002.ZCZB
     *
     * @param zczb the value for TEST_HTAP2_SORDATA_002.ZCZB
     *
     * @mbg.generated
     */
    public void setZczb(BigDecimal zczb) {
        this.zczb = zczb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_002.ZCZBBZ
     *
     * @return the value of TEST_HTAP2_SORDATA_002.ZCZBBZ
     *
     * @mbg.generated
     */
    public String getZczbbz() {
        return zczbbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_002.ZCZBBZ
     *
     * @param zczbbz the value for TEST_HTAP2_SORDATA_002.ZCZBBZ
     *
     * @mbg.generated
     */
    public void setZczbbz(String zczbbz) {
        this.zczbbz = zczbbz == null ? null : zczbbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_002.SSZB
     *
     * @return the value of TEST_HTAP2_SORDATA_002.SSZB
     *
     * @mbg.generated
     */
    public BigDecimal getSszb() {
        return sszb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_002.SSZB
     *
     * @param sszb the value for TEST_HTAP2_SORDATA_002.SSZB
     *
     * @mbg.generated
     */
    public void setSszb(BigDecimal sszb) {
        this.sszb = sszb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_002.SSZBBZ
     *
     * @return the value of TEST_HTAP2_SORDATA_002.SSZBBZ
     *
     * @mbg.generated
     */
    public String getSszbbz() {
        return sszbbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_002.SSZBBZ
     *
     * @param sszbbz the value for TEST_HTAP2_SORDATA_002.SSZBBZ
     *
     * @mbg.generated
     */
    public void setSszbbz(String sszbbz) {
        this.sszbbz = sszbbz == null ? null : sszbbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_002.ZCDZ
     *
     * @return the value of TEST_HTAP2_SORDATA_002.ZCDZ
     *
     * @mbg.generated
     */
    public String getZcdz() {
        return zcdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_002.ZCDZ
     *
     * @param zcdz the value for TEST_HTAP2_SORDATA_002.ZCDZ
     *
     * @mbg.generated
     */
    public void setZcdz(String zcdz) {
        this.zcdz = zcdz == null ? null : zcdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_002.LXDH
     *
     * @return the value of TEST_HTAP2_SORDATA_002.LXDH
     *
     * @mbg.generated
     */
    public String getLxdh() {
        return lxdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_002.LXDH
     *
     * @param lxdh the value for TEST_HTAP2_SORDATA_002.LXDH
     *
     * @mbg.generated
     */
    public void setLxdh(String lxdh) {
        this.lxdh = lxdh == null ? null : lxdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_002.JYFW
     *
     * @return the value of TEST_HTAP2_SORDATA_002.JYFW
     *
     * @mbg.generated
     */
    public String getJyfw() {
        return jyfw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_002.JYFW
     *
     * @param jyfw the value for TEST_HTAP2_SORDATA_002.JYFW
     *
     * @mbg.generated
     */
    public void setJyfw(String jyfw) {
        this.jyfw = jyfw == null ? null : jyfw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_002.CLRQ
     *
     * @return the value of TEST_HTAP2_SORDATA_002.CLRQ
     *
     * @mbg.generated
     */
    public String getClrq() {
        return clrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_002.CLRQ
     *
     * @param clrq the value for TEST_HTAP2_SORDATA_002.CLRQ
     *
     * @mbg.generated
     */
    public void setClrq(String clrq) {
        this.clrq = clrq == null ? null : clrq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_002.SSHY
     *
     * @return the value of TEST_HTAP2_SORDATA_002.SSHY
     *
     * @mbg.generated
     */
    public String getSshy() {
        return sshy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_002.SSHY
     *
     * @param sshy the value for TEST_HTAP2_SORDATA_002.SSHY
     *
     * @mbg.generated
     */
    public void setSshy(String sshy) {
        this.sshy = sshy == null ? null : sshy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_002.QYFL
     *
     * @return the value of TEST_HTAP2_SORDATA_002.QYFL
     *
     * @mbg.generated
     */
    public String getQyfl() {
        return qyfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_002.QYFL
     *
     * @param qyfl the value for TEST_HTAP2_SORDATA_002.QYFL
     *
     * @mbg.generated
     */
    public void setQyfl(String qyfl) {
        this.qyfl = qyfl == null ? null : qyfl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_002.XDKHBZ
     *
     * @return the value of TEST_HTAP2_SORDATA_002.XDKHBZ
     *
     * @mbg.generated
     */
    public String getXdkhbz() {
        return xdkhbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_002.XDKHBZ
     *
     * @param xdkhbz the value for TEST_HTAP2_SORDATA_002.XDKHBZ
     *
     * @mbg.generated
     */
    public void setXdkhbz(String xdkhbz) {
        this.xdkhbz = xdkhbz == null ? null : xdkhbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_002.SCJLXDGXNY
     *
     * @return the value of TEST_HTAP2_SORDATA_002.SCJLXDGXNY
     *
     * @mbg.generated
     */
    public String getScjlxdgxny() {
        return scjlxdgxny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_002.SCJLXDGXNY
     *
     * @param scjlxdgxny the value for TEST_HTAP2_SORDATA_002.SCJLXDGXNY
     *
     * @mbg.generated
     */
    public void setScjlxdgxny(String scjlxdgxny) {
        this.scjlxdgxny = scjlxdgxny == null ? null : scjlxdgxny.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_002.SSGSBZ
     *
     * @return the value of TEST_HTAP2_SORDATA_002.SSGSBZ
     *
     * @mbg.generated
     */
    public String getSsgsbz() {
        return ssgsbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_002.SSGSBZ
     *
     * @param ssgsbz the value for TEST_HTAP2_SORDATA_002.SSGSBZ
     *
     * @mbg.generated
     */
    public void setSsgsbz(String ssgsbz) {
        this.ssgsbz = ssgsbz == null ? null : ssgsbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_002.XYPJ
     *
     * @return the value of TEST_HTAP2_SORDATA_002.XYPJ
     *
     * @mbg.generated
     */
    public String getXypj() {
        return xypj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_002.XYPJ
     *
     * @param xypj the value for TEST_HTAP2_SORDATA_002.XYPJ
     *
     * @mbg.generated
     */
    public void setXypj(String xypj) {
        this.xypj = xypj == null ? null : xypj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_002.YGRS
     *
     * @return the value of TEST_HTAP2_SORDATA_002.YGRS
     *
     * @mbg.generated
     */
    public Integer getYgrs() {
        return ygrs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_002.YGRS
     *
     * @param ygrs the value for TEST_HTAP2_SORDATA_002.YGRS
     *
     * @mbg.generated
     */
    public void setYgrs(Integer ygrs) {
        this.ygrs = ygrs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_002.XZQHDM
     *
     * @return the value of TEST_HTAP2_SORDATA_002.XZQHDM
     *
     * @mbg.generated
     */
    public String getXzqhdm() {
        return xzqhdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_002.XZQHDM
     *
     * @param xzqhdm the value for TEST_HTAP2_SORDATA_002.XZQHDM
     *
     * @mbg.generated
     */
    public void setXzqhdm(String xzqhdm) {
        this.xzqhdm = xzqhdm == null ? null : xzqhdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_002.FXYJXH
     *
     * @return the value of TEST_HTAP2_SORDATA_002.FXYJXH
     *
     * @mbg.generated
     */
    public String getFxyjxh() {
        return fxyjxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_002.FXYJXH
     *
     * @param fxyjxh the value for TEST_HTAP2_SORDATA_002.FXYJXH
     *
     * @mbg.generated
     */
    public void setFxyjxh(String fxyjxh) {
        this.fxyjxh = fxyjxh == null ? null : fxyjxh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_002.GZSJDM
     *
     * @return the value of TEST_HTAP2_SORDATA_002.GZSJDM
     *
     * @mbg.generated
     */
    public String getGzsjdm() {
        return gzsjdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_002.GZSJDM
     *
     * @param gzsjdm the value for TEST_HTAP2_SORDATA_002.GZSJDM
     *
     * @mbg.generated
     */
    public void setGzsjdm(String gzsjdm) {
        this.gzsjdm = gzsjdm == null ? null : gzsjdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_002.BBZ
     *
     * @return the value of TEST_HTAP2_SORDATA_002.BBZ
     *
     * @mbg.generated
     */
    public String getBbz() {
        return bbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_002.BBZ
     *
     * @param bbz the value for TEST_HTAP2_SORDATA_002.BBZ
     *
     * @mbg.generated
     */
    public void setBbz(String bbz) {
        this.bbz = bbz == null ? null : bbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_002.CJRQ
     *
     * @return the value of TEST_HTAP2_SORDATA_002.CJRQ
     *
     * @mbg.generated
     */
    public String getCjrq() {
        return cjrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_002.CJRQ
     *
     * @param cjrq the value for TEST_HTAP2_SORDATA_002.CJRQ
     *
     * @mbg.generated
     */
    public void setCjrq(String cjrq) {
        this.cjrq = cjrq == null ? null : cjrq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_SORDATA_002.GSFZJG
     *
     * @return the value of TEST_HTAP2_SORDATA_002.GSFZJG
     *
     * @mbg.generated
     */
    public String getGsfzjg() {
        return gsfzjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_SORDATA_002.GSFZJG
     *
     * @param gsfzjg the value for TEST_HTAP2_SORDATA_002.GSFZJG
     *
     * @mbg.generated
     */
    public void setGsfzjg(String gsfzjg) {
        this.gsfzjg = gsfzjg == null ? null : gsfzjg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST_HTAP2_SORDATA_002
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", zdyZj=").append(zdyZj);
        sb.append(", dte=").append(dte);
        sb.append(", jrxkzh=").append(jrxkzh);
        sb.append(", nbjgh=").append(nbjgh);
        sb.append(", yhjgmc=").append(yhjgmc);
        sb.append(", khtybh=").append(khtybh);
        sb.append(", khmc=").append(khmc);
        sb.append(", khlx=").append(khlx);
        sb.append(", zjlb=").append(zjlb);
        sb.append(", zjhm=").append(zjhm);
        sb.append(", frdb=").append(frdb);
        sb.append(", frdbzjlb=").append(frdbzjlb);
        sb.append(", frdbzjhm=").append(frdbzjhm);
        sb.append(", cwfzr=").append(cwfzr);
        sb.append(", cwfzrzjlb=").append(cwfzrzjlb);
        sb.append(", cwfzrzjhm=").append(cwfzrzjhm);
        sb.append(", jbckzh=").append(jbckzh);
        sb.append(", jbckzhkhhh=").append(jbckzhkhhh);
        sb.append(", jbckzhkhhmc=").append(jbckzhkhhmc);
        sb.append(", zczb=").append(zczb);
        sb.append(", zczbbz=").append(zczbbz);
        sb.append(", sszb=").append(sszb);
        sb.append(", sszbbz=").append(sszbbz);
        sb.append(", zcdz=").append(zcdz);
        sb.append(", lxdh=").append(lxdh);
        sb.append(", jyfw=").append(jyfw);
        sb.append(", clrq=").append(clrq);
        sb.append(", sshy=").append(sshy);
        sb.append(", qyfl=").append(qyfl);
        sb.append(", xdkhbz=").append(xdkhbz);
        sb.append(", scjlxdgxny=").append(scjlxdgxny);
        sb.append(", ssgsbz=").append(ssgsbz);
        sb.append(", xypj=").append(xypj);
        sb.append(", ygrs=").append(ygrs);
        sb.append(", xzqhdm=").append(xzqhdm);
        sb.append(", fxyjxh=").append(fxyjxh);
        sb.append(", gzsjdm=").append(gzsjdm);
        sb.append(", bbz=").append(bbz);
        sb.append(", cjrq=").append(cjrq);
        sb.append(", gsfzjg=").append(gsfzjg);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}