package com.heiheipp.common.mbg.model;

import com.heiheipp.common.service.BatchModelService;

import java.io.Serializable;
import java.util.Date;

public class TestTable3 extends BaseModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table_3.V_CUST_ID
     *
     * @mbg.generated
     */
    private String vCustId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table_3.V_CUST_TYPE_CD
     *
     * @mbg.generated
     */
    private String vCustTypeCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table_3.V_INST_CODE
     *
     * @mbg.generated
     */
    private String vInstCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table_3.V_SRC_CUST_REF_CODE
     *
     * @mbg.generated
     */
    private String vSrcCustRefCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table_3.V_FIRST_NAME
     *
     * @mbg.generated
     */
    private String vFirstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table_3.V_LAST_NAME
     *
     * @mbg.generated
     */
    private String vLastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table_3.V_SEX_CD
     *
     * @mbg.generated
     */
    private String vSexCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table_3.V_ADDRESS
     *
     * @mbg.generated
     */
    private String vAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table_3.V_CITY
     *
     * @mbg.generated
     */
    private String vCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table_3.V_COUNTRY
     *
     * @mbg.generated
     */
    private String vCountry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table_3.V_POSTCODE
     *
     * @mbg.generated
     */
    private String vPostcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table_3.V_PHONE
     *
     * @mbg.generated
     */
    private String vPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table_3.V_MOBILE
     *
     * @mbg.generated
     */
    private String vMobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table_3.V_EMAIL
     *
     * @mbg.generated
     */
    private String vEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table_3.V_MARITAL_STATUS_CD
     *
     * @mbg.generated
     */
    private String vMaritalStatusCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table_3.D_BIRTHDAY
     *
     * @mbg.generated
     */
    private Date dBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_table_3
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table_3.V_CUST_ID
     *
     * @return the value of test_table_3.V_CUST_ID
     *
     * @mbg.generated
     */
    public String getvCustId() {
        return vCustId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table_3.V_CUST_ID
     *
     * @param vCustId the value for test_table_3.V_CUST_ID
     *
     * @mbg.generated
     */
    public void setvCustId(String vCustId) {
        this.vCustId = vCustId == null ? null : vCustId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table_3.V_CUST_TYPE_CD
     *
     * @return the value of test_table_3.V_CUST_TYPE_CD
     *
     * @mbg.generated
     */
    public String getvCustTypeCd() {
        return vCustTypeCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table_3.V_CUST_TYPE_CD
     *
     * @param vCustTypeCd the value for test_table_3.V_CUST_TYPE_CD
     *
     * @mbg.generated
     */
    public void setvCustTypeCd(String vCustTypeCd) {
        this.vCustTypeCd = vCustTypeCd == null ? null : vCustTypeCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table_3.V_INST_CODE
     *
     * @return the value of test_table_3.V_INST_CODE
     *
     * @mbg.generated
     */
    public String getvInstCode() {
        return vInstCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table_3.V_INST_CODE
     *
     * @param vInstCode the value for test_table_3.V_INST_CODE
     *
     * @mbg.generated
     */
    public void setvInstCode(String vInstCode) {
        this.vInstCode = vInstCode == null ? null : vInstCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table_3.V_SRC_CUST_REF_CODE
     *
     * @return the value of test_table_3.V_SRC_CUST_REF_CODE
     *
     * @mbg.generated
     */
    public String getvSrcCustRefCode() {
        return vSrcCustRefCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table_3.V_SRC_CUST_REF_CODE
     *
     * @param vSrcCustRefCode the value for test_table_3.V_SRC_CUST_REF_CODE
     *
     * @mbg.generated
     */
    public void setvSrcCustRefCode(String vSrcCustRefCode) {
        this.vSrcCustRefCode = vSrcCustRefCode == null ? null : vSrcCustRefCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table_3.V_FIRST_NAME
     *
     * @return the value of test_table_3.V_FIRST_NAME
     *
     * @mbg.generated
     */
    public String getvFirstName() {
        return vFirstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table_3.V_FIRST_NAME
     *
     * @param vFirstName the value for test_table_3.V_FIRST_NAME
     *
     * @mbg.generated
     */
    public void setvFirstName(String vFirstName) {
        this.vFirstName = vFirstName == null ? null : vFirstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table_3.V_LAST_NAME
     *
     * @return the value of test_table_3.V_LAST_NAME
     *
     * @mbg.generated
     */
    public String getvLastName() {
        return vLastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table_3.V_LAST_NAME
     *
     * @param vLastName the value for test_table_3.V_LAST_NAME
     *
     * @mbg.generated
     */
    public void setvLastName(String vLastName) {
        this.vLastName = vLastName == null ? null : vLastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table_3.V_SEX_CD
     *
     * @return the value of test_table_3.V_SEX_CD
     *
     * @mbg.generated
     */
    public String getvSexCd() {
        return vSexCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table_3.V_SEX_CD
     *
     * @param vSexCd the value for test_table_3.V_SEX_CD
     *
     * @mbg.generated
     */
    public void setvSexCd(String vSexCd) {
        this.vSexCd = vSexCd == null ? null : vSexCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table_3.V_ADDRESS
     *
     * @return the value of test_table_3.V_ADDRESS
     *
     * @mbg.generated
     */
    public String getvAddress() {
        return vAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table_3.V_ADDRESS
     *
     * @param vAddress the value for test_table_3.V_ADDRESS
     *
     * @mbg.generated
     */
    public void setvAddress(String vAddress) {
        this.vAddress = vAddress == null ? null : vAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table_3.V_CITY
     *
     * @return the value of test_table_3.V_CITY
     *
     * @mbg.generated
     */
    public String getvCity() {
        return vCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table_3.V_CITY
     *
     * @param vCity the value for test_table_3.V_CITY
     *
     * @mbg.generated
     */
    public void setvCity(String vCity) {
        this.vCity = vCity == null ? null : vCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table_3.V_COUNTRY
     *
     * @return the value of test_table_3.V_COUNTRY
     *
     * @mbg.generated
     */
    public String getvCountry() {
        return vCountry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table_3.V_COUNTRY
     *
     * @param vCountry the value for test_table_3.V_COUNTRY
     *
     * @mbg.generated
     */
    public void setvCountry(String vCountry) {
        this.vCountry = vCountry == null ? null : vCountry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table_3.V_POSTCODE
     *
     * @return the value of test_table_3.V_POSTCODE
     *
     * @mbg.generated
     */
    public String getvPostcode() {
        return vPostcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table_3.V_POSTCODE
     *
     * @param vPostcode the value for test_table_3.V_POSTCODE
     *
     * @mbg.generated
     */
    public void setvPostcode(String vPostcode) {
        this.vPostcode = vPostcode == null ? null : vPostcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table_3.V_PHONE
     *
     * @return the value of test_table_3.V_PHONE
     *
     * @mbg.generated
     */
    public String getvPhone() {
        return vPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table_3.V_PHONE
     *
     * @param vPhone the value for test_table_3.V_PHONE
     *
     * @mbg.generated
     */
    public void setvPhone(String vPhone) {
        this.vPhone = vPhone == null ? null : vPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table_3.V_MOBILE
     *
     * @return the value of test_table_3.V_MOBILE
     *
     * @mbg.generated
     */
    public String getvMobile() {
        return vMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table_3.V_MOBILE
     *
     * @param vMobile the value for test_table_3.V_MOBILE
     *
     * @mbg.generated
     */
    public void setvMobile(String vMobile) {
        this.vMobile = vMobile == null ? null : vMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table_3.V_EMAIL
     *
     * @return the value of test_table_3.V_EMAIL
     *
     * @mbg.generated
     */
    public String getvEmail() {
        return vEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table_3.V_EMAIL
     *
     * @param vEmail the value for test_table_3.V_EMAIL
     *
     * @mbg.generated
     */
    public void setvEmail(String vEmail) {
        this.vEmail = vEmail == null ? null : vEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table_3.V_MARITAL_STATUS_CD
     *
     * @return the value of test_table_3.V_MARITAL_STATUS_CD
     *
     * @mbg.generated
     */
    public String getvMaritalStatusCd() {
        return vMaritalStatusCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table_3.V_MARITAL_STATUS_CD
     *
     * @param vMaritalStatusCd the value for test_table_3.V_MARITAL_STATUS_CD
     *
     * @mbg.generated
     */
    public void setvMaritalStatusCd(String vMaritalStatusCd) {
        this.vMaritalStatusCd = vMaritalStatusCd == null ? null : vMaritalStatusCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table_3.D_BIRTHDAY
     *
     * @return the value of test_table_3.D_BIRTHDAY
     *
     * @mbg.generated
     */
    public Date getdBirthday() {
        return dBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table_3.D_BIRTHDAY
     *
     * @param dBirthday the value for test_table_3.D_BIRTHDAY
     *
     * @mbg.generated
     */
    public void setdBirthday(Date dBirthday) {
        this.dBirthday = dBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table_3
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", vCustId=").append(vCustId);
        sb.append(", vCustTypeCd=").append(vCustTypeCd);
        sb.append(", vInstCode=").append(vInstCode);
        sb.append(", vSrcCustRefCode=").append(vSrcCustRefCode);
        sb.append(", vFirstName=").append(vFirstName);
        sb.append(", vLastName=").append(vLastName);
        sb.append(", vSexCd=").append(vSexCd);
        sb.append(", vAddress=").append(vAddress);
        sb.append(", vCity=").append(vCity);
        sb.append(", vCountry=").append(vCountry);
        sb.append(", vPostcode=").append(vPostcode);
        sb.append(", vPhone=").append(vPhone);
        sb.append(", vMobile=").append(vMobile);
        sb.append(", vEmail=").append(vEmail);
        sb.append(", vMaritalStatusCd=").append(vMaritalStatusCd);
        sb.append(", dBirthday=").append(dBirthday);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * 生成文件头字符
     * @return
     */
    public static String generateFileHeader() {
        StringBuilder sb = new StringBuilder();
        sb.append("V_CUST_ID,");
        sb.append("V_CUST_TYPE_CD,");
        sb.append("V_INST_CODE,");
        sb.append("V_SRC_CUST_REF_CODE,");
        sb.append("V_FIRST_NAME,");
        sb.append("V_LAST_NAME,");
        sb.append("V_SEX_CD,");
        sb.append("V_ADDRESS,");
        sb.append("V_CITY,");
        sb.append("V_COUNTRY,");
        sb.append("V_POSTCODE,");
        sb.append("V_PHONE,");
        sb.append("V_MOBILE,");
        sb.append("V_EMAIL,");
        sb.append("V_MARITAL_STATUS_CD,");
        sb.append("D_BIRTHDAY");

        return sb.toString();
    }
}