package com.heiheipp.common.mbg.model;

import java.io.Serializable;

public class TestHtap2Rule001 implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_RULE_001.DTE
     *
     * @mbg.generated
     */
    private String dte;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_RULE_001.COD_CHK_RULE
     *
     * @mbg.generated
     */
    private String codChkRule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_RULE_001.NAM_CHK_RULE
     *
     * @mbg.generated
     */
    private String namChkRule;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_RULE_001.COD_PJT
     *
     * @mbg.generated
     */
    private String codPjt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_RULE_001.ID_SEQ
     *
     * @mbg.generated
     */
    private Integer idSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_RULE_001.COD_TBL
     *
     * @mbg.generated
     */
    private String codTbl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_RULE_001.COD_CHK_FLD
     *
     * @mbg.generated
     */
    private String codChkFld;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_RULE_001.NAM_CHK_FLD
     *
     * @mbg.generated
     */
    private String namChkFld;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_RULE_001.COD_RLN_TAB
     *
     * @mbg.generated
     */
    private String codRlnTab;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_RULE_001.NAM_RLN_TAB
     *
     * @mbg.generated
     */
    private String namRlnTab;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_RULE_001.TXT_CHK_TYP
     *
     * @mbg.generated
     */
    private String txtChkTyp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_RULE_001.TXT_CHK_CTEN
     *
     * @mbg.generated
     */
    private String txtChkCten;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_RULE_001.TXT_CHK_SQL
     *
     * @mbg.generated
     */
    private String txtChkSql;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_RULE_001.COD_WARN_TYP
     *
     * @mbg.generated
     */
    private String codWarnTyp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_RULE_001.DAT_ENABLE
     *
     * @mbg.generated
     */
    private String datEnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_RULE_001.DAT_DISABLE
     *
     * @mbg.generated
     */
    private String datDisable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_RULE_001.TXT_REMARK
     *
     * @mbg.generated
     */
    private String txtRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_RULE_001.ID_USER
     *
     * @mbg.generated
     */
    private String idUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_RULE_001.DTM_MATNC
     *
     * @mbg.generated
     */
    private String dtmMatnc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_RULE_001.RESERVE_FEILDA
     *
     * @mbg.generated
     */
    private String reserveFeilda;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_RULE_001.RESERVE_FEILDB
     *
     * @mbg.generated
     */
    private String reserveFeildb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_RULE_001.RESERVE_FEILDC
     *
     * @mbg.generated
     */
    private String reserveFeildc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TEST_HTAP2_RULE_001
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_RULE_001.DTE
     *
     * @return the value of TEST_HTAP2_RULE_001.DTE
     *
     * @mbg.generated
     */
    public String getDte() {
        return dte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_RULE_001.DTE
     *
     * @param dte the value for TEST_HTAP2_RULE_001.DTE
     *
     * @mbg.generated
     */
    public void setDte(String dte) {
        this.dte = dte == null ? null : dte.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_RULE_001.COD_CHK_RULE
     *
     * @return the value of TEST_HTAP2_RULE_001.COD_CHK_RULE
     *
     * @mbg.generated
     */
    public String getCodChkRule() {
        return codChkRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_RULE_001.COD_CHK_RULE
     *
     * @param codChkRule the value for TEST_HTAP2_RULE_001.COD_CHK_RULE
     *
     * @mbg.generated
     */
    public void setCodChkRule(String codChkRule) {
        this.codChkRule = codChkRule == null ? null : codChkRule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_RULE_001.NAM_CHK_RULE
     *
     * @return the value of TEST_HTAP2_RULE_001.NAM_CHK_RULE
     *
     * @mbg.generated
     */
    public String getNamChkRule() {
        return namChkRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_RULE_001.NAM_CHK_RULE
     *
     * @param namChkRule the value for TEST_HTAP2_RULE_001.NAM_CHK_RULE
     *
     * @mbg.generated
     */
    public void setNamChkRule(String namChkRule) {
        this.namChkRule = namChkRule == null ? null : namChkRule.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_RULE_001.COD_PJT
     *
     * @return the value of TEST_HTAP2_RULE_001.COD_PJT
     *
     * @mbg.generated
     */
    public String getCodPjt() {
        return codPjt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_RULE_001.COD_PJT
     *
     * @param codPjt the value for TEST_HTAP2_RULE_001.COD_PJT
     *
     * @mbg.generated
     */
    public void setCodPjt(String codPjt) {
        this.codPjt = codPjt == null ? null : codPjt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_RULE_001.ID_SEQ
     *
     * @return the value of TEST_HTAP2_RULE_001.ID_SEQ
     *
     * @mbg.generated
     */
    public Integer getIdSeq() {
        return idSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_RULE_001.ID_SEQ
     *
     * @param idSeq the value for TEST_HTAP2_RULE_001.ID_SEQ
     *
     * @mbg.generated
     */
    public void setIdSeq(Integer idSeq) {
        this.idSeq = idSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_RULE_001.COD_TBL
     *
     * @return the value of TEST_HTAP2_RULE_001.COD_TBL
     *
     * @mbg.generated
     */
    public String getCodTbl() {
        return codTbl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_RULE_001.COD_TBL
     *
     * @param codTbl the value for TEST_HTAP2_RULE_001.COD_TBL
     *
     * @mbg.generated
     */
    public void setCodTbl(String codTbl) {
        this.codTbl = codTbl == null ? null : codTbl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_RULE_001.COD_CHK_FLD
     *
     * @return the value of TEST_HTAP2_RULE_001.COD_CHK_FLD
     *
     * @mbg.generated
     */
    public String getCodChkFld() {
        return codChkFld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_RULE_001.COD_CHK_FLD
     *
     * @param codChkFld the value for TEST_HTAP2_RULE_001.COD_CHK_FLD
     *
     * @mbg.generated
     */
    public void setCodChkFld(String codChkFld) {
        this.codChkFld = codChkFld == null ? null : codChkFld.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_RULE_001.NAM_CHK_FLD
     *
     * @return the value of TEST_HTAP2_RULE_001.NAM_CHK_FLD
     *
     * @mbg.generated
     */
    public String getNamChkFld() {
        return namChkFld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_RULE_001.NAM_CHK_FLD
     *
     * @param namChkFld the value for TEST_HTAP2_RULE_001.NAM_CHK_FLD
     *
     * @mbg.generated
     */
    public void setNamChkFld(String namChkFld) {
        this.namChkFld = namChkFld == null ? null : namChkFld.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_RULE_001.COD_RLN_TAB
     *
     * @return the value of TEST_HTAP2_RULE_001.COD_RLN_TAB
     *
     * @mbg.generated
     */
    public String getCodRlnTab() {
        return codRlnTab;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_RULE_001.COD_RLN_TAB
     *
     * @param codRlnTab the value for TEST_HTAP2_RULE_001.COD_RLN_TAB
     *
     * @mbg.generated
     */
    public void setCodRlnTab(String codRlnTab) {
        this.codRlnTab = codRlnTab == null ? null : codRlnTab.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_RULE_001.NAM_RLN_TAB
     *
     * @return the value of TEST_HTAP2_RULE_001.NAM_RLN_TAB
     *
     * @mbg.generated
     */
    public String getNamRlnTab() {
        return namRlnTab;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_RULE_001.NAM_RLN_TAB
     *
     * @param namRlnTab the value for TEST_HTAP2_RULE_001.NAM_RLN_TAB
     *
     * @mbg.generated
     */
    public void setNamRlnTab(String namRlnTab) {
        this.namRlnTab = namRlnTab == null ? null : namRlnTab.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_RULE_001.TXT_CHK_TYP
     *
     * @return the value of TEST_HTAP2_RULE_001.TXT_CHK_TYP
     *
     * @mbg.generated
     */
    public String getTxtChkTyp() {
        return txtChkTyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_RULE_001.TXT_CHK_TYP
     *
     * @param txtChkTyp the value for TEST_HTAP2_RULE_001.TXT_CHK_TYP
     *
     * @mbg.generated
     */
    public void setTxtChkTyp(String txtChkTyp) {
        this.txtChkTyp = txtChkTyp == null ? null : txtChkTyp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_RULE_001.TXT_CHK_CTEN
     *
     * @return the value of TEST_HTAP2_RULE_001.TXT_CHK_CTEN
     *
     * @mbg.generated
     */
    public String getTxtChkCten() {
        return txtChkCten;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_RULE_001.TXT_CHK_CTEN
     *
     * @param txtChkCten the value for TEST_HTAP2_RULE_001.TXT_CHK_CTEN
     *
     * @mbg.generated
     */
    public void setTxtChkCten(String txtChkCten) {
        this.txtChkCten = txtChkCten == null ? null : txtChkCten.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_RULE_001.TXT_CHK_SQL
     *
     * @return the value of TEST_HTAP2_RULE_001.TXT_CHK_SQL
     *
     * @mbg.generated
     */
    public String getTxtChkSql() {
        return txtChkSql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_RULE_001.TXT_CHK_SQL
     *
     * @param txtChkSql the value for TEST_HTAP2_RULE_001.TXT_CHK_SQL
     *
     * @mbg.generated
     */
    public void setTxtChkSql(String txtChkSql) {
        this.txtChkSql = txtChkSql == null ? null : txtChkSql.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_RULE_001.COD_WARN_TYP
     *
     * @return the value of TEST_HTAP2_RULE_001.COD_WARN_TYP
     *
     * @mbg.generated
     */
    public String getCodWarnTyp() {
        return codWarnTyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_RULE_001.COD_WARN_TYP
     *
     * @param codWarnTyp the value for TEST_HTAP2_RULE_001.COD_WARN_TYP
     *
     * @mbg.generated
     */
    public void setCodWarnTyp(String codWarnTyp) {
        this.codWarnTyp = codWarnTyp == null ? null : codWarnTyp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_RULE_001.DAT_ENABLE
     *
     * @return the value of TEST_HTAP2_RULE_001.DAT_ENABLE
     *
     * @mbg.generated
     */
    public String getDatEnable() {
        return datEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_RULE_001.DAT_ENABLE
     *
     * @param datEnable the value for TEST_HTAP2_RULE_001.DAT_ENABLE
     *
     * @mbg.generated
     */
    public void setDatEnable(String datEnable) {
        this.datEnable = datEnable == null ? null : datEnable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_RULE_001.DAT_DISABLE
     *
     * @return the value of TEST_HTAP2_RULE_001.DAT_DISABLE
     *
     * @mbg.generated
     */
    public String getDatDisable() {
        return datDisable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_RULE_001.DAT_DISABLE
     *
     * @param datDisable the value for TEST_HTAP2_RULE_001.DAT_DISABLE
     *
     * @mbg.generated
     */
    public void setDatDisable(String datDisable) {
        this.datDisable = datDisable == null ? null : datDisable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_RULE_001.TXT_REMARK
     *
     * @return the value of TEST_HTAP2_RULE_001.TXT_REMARK
     *
     * @mbg.generated
     */
    public String getTxtRemark() {
        return txtRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_RULE_001.TXT_REMARK
     *
     * @param txtRemark the value for TEST_HTAP2_RULE_001.TXT_REMARK
     *
     * @mbg.generated
     */
    public void setTxtRemark(String txtRemark) {
        this.txtRemark = txtRemark == null ? null : txtRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_RULE_001.ID_USER
     *
     * @return the value of TEST_HTAP2_RULE_001.ID_USER
     *
     * @mbg.generated
     */
    public String getIdUser() {
        return idUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_RULE_001.ID_USER
     *
     * @param idUser the value for TEST_HTAP2_RULE_001.ID_USER
     *
     * @mbg.generated
     */
    public void setIdUser(String idUser) {
        this.idUser = idUser == null ? null : idUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_RULE_001.DTM_MATNC
     *
     * @return the value of TEST_HTAP2_RULE_001.DTM_MATNC
     *
     * @mbg.generated
     */
    public String getDtmMatnc() {
        return dtmMatnc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_RULE_001.DTM_MATNC
     *
     * @param dtmMatnc the value for TEST_HTAP2_RULE_001.DTM_MATNC
     *
     * @mbg.generated
     */
    public void setDtmMatnc(String dtmMatnc) {
        this.dtmMatnc = dtmMatnc == null ? null : dtmMatnc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_RULE_001.RESERVE_FEILDA
     *
     * @return the value of TEST_HTAP2_RULE_001.RESERVE_FEILDA
     *
     * @mbg.generated
     */
    public String getReserveFeilda() {
        return reserveFeilda;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_RULE_001.RESERVE_FEILDA
     *
     * @param reserveFeilda the value for TEST_HTAP2_RULE_001.RESERVE_FEILDA
     *
     * @mbg.generated
     */
    public void setReserveFeilda(String reserveFeilda) {
        this.reserveFeilda = reserveFeilda == null ? null : reserveFeilda.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_RULE_001.RESERVE_FEILDB
     *
     * @return the value of TEST_HTAP2_RULE_001.RESERVE_FEILDB
     *
     * @mbg.generated
     */
    public String getReserveFeildb() {
        return reserveFeildb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_RULE_001.RESERVE_FEILDB
     *
     * @param reserveFeildb the value for TEST_HTAP2_RULE_001.RESERVE_FEILDB
     *
     * @mbg.generated
     */
    public void setReserveFeildb(String reserveFeildb) {
        this.reserveFeildb = reserveFeildb == null ? null : reserveFeildb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_RULE_001.RESERVE_FEILDC
     *
     * @return the value of TEST_HTAP2_RULE_001.RESERVE_FEILDC
     *
     * @mbg.generated
     */
    public String getReserveFeildc() {
        return reserveFeildc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_RULE_001.RESERVE_FEILDC
     *
     * @param reserveFeildc the value for TEST_HTAP2_RULE_001.RESERVE_FEILDC
     *
     * @mbg.generated
     */
    public void setReserveFeildc(String reserveFeildc) {
        this.reserveFeildc = reserveFeildc == null ? null : reserveFeildc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST_HTAP2_RULE_001
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dte=").append(dte);
        sb.append(", codChkRule=").append(codChkRule);
        sb.append(", namChkRule=").append(namChkRule);
        sb.append(", codPjt=").append(codPjt);
        sb.append(", idSeq=").append(idSeq);
        sb.append(", codTbl=").append(codTbl);
        sb.append(", codChkFld=").append(codChkFld);
        sb.append(", namChkFld=").append(namChkFld);
        sb.append(", codRlnTab=").append(codRlnTab);
        sb.append(", namRlnTab=").append(namRlnTab);
        sb.append(", txtChkTyp=").append(txtChkTyp);
        sb.append(", txtChkCten=").append(txtChkCten);
        sb.append(", txtChkSql=").append(txtChkSql);
        sb.append(", codWarnTyp=").append(codWarnTyp);
        sb.append(", datEnable=").append(datEnable);
        sb.append(", datDisable=").append(datDisable);
        sb.append(", txtRemark=").append(txtRemark);
        sb.append(", idUser=").append(idUser);
        sb.append(", dtmMatnc=").append(dtmMatnc);
        sb.append(", reserveFeilda=").append(reserveFeilda);
        sb.append(", reserveFeildb=").append(reserveFeildb);
        sb.append(", reserveFeildc=").append(reserveFeildc);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}