package com.heiheipp.common.mbg.model;

import java.io.Serializable;
import java.util.Date;

public class TestTable6 extends BaseModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table_6.V_CARD_APP_ID
     *
     * @mbg.generated
     */
    private String vCardAppId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table_6.N_CARD_APP_ISSUE_ID
     *
     * @mbg.generated
     */
    private Integer nCardAppIssueId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table_6.V_ACCOUNT_NUMBER
     *
     * @mbg.generated
     */
    private String vAccountNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table_6.V_INST_CODE
     *
     * @mbg.generated
     */
    private String vInstCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table_6.V_CARD_ID
     *
     * @mbg.generated
     */
    private String vCardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table_6.N_CARD_ISSUE_ID
     *
     * @mbg.generated
     */
    private Integer nCardIssueId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table_6.V_CARD_NUMBER
     *
     * @mbg.generated
     */
    private String vCardNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table_6.D_START_DATE
     *
     * @mbg.generated
     */
    private Date dStartDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_table_6.D_END_DATE
     *
     * @mbg.generated
     */
    private Date dEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_table_6
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table_6.V_CARD_APP_ID
     *
     * @return the value of test_table_6.V_CARD_APP_ID
     *
     * @mbg.generated
     */
    public String getvCardAppId() {
        return vCardAppId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table_6.V_CARD_APP_ID
     *
     * @param vCardAppId the value for test_table_6.V_CARD_APP_ID
     *
     * @mbg.generated
     */
    public void setvCardAppId(String vCardAppId) {
        this.vCardAppId = vCardAppId == null ? null : vCardAppId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table_6.N_CARD_APP_ISSUE_ID
     *
     * @return the value of test_table_6.N_CARD_APP_ISSUE_ID
     *
     * @mbg.generated
     */
    public Integer getnCardAppIssueId() {
        return nCardAppIssueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table_6.N_CARD_APP_ISSUE_ID
     *
     * @param nCardAppIssueId the value for test_table_6.N_CARD_APP_ISSUE_ID
     *
     * @mbg.generated
     */
    public void setnCardAppIssueId(Integer nCardAppIssueId) {
        this.nCardAppIssueId = nCardAppIssueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table_6.V_ACCOUNT_NUMBER
     *
     * @return the value of test_table_6.V_ACCOUNT_NUMBER
     *
     * @mbg.generated
     */
    public String getvAccountNumber() {
        return vAccountNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table_6.V_ACCOUNT_NUMBER
     *
     * @param vAccountNumber the value for test_table_6.V_ACCOUNT_NUMBER
     *
     * @mbg.generated
     */
    public void setvAccountNumber(String vAccountNumber) {
        this.vAccountNumber = vAccountNumber == null ? null : vAccountNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table_6.V_INST_CODE
     *
     * @return the value of test_table_6.V_INST_CODE
     *
     * @mbg.generated
     */
    public String getvInstCode() {
        return vInstCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table_6.V_INST_CODE
     *
     * @param vInstCode the value for test_table_6.V_INST_CODE
     *
     * @mbg.generated
     */
    public void setvInstCode(String vInstCode) {
        this.vInstCode = vInstCode == null ? null : vInstCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table_6.V_CARD_ID
     *
     * @return the value of test_table_6.V_CARD_ID
     *
     * @mbg.generated
     */
    public String getvCardId() {
        return vCardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table_6.V_CARD_ID
     *
     * @param vCardId the value for test_table_6.V_CARD_ID
     *
     * @mbg.generated
     */
    public void setvCardId(String vCardId) {
        this.vCardId = vCardId == null ? null : vCardId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table_6.N_CARD_ISSUE_ID
     *
     * @return the value of test_table_6.N_CARD_ISSUE_ID
     *
     * @mbg.generated
     */
    public Integer getnCardIssueId() {
        return nCardIssueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table_6.N_CARD_ISSUE_ID
     *
     * @param nCardIssueId the value for test_table_6.N_CARD_ISSUE_ID
     *
     * @mbg.generated
     */
    public void setnCardIssueId(Integer nCardIssueId) {
        this.nCardIssueId = nCardIssueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table_6.V_CARD_NUMBER
     *
     * @return the value of test_table_6.V_CARD_NUMBER
     *
     * @mbg.generated
     */
    public String getvCardNumber() {
        return vCardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table_6.V_CARD_NUMBER
     *
     * @param vCardNumber the value for test_table_6.V_CARD_NUMBER
     *
     * @mbg.generated
     */
    public void setvCardNumber(String vCardNumber) {
        this.vCardNumber = vCardNumber == null ? null : vCardNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table_6.D_START_DATE
     *
     * @return the value of test_table_6.D_START_DATE
     *
     * @mbg.generated
     */
    public Date getdStartDate() {
        return dStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table_6.D_START_DATE
     *
     * @param dStartDate the value for test_table_6.D_START_DATE
     *
     * @mbg.generated
     */
    public void setdStartDate(Date dStartDate) {
        this.dStartDate = dStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_table_6.D_END_DATE
     *
     * @return the value of test_table_6.D_END_DATE
     *
     * @mbg.generated
     */
    public Date getdEndDate() {
        return dEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_table_6.D_END_DATE
     *
     * @param dEndDate the value for test_table_6.D_END_DATE
     *
     * @mbg.generated
     */
    public void setdEndDate(Date dEndDate) {
        this.dEndDate = dEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table_6
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", vCardAppId=").append(vCardAppId);
        sb.append(", nCardAppIssueId=").append(nCardAppIssueId);
        sb.append(", vAccountNumber=").append(vAccountNumber);
        sb.append(", vInstCode=").append(vInstCode);
        sb.append(", vCardId=").append(vCardId);
        sb.append(", nCardIssueId=").append(nCardIssueId);
        sb.append(", vCardNumber=").append(vCardNumber);
        sb.append(", dStartDate=").append(dStartDate);
        sb.append(", dEndDate=").append(dEndDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * 生成文件头字符
     * @return
     */
    public static String generateFileHeader() {
        StringBuilder sb = new StringBuilder();
        sb.append("V_CARD_APP_ID,");
        sb.append("N_CARD_APP_ISSUE_ID,");
        sb.append("V_ACCOUNT_NUMBER,");
        sb.append("V_INST_CODE,");
        sb.append("V_CARD_ID,");
        sb.append("N_CARD_ISSUE_ID,");
        sb.append("V_CARD_NUMBER,");
        sb.append("D_START_DATE,");
        sb.append("D_END_DATE");

        return sb.toString();
    }
}