package com.heiheipp.common.mbg.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class TestHtap2Bb001 implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_BB_001.ZDY_ZJ
     *
     * @mbg.generated
     */
    private String zdyZj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_BB_001.DTE
     *
     * @mbg.generated
     */
    private String dte;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_BB_001.JYXLH
     *
     * @mbg.generated
     */
    private String jyxlh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_BB_001.JRXKZH
     *
     * @mbg.generated
     */
    private String jrxkzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_BB_001.NBJGH
     *
     * @mbg.generated
     */
    private String nbjgh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_BB_001.YWBLJGH
     *
     * @mbg.generated
     */
    private String ywbljgh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_BB_001.YHJGMC
     *
     * @mbg.generated
     */
    private String yhjgmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_BB_001.MXKMBH
     *
     * @mbg.generated
     */
    private String mxkmbh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_BB_001.MXKMMC
     *
     * @mbg.generated
     */
    private String mxkmmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_BB_001.KHTYBH
     *
     * @mbg.generated
     */
    private String khtybh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_BB_001.ZHMC
     *
     * @mbg.generated
     */
    private String zhmc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_BB_001.ZJLB
     *
     * @mbg.generated
     */
    private String zjlb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_BB_001.ZJHM
     *
     * @mbg.generated
     */
    private String zjhm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_BB_001.GRCKZH
     *
     * @mbg.generated
     */
    private String grckzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_BB_001.WBZH
     *
     * @mbg.generated
     */
    private String wbzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_BB_001.JYLX
     *
     * @mbg.generated
     */
    private String jylx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_BB_001.JYJDBZ
     *
     * @mbg.generated
     */
    private String jyjdbz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_BB_001.HXJYRQ
     *
     * @mbg.generated
     */
    private String hxjyrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_BB_001.HXJYSJ
     *
     * @mbg.generated
     */
    private String hxjysj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_BB_001.BZ
     *
     * @mbg.generated
     */
    private String bz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_BB_001.JYJE
     *
     * @mbg.generated
     */
    private BigDecimal jyje;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_BB_001.ZHYE
     *
     * @mbg.generated
     */
    private BigDecimal zhye;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_BB_001.DFZH
     *
     * @mbg.generated
     */
    private String dfzh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_BB_001.DFHM
     *
     * @mbg.generated
     */
    private String dfhm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_BB_001.DFXH
     *
     * @mbg.generated
     */
    private String dfxh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_BB_001.DFXM
     *
     * @mbg.generated
     */
    private String dfxm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_BB_001.ZY
     *
     * @mbg.generated
     */
    private String zy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_BB_001.FY
     *
     * @mbg.generated
     */
    private String fy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_BB_001.CBMBZ
     *
     * @mbg.generated
     */
    private String cbmbz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_BB_001.XZBZ
     *
     * @mbg.generated
     */
    private String xzbz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_BB_001.JYQD
     *
     * @mbg.generated
     */
    private String jyqd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_BB_001.IPDZ
     *
     * @mbg.generated
     */
    private String ipdz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_BB_001.MACDZ
     *
     * @mbg.generated
     */
    private String macdz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_BB_001.DBRXM
     *
     * @mbg.generated
     */
    private String dbrxm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_BB_001.DBRZJLB
     *
     * @mbg.generated
     */
    private String dbrzjlb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_BB_001.DBRZJHM
     *
     * @mbg.generated
     */
    private String dbrzjhm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_BB_001.JYGYH
     *
     * @mbg.generated
     */
    private String jygyh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_BB_001.SQGYH
     *
     * @mbg.generated
     */
    private String sqgyh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_BB_001.BBZ
     *
     * @mbg.generated
     */
    private String bbz;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_BB_001.CJRQ
     *
     * @mbg.generated
     */
    private String cjrq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST_HTAP2_BB_001.GSFZJG
     *
     * @mbg.generated
     */
    private String gsfzjg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table TEST_HTAP2_BB_001
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_BB_001.ZDY_ZJ
     *
     * @return the value of TEST_HTAP2_BB_001.ZDY_ZJ
     *
     * @mbg.generated
     */
    public String getZdyZj() {
        return zdyZj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_BB_001.ZDY_ZJ
     *
     * @param zdyZj the value for TEST_HTAP2_BB_001.ZDY_ZJ
     *
     * @mbg.generated
     */
    public void setZdyZj(String zdyZj) {
        this.zdyZj = zdyZj == null ? null : zdyZj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_BB_001.DTE
     *
     * @return the value of TEST_HTAP2_BB_001.DTE
     *
     * @mbg.generated
     */
    public String getDte() {
        return dte;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_BB_001.DTE
     *
     * @param dte the value for TEST_HTAP2_BB_001.DTE
     *
     * @mbg.generated
     */
    public void setDte(String dte) {
        this.dte = dte == null ? null : dte.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_BB_001.JYXLH
     *
     * @return the value of TEST_HTAP2_BB_001.JYXLH
     *
     * @mbg.generated
     */
    public String getJyxlh() {
        return jyxlh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_BB_001.JYXLH
     *
     * @param jyxlh the value for TEST_HTAP2_BB_001.JYXLH
     *
     * @mbg.generated
     */
    public void setJyxlh(String jyxlh) {
        this.jyxlh = jyxlh == null ? null : jyxlh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_BB_001.JRXKZH
     *
     * @return the value of TEST_HTAP2_BB_001.JRXKZH
     *
     * @mbg.generated
     */
    public String getJrxkzh() {
        return jrxkzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_BB_001.JRXKZH
     *
     * @param jrxkzh the value for TEST_HTAP2_BB_001.JRXKZH
     *
     * @mbg.generated
     */
    public void setJrxkzh(String jrxkzh) {
        this.jrxkzh = jrxkzh == null ? null : jrxkzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_BB_001.NBJGH
     *
     * @return the value of TEST_HTAP2_BB_001.NBJGH
     *
     * @mbg.generated
     */
    public String getNbjgh() {
        return nbjgh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_BB_001.NBJGH
     *
     * @param nbjgh the value for TEST_HTAP2_BB_001.NBJGH
     *
     * @mbg.generated
     */
    public void setNbjgh(String nbjgh) {
        this.nbjgh = nbjgh == null ? null : nbjgh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_BB_001.YWBLJGH
     *
     * @return the value of TEST_HTAP2_BB_001.YWBLJGH
     *
     * @mbg.generated
     */
    public String getYwbljgh() {
        return ywbljgh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_BB_001.YWBLJGH
     *
     * @param ywbljgh the value for TEST_HTAP2_BB_001.YWBLJGH
     *
     * @mbg.generated
     */
    public void setYwbljgh(String ywbljgh) {
        this.ywbljgh = ywbljgh == null ? null : ywbljgh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_BB_001.YHJGMC
     *
     * @return the value of TEST_HTAP2_BB_001.YHJGMC
     *
     * @mbg.generated
     */
    public String getYhjgmc() {
        return yhjgmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_BB_001.YHJGMC
     *
     * @param yhjgmc the value for TEST_HTAP2_BB_001.YHJGMC
     *
     * @mbg.generated
     */
    public void setYhjgmc(String yhjgmc) {
        this.yhjgmc = yhjgmc == null ? null : yhjgmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_BB_001.MXKMBH
     *
     * @return the value of TEST_HTAP2_BB_001.MXKMBH
     *
     * @mbg.generated
     */
    public String getMxkmbh() {
        return mxkmbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_BB_001.MXKMBH
     *
     * @param mxkmbh the value for TEST_HTAP2_BB_001.MXKMBH
     *
     * @mbg.generated
     */
    public void setMxkmbh(String mxkmbh) {
        this.mxkmbh = mxkmbh == null ? null : mxkmbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_BB_001.MXKMMC
     *
     * @return the value of TEST_HTAP2_BB_001.MXKMMC
     *
     * @mbg.generated
     */
    public String getMxkmmc() {
        return mxkmmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_BB_001.MXKMMC
     *
     * @param mxkmmc the value for TEST_HTAP2_BB_001.MXKMMC
     *
     * @mbg.generated
     */
    public void setMxkmmc(String mxkmmc) {
        this.mxkmmc = mxkmmc == null ? null : mxkmmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_BB_001.KHTYBH
     *
     * @return the value of TEST_HTAP2_BB_001.KHTYBH
     *
     * @mbg.generated
     */
    public String getKhtybh() {
        return khtybh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_BB_001.KHTYBH
     *
     * @param khtybh the value for TEST_HTAP2_BB_001.KHTYBH
     *
     * @mbg.generated
     */
    public void setKhtybh(String khtybh) {
        this.khtybh = khtybh == null ? null : khtybh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_BB_001.ZHMC
     *
     * @return the value of TEST_HTAP2_BB_001.ZHMC
     *
     * @mbg.generated
     */
    public String getZhmc() {
        return zhmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_BB_001.ZHMC
     *
     * @param zhmc the value for TEST_HTAP2_BB_001.ZHMC
     *
     * @mbg.generated
     */
    public void setZhmc(String zhmc) {
        this.zhmc = zhmc == null ? null : zhmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_BB_001.ZJLB
     *
     * @return the value of TEST_HTAP2_BB_001.ZJLB
     *
     * @mbg.generated
     */
    public String getZjlb() {
        return zjlb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_BB_001.ZJLB
     *
     * @param zjlb the value for TEST_HTAP2_BB_001.ZJLB
     *
     * @mbg.generated
     */
    public void setZjlb(String zjlb) {
        this.zjlb = zjlb == null ? null : zjlb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_BB_001.ZJHM
     *
     * @return the value of TEST_HTAP2_BB_001.ZJHM
     *
     * @mbg.generated
     */
    public String getZjhm() {
        return zjhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_BB_001.ZJHM
     *
     * @param zjhm the value for TEST_HTAP2_BB_001.ZJHM
     *
     * @mbg.generated
     */
    public void setZjhm(String zjhm) {
        this.zjhm = zjhm == null ? null : zjhm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_BB_001.GRCKZH
     *
     * @return the value of TEST_HTAP2_BB_001.GRCKZH
     *
     * @mbg.generated
     */
    public String getGrckzh() {
        return grckzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_BB_001.GRCKZH
     *
     * @param grckzh the value for TEST_HTAP2_BB_001.GRCKZH
     *
     * @mbg.generated
     */
    public void setGrckzh(String grckzh) {
        this.grckzh = grckzh == null ? null : grckzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_BB_001.WBZH
     *
     * @return the value of TEST_HTAP2_BB_001.WBZH
     *
     * @mbg.generated
     */
    public String getWbzh() {
        return wbzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_BB_001.WBZH
     *
     * @param wbzh the value for TEST_HTAP2_BB_001.WBZH
     *
     * @mbg.generated
     */
    public void setWbzh(String wbzh) {
        this.wbzh = wbzh == null ? null : wbzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_BB_001.JYLX
     *
     * @return the value of TEST_HTAP2_BB_001.JYLX
     *
     * @mbg.generated
     */
    public String getJylx() {
        return jylx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_BB_001.JYLX
     *
     * @param jylx the value for TEST_HTAP2_BB_001.JYLX
     *
     * @mbg.generated
     */
    public void setJylx(String jylx) {
        this.jylx = jylx == null ? null : jylx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_BB_001.JYJDBZ
     *
     * @return the value of TEST_HTAP2_BB_001.JYJDBZ
     *
     * @mbg.generated
     */
    public String getJyjdbz() {
        return jyjdbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_BB_001.JYJDBZ
     *
     * @param jyjdbz the value for TEST_HTAP2_BB_001.JYJDBZ
     *
     * @mbg.generated
     */
    public void setJyjdbz(String jyjdbz) {
        this.jyjdbz = jyjdbz == null ? null : jyjdbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_BB_001.HXJYRQ
     *
     * @return the value of TEST_HTAP2_BB_001.HXJYRQ
     *
     * @mbg.generated
     */
    public String getHxjyrq() {
        return hxjyrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_BB_001.HXJYRQ
     *
     * @param hxjyrq the value for TEST_HTAP2_BB_001.HXJYRQ
     *
     * @mbg.generated
     */
    public void setHxjyrq(String hxjyrq) {
        this.hxjyrq = hxjyrq == null ? null : hxjyrq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_BB_001.HXJYSJ
     *
     * @return the value of TEST_HTAP2_BB_001.HXJYSJ
     *
     * @mbg.generated
     */
    public String getHxjysj() {
        return hxjysj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_BB_001.HXJYSJ
     *
     * @param hxjysj the value for TEST_HTAP2_BB_001.HXJYSJ
     *
     * @mbg.generated
     */
    public void setHxjysj(String hxjysj) {
        this.hxjysj = hxjysj == null ? null : hxjysj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_BB_001.BZ
     *
     * @return the value of TEST_HTAP2_BB_001.BZ
     *
     * @mbg.generated
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_BB_001.BZ
     *
     * @param bz the value for TEST_HTAP2_BB_001.BZ
     *
     * @mbg.generated
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_BB_001.JYJE
     *
     * @return the value of TEST_HTAP2_BB_001.JYJE
     *
     * @mbg.generated
     */
    public BigDecimal getJyje() {
        return jyje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_BB_001.JYJE
     *
     * @param jyje the value for TEST_HTAP2_BB_001.JYJE
     *
     * @mbg.generated
     */
    public void setJyje(BigDecimal jyje) {
        this.jyje = jyje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_BB_001.ZHYE
     *
     * @return the value of TEST_HTAP2_BB_001.ZHYE
     *
     * @mbg.generated
     */
    public BigDecimal getZhye() {
        return zhye;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_BB_001.ZHYE
     *
     * @param zhye the value for TEST_HTAP2_BB_001.ZHYE
     *
     * @mbg.generated
     */
    public void setZhye(BigDecimal zhye) {
        this.zhye = zhye;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_BB_001.DFZH
     *
     * @return the value of TEST_HTAP2_BB_001.DFZH
     *
     * @mbg.generated
     */
    public String getDfzh() {
        return dfzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_BB_001.DFZH
     *
     * @param dfzh the value for TEST_HTAP2_BB_001.DFZH
     *
     * @mbg.generated
     */
    public void setDfzh(String dfzh) {
        this.dfzh = dfzh == null ? null : dfzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_BB_001.DFHM
     *
     * @return the value of TEST_HTAP2_BB_001.DFHM
     *
     * @mbg.generated
     */
    public String getDfhm() {
        return dfhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_BB_001.DFHM
     *
     * @param dfhm the value for TEST_HTAP2_BB_001.DFHM
     *
     * @mbg.generated
     */
    public void setDfhm(String dfhm) {
        this.dfhm = dfhm == null ? null : dfhm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_BB_001.DFXH
     *
     * @return the value of TEST_HTAP2_BB_001.DFXH
     *
     * @mbg.generated
     */
    public String getDfxh() {
        return dfxh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_BB_001.DFXH
     *
     * @param dfxh the value for TEST_HTAP2_BB_001.DFXH
     *
     * @mbg.generated
     */
    public void setDfxh(String dfxh) {
        this.dfxh = dfxh == null ? null : dfxh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_BB_001.DFXM
     *
     * @return the value of TEST_HTAP2_BB_001.DFXM
     *
     * @mbg.generated
     */
    public String getDfxm() {
        return dfxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_BB_001.DFXM
     *
     * @param dfxm the value for TEST_HTAP2_BB_001.DFXM
     *
     * @mbg.generated
     */
    public void setDfxm(String dfxm) {
        this.dfxm = dfxm == null ? null : dfxm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_BB_001.ZY
     *
     * @return the value of TEST_HTAP2_BB_001.ZY
     *
     * @mbg.generated
     */
    public String getZy() {
        return zy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_BB_001.ZY
     *
     * @param zy the value for TEST_HTAP2_BB_001.ZY
     *
     * @mbg.generated
     */
    public void setZy(String zy) {
        this.zy = zy == null ? null : zy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_BB_001.FY
     *
     * @return the value of TEST_HTAP2_BB_001.FY
     *
     * @mbg.generated
     */
    public String getFy() {
        return fy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_BB_001.FY
     *
     * @param fy the value for TEST_HTAP2_BB_001.FY
     *
     * @mbg.generated
     */
    public void setFy(String fy) {
        this.fy = fy == null ? null : fy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_BB_001.CBMBZ
     *
     * @return the value of TEST_HTAP2_BB_001.CBMBZ
     *
     * @mbg.generated
     */
    public String getCbmbz() {
        return cbmbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_BB_001.CBMBZ
     *
     * @param cbmbz the value for TEST_HTAP2_BB_001.CBMBZ
     *
     * @mbg.generated
     */
    public void setCbmbz(String cbmbz) {
        this.cbmbz = cbmbz == null ? null : cbmbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_BB_001.XZBZ
     *
     * @return the value of TEST_HTAP2_BB_001.XZBZ
     *
     * @mbg.generated
     */
    public String getXzbz() {
        return xzbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_BB_001.XZBZ
     *
     * @param xzbz the value for TEST_HTAP2_BB_001.XZBZ
     *
     * @mbg.generated
     */
    public void setXzbz(String xzbz) {
        this.xzbz = xzbz == null ? null : xzbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_BB_001.JYQD
     *
     * @return the value of TEST_HTAP2_BB_001.JYQD
     *
     * @mbg.generated
     */
    public String getJyqd() {
        return jyqd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_BB_001.JYQD
     *
     * @param jyqd the value for TEST_HTAP2_BB_001.JYQD
     *
     * @mbg.generated
     */
    public void setJyqd(String jyqd) {
        this.jyqd = jyqd == null ? null : jyqd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_BB_001.IPDZ
     *
     * @return the value of TEST_HTAP2_BB_001.IPDZ
     *
     * @mbg.generated
     */
    public String getIpdz() {
        return ipdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_BB_001.IPDZ
     *
     * @param ipdz the value for TEST_HTAP2_BB_001.IPDZ
     *
     * @mbg.generated
     */
    public void setIpdz(String ipdz) {
        this.ipdz = ipdz == null ? null : ipdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_BB_001.MACDZ
     *
     * @return the value of TEST_HTAP2_BB_001.MACDZ
     *
     * @mbg.generated
     */
    public String getMacdz() {
        return macdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_BB_001.MACDZ
     *
     * @param macdz the value for TEST_HTAP2_BB_001.MACDZ
     *
     * @mbg.generated
     */
    public void setMacdz(String macdz) {
        this.macdz = macdz == null ? null : macdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_BB_001.DBRXM
     *
     * @return the value of TEST_HTAP2_BB_001.DBRXM
     *
     * @mbg.generated
     */
    public String getDbrxm() {
        return dbrxm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_BB_001.DBRXM
     *
     * @param dbrxm the value for TEST_HTAP2_BB_001.DBRXM
     *
     * @mbg.generated
     */
    public void setDbrxm(String dbrxm) {
        this.dbrxm = dbrxm == null ? null : dbrxm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_BB_001.DBRZJLB
     *
     * @return the value of TEST_HTAP2_BB_001.DBRZJLB
     *
     * @mbg.generated
     */
    public String getDbrzjlb() {
        return dbrzjlb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_BB_001.DBRZJLB
     *
     * @param dbrzjlb the value for TEST_HTAP2_BB_001.DBRZJLB
     *
     * @mbg.generated
     */
    public void setDbrzjlb(String dbrzjlb) {
        this.dbrzjlb = dbrzjlb == null ? null : dbrzjlb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_BB_001.DBRZJHM
     *
     * @return the value of TEST_HTAP2_BB_001.DBRZJHM
     *
     * @mbg.generated
     */
    public String getDbrzjhm() {
        return dbrzjhm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_BB_001.DBRZJHM
     *
     * @param dbrzjhm the value for TEST_HTAP2_BB_001.DBRZJHM
     *
     * @mbg.generated
     */
    public void setDbrzjhm(String dbrzjhm) {
        this.dbrzjhm = dbrzjhm == null ? null : dbrzjhm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_BB_001.JYGYH
     *
     * @return the value of TEST_HTAP2_BB_001.JYGYH
     *
     * @mbg.generated
     */
    public String getJygyh() {
        return jygyh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_BB_001.JYGYH
     *
     * @param jygyh the value for TEST_HTAP2_BB_001.JYGYH
     *
     * @mbg.generated
     */
    public void setJygyh(String jygyh) {
        this.jygyh = jygyh == null ? null : jygyh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_BB_001.SQGYH
     *
     * @return the value of TEST_HTAP2_BB_001.SQGYH
     *
     * @mbg.generated
     */
    public String getSqgyh() {
        return sqgyh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_BB_001.SQGYH
     *
     * @param sqgyh the value for TEST_HTAP2_BB_001.SQGYH
     *
     * @mbg.generated
     */
    public void setSqgyh(String sqgyh) {
        this.sqgyh = sqgyh == null ? null : sqgyh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_BB_001.BBZ
     *
     * @return the value of TEST_HTAP2_BB_001.BBZ
     *
     * @mbg.generated
     */
    public String getBbz() {
        return bbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_BB_001.BBZ
     *
     * @param bbz the value for TEST_HTAP2_BB_001.BBZ
     *
     * @mbg.generated
     */
    public void setBbz(String bbz) {
        this.bbz = bbz == null ? null : bbz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_BB_001.CJRQ
     *
     * @return the value of TEST_HTAP2_BB_001.CJRQ
     *
     * @mbg.generated
     */
    public String getCjrq() {
        return cjrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_BB_001.CJRQ
     *
     * @param cjrq the value for TEST_HTAP2_BB_001.CJRQ
     *
     * @mbg.generated
     */
    public void setCjrq(String cjrq) {
        this.cjrq = cjrq == null ? null : cjrq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST_HTAP2_BB_001.GSFZJG
     *
     * @return the value of TEST_HTAP2_BB_001.GSFZJG
     *
     * @mbg.generated
     */
    public String getGsfzjg() {
        return gsfzjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST_HTAP2_BB_001.GSFZJG
     *
     * @param gsfzjg the value for TEST_HTAP2_BB_001.GSFZJG
     *
     * @mbg.generated
     */
    public void setGsfzjg(String gsfzjg) {
        this.gsfzjg = gsfzjg == null ? null : gsfzjg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST_HTAP2_BB_001
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", zdyZj=").append(zdyZj);
        sb.append(", dte=").append(dte);
        sb.append(", jyxlh=").append(jyxlh);
        sb.append(", jrxkzh=").append(jrxkzh);
        sb.append(", nbjgh=").append(nbjgh);
        sb.append(", ywbljgh=").append(ywbljgh);
        sb.append(", yhjgmc=").append(yhjgmc);
        sb.append(", mxkmbh=").append(mxkmbh);
        sb.append(", mxkmmc=").append(mxkmmc);
        sb.append(", khtybh=").append(khtybh);
        sb.append(", zhmc=").append(zhmc);
        sb.append(", zjlb=").append(zjlb);
        sb.append(", zjhm=").append(zjhm);
        sb.append(", grckzh=").append(grckzh);
        sb.append(", wbzh=").append(wbzh);
        sb.append(", jylx=").append(jylx);
        sb.append(", jyjdbz=").append(jyjdbz);
        sb.append(", hxjyrq=").append(hxjyrq);
        sb.append(", hxjysj=").append(hxjysj);
        sb.append(", bz=").append(bz);
        sb.append(", jyje=").append(jyje);
        sb.append(", zhye=").append(zhye);
        sb.append(", dfzh=").append(dfzh);
        sb.append(", dfhm=").append(dfhm);
        sb.append(", dfxh=").append(dfxh);
        sb.append(", dfxm=").append(dfxm);
        sb.append(", zy=").append(zy);
        sb.append(", fy=").append(fy);
        sb.append(", cbmbz=").append(cbmbz);
        sb.append(", xzbz=").append(xzbz);
        sb.append(", jyqd=").append(jyqd);
        sb.append(", ipdz=").append(ipdz);
        sb.append(", macdz=").append(macdz);
        sb.append(", dbrxm=").append(dbrxm);
        sb.append(", dbrzjlb=").append(dbrzjlb);
        sb.append(", dbrzjhm=").append(dbrzjhm);
        sb.append(", jygyh=").append(jygyh);
        sb.append(", sqgyh=").append(sqgyh);
        sb.append(", bbz=").append(bbz);
        sb.append(", cjrq=").append(cjrq);
        sb.append(", gsfzjg=").append(gsfzjg);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}