package com.heiheipp.common.mbg.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class ZdjTable2 extends BaseModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zdj_table2.BRANCH
     *
     * @mbg.generated
     */
    private String branch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zdj_table2.ACCT_NO
     *
     * @mbg.generated
     */
    private String acctNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zdj_table2.CUST_NO
     *
     * @mbg.generated
     */
    private String custNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zdj_table2.PRODUCT_NO
     *
     * @mbg.generated
     */
    private String productNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zdj_table2.CURRENCY
     *
     * @mbg.generated
     */
    private String currency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zdj_table2.TERM
     *
     * @mbg.generated
     */
    private String term;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zdj_table2.END_DATE
     *
     * @mbg.generated
     */
    private String endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zdj_table2.AMOUNT
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zdj_table2
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zdj_table2.BRANCH
     *
     * @return the value of zdj_table2.BRANCH
     *
     * @mbg.generated
     */
    public String getBranch() {
        return branch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zdj_table2.BRANCH
     *
     * @param branch the value for zdj_table2.BRANCH
     *
     * @mbg.generated
     */
    public void setBranch(String branch) {
        this.branch = branch == null ? null : branch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zdj_table2.ACCT_NO
     *
     * @return the value of zdj_table2.ACCT_NO
     *
     * @mbg.generated
     */
    public String getAcctNo() {
        return acctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zdj_table2.ACCT_NO
     *
     * @param acctNo the value for zdj_table2.ACCT_NO
     *
     * @mbg.generated
     */
    public void setAcctNo(String acctNo) {
        this.acctNo = acctNo == null ? null : acctNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zdj_table2.CUST_NO
     *
     * @return the value of zdj_table2.CUST_NO
     *
     * @mbg.generated
     */
    public String getCustNo() {
        return custNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zdj_table2.CUST_NO
     *
     * @param custNo the value for zdj_table2.CUST_NO
     *
     * @mbg.generated
     */
    public void setCustNo(String custNo) {
        this.custNo = custNo == null ? null : custNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zdj_table2.PRODUCT_NO
     *
     * @return the value of zdj_table2.PRODUCT_NO
     *
     * @mbg.generated
     */
    public String getProductNo() {
        return productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zdj_table2.PRODUCT_NO
     *
     * @param productNo the value for zdj_table2.PRODUCT_NO
     *
     * @mbg.generated
     */
    public void setProductNo(String productNo) {
        this.productNo = productNo == null ? null : productNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zdj_table2.CURRENCY
     *
     * @return the value of zdj_table2.CURRENCY
     *
     * @mbg.generated
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zdj_table2.CURRENCY
     *
     * @param currency the value for zdj_table2.CURRENCY
     *
     * @mbg.generated
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zdj_table2.TERM
     *
     * @return the value of zdj_table2.TERM
     *
     * @mbg.generated
     */
    public String getTerm() {
        return term;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zdj_table2.TERM
     *
     * @param term the value for zdj_table2.TERM
     *
     * @mbg.generated
     */
    public void setTerm(String term) {
        this.term = term == null ? null : term.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zdj_table2.END_DATE
     *
     * @return the value of zdj_table2.END_DATE
     *
     * @mbg.generated
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zdj_table2.END_DATE
     *
     * @param endDate the value for zdj_table2.END_DATE
     *
     * @mbg.generated
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate == null ? null : endDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zdj_table2.AMOUNT
     *
     * @return the value of zdj_table2.AMOUNT
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zdj_table2.AMOUNT
     *
     * @param amount the value for zdj_table2.AMOUNT
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zdj_table2
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", branch=").append(branch);
        sb.append(", acctNo=").append(acctNo);
        sb.append(", custNo=").append(custNo);
        sb.append(", productNo=").append(productNo);
        sb.append(", currency=").append(currency);
        sb.append(", term=").append(term);
        sb.append(", endDate=").append(endDate);
        sb.append(", amount=").append(amount);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}