package com.heiheipp.common.mbg.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class ZdjTable1 extends BaseModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zdj_table1.BRANCH
     *
     * @mbg.generated
     */
    private String branch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zdj_table1.TRAN_SEQ
     *
     * @mbg.generated
     */
    private String tranSeq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zdj_table1.ACCT_NO
     *
     * @mbg.generated
     */
    private String acctNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zdj_table1.AMOUNT
     *
     * @mbg.generated
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zdj_table1.TRAN_CODE
     *
     * @mbg.generated
     */
    private String tranCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zdj_table1.TELLER_NO
     *
     * @mbg.generated
     */
    private String tellerNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zdj_table1.CUST_NO
     *
     * @mbg.generated
     */
    private String custNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zdj_table1.TRAN_DATE
     *
     * @mbg.generated
     */
    private String tranDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zdj_table1.TRAN_TIME
     *
     * @mbg.generated
     */
    private String tranTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zdj_table1.TELLER_NO1
     *
     * @mbg.generated
     */
    private String tellerNo1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zdj_table1
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zdj_table1.BRANCH
     *
     * @return the value of zdj_table1.BRANCH
     *
     * @mbg.generated
     */
    public String getBranch() {
        return branch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zdj_table1.BRANCH
     *
     * @param branch the value for zdj_table1.BRANCH
     *
     * @mbg.generated
     */
    public void setBranch(String branch) {
        this.branch = branch == null ? null : branch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zdj_table1.TRAN_SEQ
     *
     * @return the value of zdj_table1.TRAN_SEQ
     *
     * @mbg.generated
     */
    public String getTranSeq() {
        return tranSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zdj_table1.TRAN_SEQ
     *
     * @param tranSeq the value for zdj_table1.TRAN_SEQ
     *
     * @mbg.generated
     */
    public void setTranSeq(String tranSeq) {
        this.tranSeq = tranSeq == null ? null : tranSeq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zdj_table1.ACCT_NO
     *
     * @return the value of zdj_table1.ACCT_NO
     *
     * @mbg.generated
     */
    public String getAcctNo() {
        return acctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zdj_table1.ACCT_NO
     *
     * @param acctNo the value for zdj_table1.ACCT_NO
     *
     * @mbg.generated
     */
    public void setAcctNo(String acctNo) {
        this.acctNo = acctNo == null ? null : acctNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zdj_table1.AMOUNT
     *
     * @return the value of zdj_table1.AMOUNT
     *
     * @mbg.generated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zdj_table1.AMOUNT
     *
     * @param amount the value for zdj_table1.AMOUNT
     *
     * @mbg.generated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zdj_table1.TRAN_CODE
     *
     * @return the value of zdj_table1.TRAN_CODE
     *
     * @mbg.generated
     */
    public String getTranCode() {
        return tranCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zdj_table1.TRAN_CODE
     *
     * @param tranCode the value for zdj_table1.TRAN_CODE
     *
     * @mbg.generated
     */
    public void setTranCode(String tranCode) {
        this.tranCode = tranCode == null ? null : tranCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zdj_table1.TELLER_NO
     *
     * @return the value of zdj_table1.TELLER_NO
     *
     * @mbg.generated
     */
    public String getTellerNo() {
        return tellerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zdj_table1.TELLER_NO
     *
     * @param tellerNo the value for zdj_table1.TELLER_NO
     *
     * @mbg.generated
     */
    public void setTellerNo(String tellerNo) {
        this.tellerNo = tellerNo == null ? null : tellerNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zdj_table1.CUST_NO
     *
     * @return the value of zdj_table1.CUST_NO
     *
     * @mbg.generated
     */
    public String getCustNo() {
        return custNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zdj_table1.CUST_NO
     *
     * @param custNo the value for zdj_table1.CUST_NO
     *
     * @mbg.generated
     */
    public void setCustNo(String custNo) {
        this.custNo = custNo == null ? null : custNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zdj_table1.TRAN_DATE
     *
     * @return the value of zdj_table1.TRAN_DATE
     *
     * @mbg.generated
     */
    public String getTranDate() {
        return tranDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zdj_table1.TRAN_DATE
     *
     * @param tranDate the value for zdj_table1.TRAN_DATE
     *
     * @mbg.generated
     */
    public void setTranDate(String tranDate) {
        this.tranDate = tranDate == null ? null : tranDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zdj_table1.TRAN_TIME
     *
     * @return the value of zdj_table1.TRAN_TIME
     *
     * @mbg.generated
     */
    public String getTranTime() {
        return tranTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zdj_table1.TRAN_TIME
     *
     * @param tranTime the value for zdj_table1.TRAN_TIME
     *
     * @mbg.generated
     */
    public void setTranTime(String tranTime) {
        this.tranTime = tranTime == null ? null : tranTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zdj_table1.TELLER_NO1
     *
     * @return the value of zdj_table1.TELLER_NO1
     *
     * @mbg.generated
     */
    public String getTellerNo1() {
        return tellerNo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zdj_table1.TELLER_NO1
     *
     * @param tellerNo1 the value for zdj_table1.TELLER_NO1
     *
     * @mbg.generated
     */
    public void setTellerNo1(String tellerNo1) {
        this.tellerNo1 = tellerNo1 == null ? null : tellerNo1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zdj_table1
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", branch=").append(branch);
        sb.append(", tranSeq=").append(tranSeq);
        sb.append(", acctNo=").append(acctNo);
        sb.append(", amount=").append(amount);
        sb.append(", tranCode=").append(tranCode);
        sb.append(", tellerNo=").append(tellerNo);
        sb.append(", custNo=").append(custNo);
        sb.append(", tranDate=").append(tranDate);
        sb.append(", tranTime=").append(tranTime);
        sb.append(", tellerNo1=").append(tellerNo1);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}