package com.heiheipp.common.mbg.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class ZdjTable3 extends BaseModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zdj_table3.BRANCH
     *
     * @mbg.generated
     */
    private String branch;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zdj_table3.ACCT_NO
     *
     * @mbg.generated
     */
    private String acctNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zdj_table3.PRODUCT_NO
     *
     * @mbg.generated
     */
    private String productNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zdj_table3.CURRENCY
     *
     * @mbg.generated
     */
    private String currency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zdj_table3.TERM
     *
     * @mbg.generated
     */
    private String term;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zdj_table3.INST
     *
     * @mbg.generated
     */
    private BigDecimal inst;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zdj_table3.SIGN_DATE
     *
     * @mbg.generated
     */
    private String signDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zdj_table3.STATUS
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zdj_table3
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zdj_table3.BRANCH
     *
     * @return the value of zdj_table3.BRANCH
     *
     * @mbg.generated
     */
    public String getBranch() {
        return branch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zdj_table3.BRANCH
     *
     * @param branch the value for zdj_table3.BRANCH
     *
     * @mbg.generated
     */
    public void setBranch(String branch) {
        this.branch = branch == null ? null : branch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zdj_table3.ACCT_NO
     *
     * @return the value of zdj_table3.ACCT_NO
     *
     * @mbg.generated
     */
    public String getAcctNo() {
        return acctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zdj_table3.ACCT_NO
     *
     * @param acctNo the value for zdj_table3.ACCT_NO
     *
     * @mbg.generated
     */
    public void setAcctNo(String acctNo) {
        this.acctNo = acctNo == null ? null : acctNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zdj_table3.PRODUCT_NO
     *
     * @return the value of zdj_table3.PRODUCT_NO
     *
     * @mbg.generated
     */
    public String getProductNo() {
        return productNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zdj_table3.PRODUCT_NO
     *
     * @param productNo the value for zdj_table3.PRODUCT_NO
     *
     * @mbg.generated
     */
    public void setProductNo(String productNo) {
        this.productNo = productNo == null ? null : productNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zdj_table3.CURRENCY
     *
     * @return the value of zdj_table3.CURRENCY
     *
     * @mbg.generated
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zdj_table3.CURRENCY
     *
     * @param currency the value for zdj_table3.CURRENCY
     *
     * @mbg.generated
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zdj_table3.TERM
     *
     * @return the value of zdj_table3.TERM
     *
     * @mbg.generated
     */
    public String getTerm() {
        return term;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zdj_table3.TERM
     *
     * @param term the value for zdj_table3.TERM
     *
     * @mbg.generated
     */
    public void setTerm(String term) {
        this.term = term == null ? null : term.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zdj_table3.INST
     *
     * @return the value of zdj_table3.INST
     *
     * @mbg.generated
     */
    public BigDecimal getInst() {
        return inst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zdj_table3.INST
     *
     * @param inst the value for zdj_table3.INST
     *
     * @mbg.generated
     */
    public void setInst(BigDecimal inst) {
        this.inst = inst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zdj_table3.SIGN_DATE
     *
     * @return the value of zdj_table3.SIGN_DATE
     *
     * @mbg.generated
     */
    public String getSignDate() {
        return signDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zdj_table3.SIGN_DATE
     *
     * @param signDate the value for zdj_table3.SIGN_DATE
     *
     * @mbg.generated
     */
    public void setSignDate(String signDate) {
        this.signDate = signDate == null ? null : signDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zdj_table3.STATUS
     *
     * @return the value of zdj_table3.STATUS
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zdj_table3.STATUS
     *
     * @param status the value for zdj_table3.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zdj_table3
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", branch=").append(branch);
        sb.append(", acctNo=").append(acctNo);
        sb.append(", productNo=").append(productNo);
        sb.append(", currency=").append(currency);
        sb.append(", term=").append(term);
        sb.append(", inst=").append(inst);
        sb.append(", signDate=").append(signDate);
        sb.append(", status=").append(status);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}