package com.heiheipp.ctiqbusiapi.entity;

import java.io.Serializable;
import java.util.Date;

public class TestDetail implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_detail.UNN_TRNO
     *
     * @mbg.generated
     */
    private Integer unnTrno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_detail.TXN_DT
     *
     * @mbg.generated
     */
    private Date txnDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_detail.TXN_ACCNO
     *
     * @mbg.generated
     */
    private String txnAccno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_detail.SUMMRY
     *
     * @mbg.generated
     */
    private String summry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_detail
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_detail.UNN_TRNO
     *
     * @return the value of test_detail.UNN_TRNO
     *
     * @mbg.generated
     */
    public Integer getUnnTrno() {
        return unnTrno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_detail.UNN_TRNO
     *
     * @param unnTrno the value for test_detail.UNN_TRNO
     *
     * @mbg.generated
     */
    public void setUnnTrno(Integer unnTrno) {
        this.unnTrno = unnTrno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_detail.TXN_DT
     *
     * @return the value of test_detail.TXN_DT
     *
     * @mbg.generated
     */
    public Date getTxnDt() {
        return txnDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_detail.TXN_DT
     *
     * @param txnDt the value for test_detail.TXN_DT
     *
     * @mbg.generated
     */
    public void setTxnDt(Date txnDt) {
        this.txnDt = txnDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_detail.TXN_ACCNO
     *
     * @return the value of test_detail.TXN_ACCNO
     *
     * @mbg.generated
     */
    public String getTxnAccno() {
        return txnAccno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_detail.TXN_ACCNO
     *
     * @param txnAccno the value for test_detail.TXN_ACCNO
     *
     * @mbg.generated
     */
    public void setTxnAccno(String txnAccno) {
        this.txnAccno = txnAccno == null ? null : txnAccno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_detail.SUMMRY
     *
     * @return the value of test_detail.SUMMRY
     *
     * @mbg.generated
     */
    public String getSummry() {
        return summry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_detail.SUMMRY
     *
     * @param summry the value for test_detail.SUMMRY
     *
     * @mbg.generated
     */
    public void setSummry(String summry) {
        this.summry = summry == null ? null : summry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_detail
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", unnTrno=").append(unnTrno);
        sb.append(", txnDt=").append(txnDt);
        sb.append(", txnAccno=").append(txnAccno);
        sb.append(", summry=").append(summry);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}