package com.heiheipp.ctiqbusiapi.entity;

import java.io.Serializable;
import java.util.Date;

public class TestDetailAgg implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_detail_agg.UNN_TRNO
     *
     * @mbg.generated
     */
    private Integer unnTrno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_detail_agg.TXN_DT
     *
     * @mbg.generated
     */
    private Date txnDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_detail_agg.TXN_ACCNO
     *
     * @mbg.generated
     */
    private String txnAccno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_detail_agg.SUMMRY
     *
     * @mbg.generated
     */
    private String summry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_detail_agg.TRAN_TYPE
     *
     * @mbg.generated
     */
    private String tranType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_detail_agg.TXN_AMT
     *
     * @mbg.generated
     */
    private Integer txnAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_detail_agg
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_detail_agg.UNN_TRNO
     *
     * @return the value of test_detail_agg.UNN_TRNO
     *
     * @mbg.generated
     */
    public Integer getUnnTrno() {
        return unnTrno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_detail_agg.UNN_TRNO
     *
     * @param unnTrno the value for test_detail_agg.UNN_TRNO
     *
     * @mbg.generated
     */
    public void setUnnTrno(Integer unnTrno) {
        this.unnTrno = unnTrno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_detail_agg.TXN_DT
     *
     * @return the value of test_detail_agg.TXN_DT
     *
     * @mbg.generated
     */
    public Date getTxnDt() {
        return txnDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_detail_agg.TXN_DT
     *
     * @param txnDt the value for test_detail_agg.TXN_DT
     *
     * @mbg.generated
     */
    public void setTxnDt(Date txnDt) {
        this.txnDt = txnDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_detail_agg.TXN_ACCNO
     *
     * @return the value of test_detail_agg.TXN_ACCNO
     *
     * @mbg.generated
     */
    public String getTxnAccno() {
        return txnAccno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_detail_agg.TXN_ACCNO
     *
     * @param txnAccno the value for test_detail_agg.TXN_ACCNO
     *
     * @mbg.generated
     */
    public void setTxnAccno(String txnAccno) {
        this.txnAccno = txnAccno == null ? null : txnAccno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_detail_agg.SUMMRY
     *
     * @return the value of test_detail_agg.SUMMRY
     *
     * @mbg.generated
     */
    public String getSummry() {
        return summry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_detail_agg.SUMMRY
     *
     * @param summry the value for test_detail_agg.SUMMRY
     *
     * @mbg.generated
     */
    public void setSummry(String summry) {
        this.summry = summry == null ? null : summry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_detail_agg.TRAN_TYPE
     *
     * @return the value of test_detail_agg.TRAN_TYPE
     *
     * @mbg.generated
     */
    public String getTranType() {
        return tranType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_detail_agg.TRAN_TYPE
     *
     * @param tranType the value for test_detail_agg.TRAN_TYPE
     *
     * @mbg.generated
     */
    public void setTranType(String tranType) {
        this.tranType = tranType == null ? null : tranType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_detail_agg.TXN_AMT
     *
     * @return the value of test_detail_agg.TXN_AMT
     *
     * @mbg.generated
     */
    public Integer getTxnAmt() {
        return txnAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_detail_agg.TXN_AMT
     *
     * @param txnAmt the value for test_detail_agg.TXN_AMT
     *
     * @mbg.generated
     */
    public void setTxnAmt(Integer txnAmt) {
        this.txnAmt = txnAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_detail_agg
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", unnTrno=").append(unnTrno);
        sb.append(", txnDt=").append(txnDt);
        sb.append(", txnAccno=").append(txnAccno);
        sb.append(", summry=").append(summry);
        sb.append(", tranType=").append(tranType);
        sb.append(", txnAmt=").append(txnAmt);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}