package com.heiheipp.ctiqbusiapi.mapper;

import com.heiheipp.ctiqbusiapi.entity.PagerInput;
import com.heiheipp.ctiqbusiapi.entity.TestDetail;

import java.util.List;

public interface TestDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer unnTrno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_detail
     *
     * @mbg.generated
     */
    int insert(TestDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_detail
     *
     * @mbg.generated
     */
    TestDetail selectByPrimaryKey(Integer unnTrno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_detail
     *
     * @mbg.generated
     */
    List<TestDetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TestDetail record);

    List<TestDetail> selectByPage(PagerInput input);

    int selectPageCount(PagerInput input);
}