package com.heiheipp.ctiqbusiapi.mapper;

import com.heiheipp.ctiqbusiapi.entity.PagerInput;
import com.heiheipp.ctiqbusiapi.entity.TestDetailAgg;

import java.util.List;
import java.util.Map;

public interface TestDetailAggMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_detail_agg
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer unnTrno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_detail_agg
     *
     * @mbg.generated
     */
    int insert(TestDetailAgg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_detail_agg
     *
     * @mbg.generated
     */
    TestDetailAgg selectByPrimaryKey(PagerInput input);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_detail_agg
     *
     * @mbg.generated
     */
    List<TestDetailAgg> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_detail_agg
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TestDetailAgg record);

    List<TestDetailAgg> selectByPage(PagerInput input);

    int selectPageCount(PagerInput input);

    List<Map<String, Object>> selectSumAmtByYear(PagerInput input);
}