DROP TABLE IF EXISTS `cdm_trans_detail`;
CREATE TABLE `cdm_trans_detail` (
  `tran_id` varchar(44) NOT NULL            COMMENT '交易流水号',
  `cust_id` varchar(40) not null            COMMENT '客户号',
  `card_no` varchar(18) not null            COMMENT '卡号',
  `date_time` datetime  not null            COMMENT '交易时间',
  `tran_type` char(4) not null DEFAULT ''   COMMENT '交易类型，0001-转出，0002-转入，0003-支付，0004-消费',
  `tran_cat`  char(1) not null DEFAULT ''   COMMENT '收支方向，0001/0003/0004对应0支出，0002对应1收入',
  `tran_msg`  varchar(50) not null DEFAULT '' COMMENT '交易信息',
  `tran_amount` decimal(21,3) not null DEFAULT '0.0' COMMENT '交易金额',
  `tran_cureen` char(3) DEFAULT '156',
  `acct_avaibala` decimal(21,3) DEFAULT '0.0' COMMENT '账户可用余额',
  `act_name` varchar(140) not null DEFAULT '' COMMENT '户名',
  `remit_type` char(1) DEFAULT '1',
  `opp_actno` varchar(35) DEFAULT '11223344556677889900'  COMMENT '对手方账号',
  `opp_cardno` varchar(19) DEFAULT '9988776655443322' COMMENT '对手方卡号',
  `opp_actname` varchar(140) DEFAULT '某某某某对手方'        COMMENT '对手方户名',
  `opp_brname` varchar(80) DEFAULT '某某某某分行某某支行'          COMMENT '对手方开户行名称',
  `opp_brno` varchar(14) DEFAULT '11223344556677',
  `tran_amountcny` decimal(21,3) DEFAULT '0.0',
  `mer_no` varchar(15) DEFAULT '998877665544332',
  `mer_name` varchar(30) DEFAULT '某某某某商户',
  `rembak` varchar(160) DEFAULT '某某某某备用信息',
  `usage_name` varchar(80) DEFAULT '某某交易用途',
  `tran_ps` varchar(225) DEFAULT '某某某某交易备注',
  `summary` varchar(140) DEFAULT '某某某某摘要',
  `sum_flag` char(1) DEFAULT '1',
  `edit_flag` char(1) DEFAULT '1',
  `sys_code` char(2) DEFAULT '01',
  PRIMARY KEY (cust_id, date_time, tran_id) CLUSTERED
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='交易基础信息表';