package com.heiheipp.common.mbg.mapper;

import com.heiheipp.common.mbg.model.AdsTxnTifBas100c;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdsTxnTifBas100cMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads_txn_tif_bas_100c
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("unnTrno") BigDecimal unnTrno, @Param("txnDt") Date txnDt);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads_txn_tif_bas_100c
     *
     * @mbg.generated
     */
    int insert(AdsTxnTifBas100c record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads_txn_tif_bas_100c
     *
     * @mbg.generated
     */
    AdsTxnTifBas100c selectByPrimaryKey(@Param("unnTrno") BigDecimal unnTrno, @Param("txnDt") Date txnDt);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads_txn_tif_bas_100c
     *
     * @mbg.generated
     */
    List<AdsTxnTifBas100c> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads_txn_tif_bas_100c
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AdsTxnTifBas100c record);

    /**
     * 批量插入
     * @param adsTxnTifBas100cs
     * @return
     */
    int batchInsert(@Param("ads100") List<AdsTxnTifBas100c> adsTxnTifBas100cs);
}