package com.heiheipp.common.mbg.mapper;

import com.heiheipp.common.mbg.model.AdsTxnTifBasFollow;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdsTxnTifBasFollowMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads_txn_tif_bas_follow
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("unnTrno") BigDecimal unnTrno, @Param("txnDt") Date txnDt);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads_txn_tif_bas_follow
     *
     * @mbg.generated
     */
    int insert(AdsTxnTifBasFollow record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads_txn_tif_bas_follow
     *
     * @mbg.generated
     */
    AdsTxnTifBasFollow selectByPrimaryKey(@Param("unnTrno") BigDecimal unnTrno, @Param("txnDt") Date txnDt);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads_txn_tif_bas_follow
     *
     * @mbg.generated
     */
    List<AdsTxnTifBasFollow> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads_txn_tif_bas_follow
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AdsTxnTifBasFollow record);

    /**
     * 批量插入
     * @param adsTxnTifBasFollows
     * @return
     */
    int batchInsert(@Param("adsf") List<AdsTxnTifBasFollow> adsTxnTifBasFollows);
}