package com.heiheipp.common.mbg.mapper;

import com.heiheipp.common.mbg.model.AdsTxnTifBasDetail;
import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdsTxnTifBasDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads_txn_tif_bas_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("unnTrno") BigDecimal unnTrno, @Param("txnDt") Date txnDt);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads_txn_tif_bas_detail
     *
     * @mbg.generated
     */
    int insert(AdsTxnTifBasDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads_txn_tif_bas_detail
     *
     * @mbg.generated
     */
    AdsTxnTifBasDetail selectByPrimaryKey(@Param("unnTrno") BigDecimal unnTrno, @Param("txnDt") Date txnDt);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads_txn_tif_bas_detail
     *
     * @mbg.generated
     */
    List<AdsTxnTifBasDetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads_txn_tif_bas_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AdsTxnTifBasDetail record);

    /**
     * 批量插入
     * @param adsTxnTifBasDetails
     * @return
     */
    int batchInsert(@Param("basdetail") List<AdsTxnTifBasDetail> adsTxnTifBasDetails);
}