package com.heiheipp.common.mbg.mapper;

import com.heiheipp.common.mbg.model.CdmTransDetail;
import java.util.Date;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CdmTransDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdm_trans_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("custId") String custId, @Param("dateTime") Date dateTime, @Param("tranId") String tranId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdm_trans_detail
     *
     * @mbg.generated
     */
    int insert(CdmTransDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdm_trans_detail
     *
     * @mbg.generated
     */
    CdmTransDetail selectByPrimaryKey(@Param("custId") String custId, @Param("dateTime") Date dateTime, @Param("tranId") String tranId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdm_trans_detail
     *
     * @mbg.generated
     */
    List<CdmTransDetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cdm_trans_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CdmTransDetail record);

    /**
     * 批量插入
     * @param cdmTransDetails
     * @return
     */
    int batchInsert(@Param("ctds") List<CdmTransDetail> cdmTransDetails);
}