package com.heiheipp.common.mbg.mapper;

import com.heiheipp.common.mbg.model.CdsTable1;
import java.util.List;

public interface CdsTable1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cds_table_1
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cds_table_1
     *
     * @mbg.generated
     */
    int insert(CdsTable1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cds_table_1
     *
     * @mbg.generated
     */
    CdsTable1 selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cds_table_1
     *
     * @mbg.generated
     */
    List<CdsTable1> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cds_table_1
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CdsTable1 record);
}