package com.heiheipp.common.mbg.mapper;

import com.heiheipp.common.mbg.model.CdsTable2;
import java.util.List;

public interface CdsTable2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cds_table_2
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cds_table_2
     *
     * @mbg.generated
     */
    int insert(CdsTable2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cds_table_2
     *
     * @mbg.generated
     */
    CdsTable2 selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cds_table_2
     *
     * @mbg.generated
     */
    List<CdsTable2> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cds_table_2
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CdsTable2 record);
}