package com.heiheipp.common.mbg.mapper;

import com.heiheipp.common.mbg.model.DwdTransDetail;
import java.util.List;

public interface DwdTransDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwd_trans_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String tranId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwd_trans_detail
     *
     * @mbg.generated
     */
    int insert(DwdTransDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwd_trans_detail
     *
     * @mbg.generated
     */
    DwdTransDetail selectByPrimaryKey(String tranId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwd_trans_detail
     *
     * @mbg.generated
     */
    List<DwdTransDetail> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dwd_trans_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DwdTransDetail record);
}