package com.heiheipp.common.mbg.mapper;

import com.heiheipp.common.mbg.model.SzTable1;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SzTable1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sz_table_1
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("bankNo") String bankNo, @Param("jizhangDate") String jizhangDate, @Param("tranDate") String tranDate, @Param("tranTime") String tranTime, @Param("tranSeq") String tranSeq, @Param("fenluSeq") String fenluSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sz_table_1
     *
     * @mbg.generated
     */
    int insert(SzTable1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sz_table_1
     *
     * @mbg.generated
     */
    SzTable1 selectByPrimaryKey(@Param("bankNo") String bankNo, @Param("jizhangDate") String jizhangDate, @Param("tranDate") String tranDate, @Param("tranTime") String tranTime, @Param("tranSeq") String tranSeq, @Param("fenluSeq") String fenluSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sz_table_1
     *
     * @mbg.generated
     */
    List<SzTable1> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sz_table_1
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SzTable1 record);

    /**
     * 批量插入
     * @param szTable1s
     * @return
     */
    int batchInsert(@Param("szTable1") List<SzTable1> szTable1s);
}