package com.heiheipp.common.mbg.mapper;

import com.heiheipp.common.mbg.model.TestTable4;
import com.heiheipp.common.mbg.model.TestTable6;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestTable6Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table_6
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("vCardAppId") String vCardAppId, @Param("nCardAppIssueId") Integer nCardAppIssueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table_6
     *
     * @mbg.generated
     */
    int insert(TestTable6 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table_6
     *
     * @mbg.generated
     */
    TestTable6 selectByPrimaryKey(@Param("vCardAppId") String vCardAppId, @Param("nCardAppIssueId") Integer nCardAppIssueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table_6
     *
     * @mbg.generated
     */
    List<TestTable6> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table_6
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TestTable6 record);

    /**
     * 批量插入
     * @param testTable6s
     * @return
     */
    int batchInsert(@Param("tt6") List<TestTable6> testTable6s);
}