package com.heiheipp.common.mbg.mapper;

import com.heiheipp.common.mbg.model.TestTable4;
import com.heiheipp.common.mbg.model.TestTable5;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestTable5Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table_5
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("vRelationId") String vRelationId, @Param("nRelationSeqNo") Integer nRelationSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table_5
     *
     * @mbg.generated
     */
    int insert(TestTable5 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table_5
     *
     * @mbg.generated
     */
    TestTable5 selectByPrimaryKey(@Param("vRelationId") String vRelationId, @Param("nRelationSeqNo") Integer nRelationSeqNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table_5
     *
     * @mbg.generated
     */
    List<TestTable5> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table_5
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TestTable5 record);

    /**
     * 批量插入
     * @param testTable5s
     * @return
     */
    int batchInsert(@Param("tt5") List<TestTable5> testTable5s);
}