package com.heiheipp.common.mbg.mapper;

import com.heiheipp.common.mbg.model.TestHtap2Sordata001;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TestHtap2Sordata001Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST_HTAP2_SORDATA_001
     *
     * @mbg.generated
     */
    int insert(TestHtap2Sordata001 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST_HTAP2_SORDATA_001
     *
     * @mbg.generated
     */
    List<TestHtap2Sordata001> selectAll();

    /**
     * 批量插入
     * @param testTables
     * @return
     */
    int batchInsert(@Param("sordata001") List<TestHtap2Sordata001> testTables);
}