package com.heiheipp.common.mbg.mapper;

import com.heiheipp.common.mbg.model.TestHtap2Result001;
import java.util.List;

public interface TestHtap2Result001Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST_HTAP2_RESULT_001
     *
     * @mbg.generated
     */
    int insert(TestHtap2Result001 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST_HTAP2_RESULT_001
     *
     * @mbg.generated
     */
    List<TestHtap2Result001> selectAll();
}