package com.heiheipp.common.mbg.mapper;

import com.heiheipp.common.mbg.model.TestTable1;
import java.util.List;

public interface TestTable1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table_1
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table_1
     *
     * @mbg.generated
     */
    int insert(TestTable1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table_1
     *
     * @mbg.generated
     */
    TestTable1 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table_1
     *
     * @mbg.generated
     */
    List<TestTable1> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table_1
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TestTable1 record);
}