package com.heiheipp.common.mbg.mapper;

import com.heiheipp.common.mbg.model.TestTable4;
import com.heiheipp.common.mbg.model.TestTable8;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestTable8Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table_8
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("vAccountNumber") String vAccountNumber, @Param("nCycleNo") Integer nCycleNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table_8
     *
     * @mbg.generated
     */
    int insert(TestTable8 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table_8
     *
     * @mbg.generated
     */
    TestTable8 selectByPrimaryKey(@Param("vAccountNumber") String vAccountNumber, @Param("nCycleNo") Integer nCycleNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table_8
     *
     * @mbg.generated
     */
    List<TestTable8> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table_8
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TestTable8 record);

    /**
     * 批量插入
     * @param testTable8s
     * @return
     */
    int batchInsert(@Param("tt8") List<TestTable8> testTable8s);
}