package com.heiheipp.common.mbg.mapper;

import com.heiheipp.common.mbg.model.TestHtap2Sordata002;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TestHtap2Sordata002Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST_HTAP2_SORDATA_002
     *
     * @mbg.generated
     */
    int insert(TestHtap2Sordata002 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST_HTAP2_SORDATA_002
     *
     * @mbg.generated
     */
    List<TestHtap2Sordata002> selectAll();

    /**
     * 批量插入
     * @param testTables
     * @return
     */
    int batchInsert(@Param("sordata002") List<TestHtap2Sordata002> testTables);
}