package com.heiheipp.common.mbg.mapper;

import com.heiheipp.common.mbg.model.TestHtap2Rule001;
import java.util.List;

public interface TestHtap2Rule001Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST_HTAP2_RULE_001
     *
     * @mbg.generated
     */
    int insert(TestHtap2Rule001 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST_HTAP2_RULE_001
     *
     * @mbg.generated
     */
    List<TestHtap2Rule001> selectAll();
}