package com.heiheipp.common.mbg.mapper;

import com.heiheipp.common.mbg.model.CdmTransDetail;
import com.heiheipp.common.mbg.model.TestTable3;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TestTable3Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table_3
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String vCustId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table_3
     *
     * @mbg.generated
     */
    int insert(TestTable3 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table_3
     *
     * @mbg.generated
     */
    TestTable3 selectByPrimaryKey(String vCustId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table_3
     *
     * @mbg.generated
     */
    List<TestTable3> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_table_3
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TestTable3 record);

    /**
     * 批量插入
     * @param testTable3s
     * @return
     */
    int batchInsert(@Param("tt3") List<TestTable3> testTable3s);
}