package com.heiheipp.common.mbg.mapper;

import com.heiheipp.common.mbg.model.TestHtap2Bb001;
import java.util.List;

public interface TestHtap2Bb001Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST_HTAP2_BB_001
     *
     * @mbg.generated
     */
    int insert(TestHtap2Bb001 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TEST_HTAP2_BB_001
     *
     * @mbg.generated
     */
    List<TestHtap2Bb001> selectAll();
}