package com.heiheipp.common.mbg.mapper;

import com.heiheipp.common.mbg.model.ZdjTable2;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ZdjTable2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zdj_table2
     *
     * @mbg.generated
     */
    int insert(ZdjTable2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zdj_table2
     *
     * @mbg.generated
     */
    List<ZdjTable2> selectAll();

    /**
     * 批量插入
     * @param zdjTable2s
     * @return
     */
    int batchInsert(@Param("zdj2") List<ZdjTable2> zdjTable2s);
}