package com.heiheipp.common.mbg.mapper;

import com.heiheipp.common.mbg.model.ZdjTable1;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ZdjTable1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zdj_table1
     *
     * @mbg.generated
     */
    int insert(ZdjTable1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zdj_table1
     *
     * @mbg.generated
     */
    List<ZdjTable1> selectAll();

    /**
     * 批量插入
     * @param zdjTable1s
     * @return
     */
    int batchInsert(@Param("zdj1") List<ZdjTable1> zdjTable1s);
}